/* This function was automatically generated by CasADi */
#ifdef __cplusplus
extern "C" {
#endif

#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else /* CODEGEN_PREFIX */
  #define CASADI_PREFIX(ID) pendulum_ode_generated_ ## ID
#endif /* CODEGEN_PREFIX */

#include <math.h>

#ifndef real_t
#define real_t double
#define to_double(x) (double) x
#define to_int(x) (int) x
#endif /* real_t */

/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
real_t CASADI_PREFIX(fmin)(real_t x, real_t y) { return x<y ? x : y;}
#define fmin(x,y) CASADI_PREFIX(fmin)(x,y)
real_t CASADI_PREFIX(fmax)(real_t x, real_t y) { return x>y ? x : y;}
#define fmax(x,y) CASADI_PREFIX(fmax)(x,y)
#endif

#define PRINTF printf
real_t CASADI_PREFIX(sq)(real_t x) { return x*x;}
#define sq(x) CASADI_PREFIX(sq)(x)

real_t CASADI_PREFIX(sign)(real_t x) { return x<0 ? -1 : x>0 ? 1 : x;}
#define sign(x) CASADI_PREFIX(sign)(x)

void CASADI_PREFIX(copy)(const real_t* x, int n, real_t* y) {
  int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}
#define copy(x, n, y) CASADI_PREFIX(copy)(x, n, y)


void CASADI_PREFIX(fill)(real_t* x, int n, real_t alpha) {
  int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}
#define fill(x, n, alpha) CASADI_PREFIX(fill)(x, n, alpha)


void CASADI_PREFIX(trans)(const real_t* x, const int* sp_x, real_t* y, const int* sp_y, int *tmp) {
  int ncol_x = sp_x[1];
  int nnz_x = sp_x[2 + ncol_x];
  const int* row_x = sp_x + 2 + ncol_x+1;
  int ncol_y = sp_y[1];
  const int* colind_y = sp_y+2;
  int k;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}
#define trans(x, sp_x, y, sp_y, tmp) CASADI_PREFIX(trans)(x, sp_x, y, sp_y, tmp)

void CASADI_PREFIX(project)(const real_t* x, const int* sp_x, real_t* y, const int* sp_y, real_t* w) {
  int ncol_x = sp_x[1];
  const int *colind_x = sp_x+2, *row_x = sp_x + 2 + ncol_x+1;
  int ncol_y = sp_y[1];
  const int *colind_y = sp_y+2, *row_y = sp_y + 2 + ncol_y+1;
  /* Loop over columns of x and y */
  int i, el;
  for (i=0; i<ncol_x; ++i) {
    /* Zero out requested entries in y */
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) w[row_y[el]] = 0;
    /* Set x entries */
    for (el=colind_x[i]; el<colind_x[i+1]; ++el) w[row_x[el]] = x[el];
    /* Retrieve requested entries in y */
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) y[el] = w[row_y[el]];
  }
}
#define project(x, sp_x, y, sp_y, w) CASADI_PREFIX(project)(x, sp_x, y, sp_y, w)


static const int CASADI_PREFIX(s0)[] = {2, 3, 0, 1, 3, 4, 1, 0, 1, 1};
#define s0 CASADI_PREFIX(s0)
static const int CASADI_PREFIX(s1)[] = {3, 2, 0, 1, 4, 1, 0, 1, 2};
#define s1 CASADI_PREFIX(s1)
static const int CASADI_PREFIX(s2)[] = {2, 3, 0, 2, 4, 6, 0, 1, 0, 1, 0, 1};
#define s2 CASADI_PREFIX(s2)
static const int CASADI_PREFIX(s3)[] = {1, 1, 0, 1, 0};
#define s3 CASADI_PREFIX(s3)
static const int CASADI_PREFIX(s4)[] = {3, 1, 0, 3, 0, 1, 2};
#define s4 CASADI_PREFIX(s4)
static const int CASADI_PREFIX(s5)[] = {2, 1, 0, 2, 0, 1};
#define s5 CASADI_PREFIX(s5)
static const int CASADI_PREFIX(s6)[] = {2, 2, 0, 1, 3, 1, 0, 1};
#define s6 CASADI_PREFIX(s6)
static const int CASADI_PREFIX(s7)[] = {2, 2, 0, 2, 4, 0, 1, 0, 1};
#define s7 CASADI_PREFIX(s7)
static const int CASADI_PREFIX(s8)[] = {2, 1, 0, 1, 1};
#define s8 CASADI_PREFIX(s8)
/* pendulum_ode_jac */
int pendulum_ode_jac(const real_t** arg, real_t** res, int* iw, real_t* w, int mem) {
  int i, j, k, *ii, *jj, *kk;
  const int *cii;
  real_t r, s, t, *rr, *ss, *tt;
  const real_t *cr, *cs, *ct;
  const real_t** arg1=arg+2;
  real_t** res1=res+2;
  real_t w0, w1, w2, w3, w4, *w5=w+7, *w6=w+9, *w7=w+13, *w8=w+17;
  w0 = arg[1] ? arg[1][0] : 0;
  w1 = sin( w0 );
  w2 = -9.8100000000000005e+00;
  w1  = (w2*w1);
  w3 = arg[1] ? arg[1][1] : 0;
  w4 = (2.* w3 );
  w1 -= w4;
  w4 = arg[1] ? arg[1][2] : 0;
  w1 += w4;
  rr=w5;
  *rr++ = w3;
  *rr++ = w1;
  if (res[0]) copy(w5, 2, res[0]);
  w0 = cos( w0 );
  w3 = 1.;
  w1 = w3;
  w0 *= w1;
  w2 *= w0;
  fill(w6, 4, 0.);
  for (rr=w6+1, ss=(&w2); rr!=w6+2; rr+=1) *rr = *ss++;
  w2 = 1.;
  w0 = w2;
  w2 = (2.* w0 );
  w2 = (- w2 );
  rr=w5;
  *rr++ = w0;
  *rr++ = w2;
  for (rr=w6+0, ss=w5; rr!=w6+4; rr+=2) *rr = *ss++;
  w0 = 1.;
  w2 = w0;
  for (rr=w6+3, ss=(&w2); rr!=w6+4; rr+=1) *rr = *ss++;
  trans(w6, s1, w7, s0, iw);
    project(w7, s0, w8, s2, w);
  if (res[1]) copy(w8, 6, res[1]);
  return 0;
}

void pendulum_ode_jac_incref(void) {
}

void pendulum_ode_jac_decref(void) {
}

int pendulum_ode_jac_n_in(void) { return 2;}

int pendulum_ode_jac_n_out(void) { return 2;}

const char* pendulum_ode_jac_name_in(int i){
  switch (i) {
  case 0: return "t";
  case 1: return "z0";
  default: return 0;
  }
}

const char* pendulum_ode_jac_name_out(int i){
  switch (i) {
  case 0: return "xdot";
  case 1: return "J";
  default: return 0;
  }
}

const int* pendulum_ode_jac_sparsity_in(int i) {
  switch (i) {
  case 0: return s3;
  case 1: return s4;
  default: return 0;
  }
}

const int* pendulum_ode_jac_sparsity_out(int i) {
  switch (i) {
  case 0: return s5;
  case 1: return s2;
  default: return 0;
  }
}

int pendulum_ode_jac_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 4;
  if (sz_w) *sz_w = 23;
  return 0;
}

/* pendulum_ode_AB */
int pendulum_ode_AB(const real_t** arg, real_t** res, int* iw, real_t* w, int mem) {
  int i, j, k, *ii, *jj, *kk;
  const int *cii;
  real_t r, s, t, *rr, *ss, *tt;
  const real_t *cr, *cs, *ct;
  const real_t** arg1=arg+3;
  real_t** res1=res+3;
  real_t w0, w1, w2, w3, w4, *w5=w+7, *w6=w+9, *w7=w+12, *w8=w+15;
  w0 = arg[1] ? arg[1][0] : 0;
  w1 = sin( w0 );
  w2 = -9.8100000000000005e+00;
  w1  = (w2*w1);
  w3 = arg[1] ? arg[1][1] : 0;
  w4 = (2.* w3 );
  w1 -= w4;
  w4 = arg[2] ? arg[2][0] : 0;
  w1 += w4;
  rr=w5;
  *rr++ = w3;
  *rr++ = w1;
  if (res[0]) copy(w5, 2, res[0]);
  w0 = cos( w0 );
  w3 = 1.;
  w1 = w3;
  w0 *= w1;
  w2 *= w0;
  fill(w6, 3, 0.);
  for (rr=w6+1, ss=(&w2); rr!=w6+2; rr+=1) *rr = *ss++;
  w2 = 1.;
  w0 = w2;
  w2 = (2.* w0 );
  w2 = (- w2 );
  rr=w5;
  *rr++ = w0;
  *rr++ = w2;
  for (rr=w6+0, ss=w5; rr!=w6+4; rr+=2) *rr = *ss++;
  trans(w6, s6, w7, s6, iw);
    project(w7, s6, w8, s7, w);
  if (res[1]) copy(w8, 4, res[1]);
  w0 = 0.;
  w2 = 1.;
  for (rr=(&w0)+0, ss=(&w2); rr!=(&w0)+1; rr+=1) *rr = *ss++;
    project((&w0), s8, w5, s5, w);
  if (res[2]) copy(w5, 2, res[2]);
  return 0;
}

void pendulum_ode_AB_incref(void) {
}

void pendulum_ode_AB_decref(void) {
}

int pendulum_ode_AB_n_in(void) { return 3;}

int pendulum_ode_AB_n_out(void) { return 3;}

const char* pendulum_ode_AB_name_in(int i){
  switch (i) {
  case 0: return "t";
  case 1: return "x0";
  case 2: return "u0";
  default: return 0;
  }
}

const char* pendulum_ode_AB_name_out(int i){
  switch (i) {
  case 0: return "xdot";
  case 1: return "A";
  case 2: return "B";
  default: return 0;
  }
}

const int* pendulum_ode_AB_sparsity_in(int i) {
  switch (i) {
  case 0: return s3;
  case 1: return s5;
  case 2: return s3;
  default: return 0;
  }
}

const int* pendulum_ode_AB_sparsity_out(int i) {
  switch (i) {
  case 0: return s5;
  case 1: return s7;
  case 2: return s5;
  default: return 0;
  }
}

int pendulum_ode_AB_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 3;
  if (sz_w) *sz_w = 19;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
