/* This function was automatically generated by CasADi */
#ifdef __cplusplus
extern "C" {
#endif

#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else /* CODEGEN_PREFIX */
  #define CASADI_PREFIX(ID) casadi_function_test_generated_ ## ID
#endif /* CODEGEN_PREFIX */

#include <math.h>

#ifndef real_t
#define real_t double
#endif /* real_t */

#define to_double(x) (double) x
#define to_int(x) (int) x
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
real_t CASADI_PREFIX(fmin)(real_t x, real_t y) { return x<y ? x : y;}
#define fmin(x,y) CASADI_PREFIX(fmin)(x,y)
real_t CASADI_PREFIX(fmax)(real_t x, real_t y) { return x>y ? x : y;}
#define fmax(x,y) CASADI_PREFIX(fmax)(x,y)
#endif

#define PRINTF printf
real_t CASADI_PREFIX(sq)(real_t x) { return x*x;}
#define sq(x) CASADI_PREFIX(sq)(x)

real_t CASADI_PREFIX(sign)(real_t x) { return x<0 ? -1 : x>0 ? 1 : x;}
#define sign(x) CASADI_PREFIX(sign)(x)

void CASADI_PREFIX(fill)(real_t* x, int n, real_t alpha) {
  int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}
#define fill(x, n, alpha) CASADI_PREFIX(fill)(x, n, alpha)


void CASADI_PREFIX(copy)(const real_t* x, int n, real_t* y) {
  int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}
#define copy(x, n, y) CASADI_PREFIX(copy)(x, n, y)


static const int CASADI_PREFIX(s0)[11] = {3, 2, 0, 3, 6, 0, 1, 2, 0, 1, 2};
#define s0 CASADI_PREFIX(s0)
static const int CASADI_PREFIX(s1)[9] = {2, 2, 0, 2, 4, 0, 1, 0, 1};
#define s1 CASADI_PREFIX(s1)
static const int CASADI_PREFIX(s2)[5] = {1, 1, 0, 1, 0};
#define s2 CASADI_PREFIX(s2)
static const int CASADI_PREFIX(s3)[7] = {1, 2, 0, 1, 2, 0, 0};
#define s3 CASADI_PREFIX(s3)
/* f */
int f(const real_t** arg, real_t** res, int* iw, real_t* w, int mem) {
  int i, j, k, *ii, *jj, *kk;
  const int *cii;
  real_t r, s, t, *rr, *ss, *tt;
  const real_t *cr, *cs, *ct;
  const real_t** arg1=arg+3;
  real_t** res1=res+2;
  real_t *w0=w+3, w1, *w2=w+10, *w3=w+16, *w4=w+22, *w5=w+26, *w6=w+28;
  /* #0: Input 0 (i0), part 0 (A) */
  if (arg[0])
    copy(arg[0], 6, w0);
  else 
    fill(w0, 6, 0);
  /* #1: Input 2 (i2), part 0 (x) */
  w1 = arg[2] ? arg[2][0] : 0;
  /* #2: @2 = (@0*@1) */
  for (i=0, rr=w2, cr=w0; i<6; ++i) (*rr++)  = ((*cr++)*w1);
  /* #3: @3 = zeros(3x2, dense) */
  fill(w3, 6, 0.);
  /* #4: Input 1 (i1), part 0 (B) */
  if (arg[1])
    copy(arg[1], 4, w4);
  else 
    fill(w4, 4, 0);
  /* #5: @3 = mac(@2,@4,@3) */
  for (i=0, rr=w3; i<2; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w2+j, tt=w4+i*2; k<2; ++k) *rr += ss[k*3]**tt++;
  /* #6: Output 0 (o0) */
  if (res[0]) copy(w3, 6, res[0]);
  /* #7: @3 = zeros(3x2, dense) */
  fill(w3, 6, 0.);
  /* #8: @3 = mac(@0,@4,@3) */
  for (i=0, rr=w3; i<2; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w0+j, tt=w4+i*2; k<2; ++k) *rr += ss[k*3]**tt++;
  /* #9: @5 = zeros(1x2, dense) */
  fill(w5, 2, 0.);
  /* #10: @6 = ones(1x3, dense) */
  fill(w6, 3, 1.);
  /* #11: @5 = mac(@6,@3,@5) */
  for (i=0, rr=w5; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w6+j, tt=w3+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #12: Output 1 (o1) */
  if (res[1]) copy(w5, 2, res[1]);
  return 0;
}

void f_incref(void) {
}

void f_decref(void) {
}

int f_n_in(void) { return 3;}

int f_n_out(void) { return 2;}

const char* f_name_in(int i){
  switch (i) {
  case 0: return "i0";
  case 1: return "i1";
  case 2: return "i2";
  default: return 0;
  }
}

const char* f_name_out(int i){
  switch (i) {
  case 0: return "o0";
  case 1: return "o1";
  default: return 0;
  }
}

const int* f_sparsity_in(int i) {
  switch (i) {
  case 0: return s0;
  case 1: return s1;
  case 2: return s2;
  default: return 0;
  }
}

const int* f_sparsity_out(int i) {
  switch (i) {
  case 0: return s0;
  case 1: return s3;
  default: return 0;
  }
}

int f_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 31;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
