/* This function was automatically generated by CasADi */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef real_t
#define real_t double
#endif /* real_t */

int f(const real_t** arg, real_t** res, int* iw, real_t* w, int mem);
void f_incref(void);
void f_decref(void);
int f_n_in(void);
int f_n_out(void);
const char* f_name_in(int i);
const char* f_name_out(int i);
const int* f_sparsity_in(int i);
const int* f_sparsity_out(int i);
int f_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w);
#ifdef __cplusplus
} /* extern "C" */
#endif
