/* This function was automatically generated by CasADi */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef real_t
#define real_t double
#define to_double(x) (double) x
#define to_int(x) (int) x
#endif /* real_t */

int chen1998_ode_AB(const real_t** arg, real_t** res, int* iw, real_t* w, int mem);
void chen1998_ode_AB_incref(void);
void chen1998_ode_AB_decref(void);
int chen1998_ode_AB_n_in(void);
int chen1998_ode_AB_n_out(void);
const char* chen1998_ode_AB_name_in(int i);
const char* chen1998_ode_AB_name_out(int i);
const int* chen1998_ode_AB_sparsity_in(int i);
const int* chen1998_ode_AB_sparsity_out(int i);
int chen1998_ode_AB_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w);
#ifdef __cplusplus
} /* extern "C" */
#endif
