/* This function was automatically generated by CasADi */
#ifdef __cplusplus
extern "C" {
#endif

#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else /* CODEGEN_PREFIX */
  #define CASADI_PREFIX(ID) chen1998_ode_generated_ ## ID
#endif /* CODEGEN_PREFIX */

#include <math.h>

#ifndef real_t
#define real_t double
#define to_double(x) (double) x
#define to_int(x) (int) x
#endif /* real_t */

/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
real_t CASADI_PREFIX(fmin)(real_t x, real_t y) { return x<y ? x : y;}
#define fmin(x,y) CASADI_PREFIX(fmin)(x,y)
real_t CASADI_PREFIX(fmax)(real_t x, real_t y) { return x>y ? x : y;}
#define fmax(x,y) CASADI_PREFIX(fmax)(x,y)
#endif

#define PRINTF printf
real_t CASADI_PREFIX(sq)(real_t x) { return x*x;}
#define sq(x) CASADI_PREFIX(sq)(x)

real_t CASADI_PREFIX(sign)(real_t x) { return x<0 ? -1 : x>0 ? 1 : x;}
#define sign(x) CASADI_PREFIX(sign)(x)

void CASADI_PREFIX(copy)(const real_t* x, int n, real_t* y) {
  int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}
#define copy(x, n, y) CASADI_PREFIX(copy)(x, n, y)


void CASADI_PREFIX(fill)(real_t* x, int n, real_t alpha) {
  int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}
#define fill(x, n, alpha) CASADI_PREFIX(fill)(x, n, alpha)


static const int CASADI_PREFIX(s0)[] = {1, 1, 0, 1, 0};
#define s0 CASADI_PREFIX(s0)
static const int CASADI_PREFIX(s1)[] = {2, 1, 0, 2, 0, 1};
#define s1 CASADI_PREFIX(s1)
static const int CASADI_PREFIX(s2)[] = {2, 2, 0, 2, 4, 0, 1, 0, 1};
#define s2 CASADI_PREFIX(s2)
/* chen1998_ode_AB */
int chen1998_ode_AB(const real_t** arg, real_t** res, int* iw, real_t* w, int mem) {
  int i, j, k, *ii, *jj, *kk;
  const int *cii;
  real_t r, s, t, *rr, *ss, *tt;
  const real_t *cr, *cs, *ct;
  const real_t** arg1=arg+3;
  real_t** res1=res+3;
  real_t w0, w1, w2, w3, w4, w5, w6, *w7=w+7, *w8=w+9, *w9=w+13, *w10=w+17;
  w0 = 5.0000000000000000e-01;
  w1 = arg[1] ? arg[1][0] : 0;
  w2  = (w0*w1);
  w3 = 5.0000000000000000e-01;
  w3 += w2;
  w2 = arg[2] ? arg[2][0] : 0;
  w4  = (w2*w3);
  w5 = arg[1] ? arg[1][1] : 0;
  w4  = (w5+w4);
  w5 = (2.* w5 );
  w6 = 5.0000000000000000e-01;
  w6 -= w5;
  w5  = (w2*w6);
  w1 += w5;
  rr=w7;
  *rr++ = w4;
  *rr++ = w1;
  if (res[0]) copy(w7, 2, res[0]);
  w4 = 1.;
  w1 = w4;
  w0 *= w1;
  w0  = (w2*w0);
  rr=w7;
  *rr++ = w0;
  *rr++ = w1;
  fill(w8, 4, 0.);
  for (rr=w8+0, ss=w7; rr!=w8+4; rr+=2) *rr = *ss++;
  w0 = 1.;
  w1 = w0;
  w0 = (2.* w1 );
  w2 *= w0;
  w2 = (- w2 );
  rr=w7;
  *rr++ = w1;
  *rr++ = w2;
  for (rr=w8+1, ss=w7; rr!=w8+5; rr+=2) *rr = *ss++;
  for (i=0, rr=w9, cs=w8; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  if (res[1]) copy(w9, 4, res[1]);
  rr=w7;
  *rr++ = w3;
  *rr++ = w6;
  fill(w10, 2, 0.);
  for (rr=w10+0, ss=w7; rr!=w10+2; rr+=1) *rr = *ss++;
  if (res[2]) copy(w10, 2, res[2]);
  return 0;
}

void chen1998_ode_AB_incref(void) {
}

void chen1998_ode_AB_decref(void) {
}

int chen1998_ode_AB_n_in(void) { return 3;}

int chen1998_ode_AB_n_out(void) { return 3;}

const char* chen1998_ode_AB_name_in(int i){
  switch (i) {
  case 0: return "t";
  case 1: return "x0";
  case 2: return "u0";
  default: return 0;
  }
}

const char* chen1998_ode_AB_name_out(int i){
  switch (i) {
  case 0: return "xdot";
  case 1: return "A";
  case 2: return "B";
  default: return 0;
  }
}

const int* chen1998_ode_AB_sparsity_in(int i) {
  switch (i) {
  case 0: return s0;
  case 1: return s1;
  case 2: return s0;
  default: return 0;
  }
}

const int* chen1998_ode_AB_sparsity_out(int i) {
  switch (i) {
  case 0: return s1;
  case 1: return s2;
  case 2: return s1;
  default: return 0;
  }
}

int chen1998_ode_AB_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 19;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
