/* This function was automatically generated by CasADi */
#ifdef __cplusplus
extern "C" {
#endif

#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else /* CODEGEN_PREFIX */
  #define CASADI_PREFIX(ID) cablerobot_output_ ## ID
#endif /* CODEGEN_PREFIX */

#include <math.h>

#ifndef real_t
#define real_t double
#define to_double(x) (double) x
#define to_int(x) (int) x
#endif /* real_t */

/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
real_t CASADI_PREFIX(fmin)(real_t x, real_t y) { return x<y ? x : y;}
#define fmin(x,y) CASADI_PREFIX(fmin)(x,y)
real_t CASADI_PREFIX(fmax)(real_t x, real_t y) { return x>y ? x : y;}
#define fmax(x,y) CASADI_PREFIX(fmax)(x,y)
#endif

#define PRINTF printf
real_t CASADI_PREFIX(sq)(real_t x) { return x*x;}
#define sq(x) CASADI_PREFIX(sq)(x)

real_t CASADI_PREFIX(sign)(real_t x) { return x<0 ? -1 : x>0 ? 1 : x;}
#define sign(x) CASADI_PREFIX(sign)(x)

void CASADI_PREFIX(fill)(real_t* x, int n, real_t alpha) {
  int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}
#define fill(x, n, alpha) CASADI_PREFIX(fill)(x, n, alpha)


void CASADI_PREFIX(copy)(const real_t* x, int n, real_t* y) {
  int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}
#define copy(x, n, y) CASADI_PREFIX(copy)(x, n, y)


real_t CASADI_PREFIX(dot)(int n, const real_t* x, const real_t* y) {
  real_t r = 0;
  int i;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}
#define dot(n, x, y) CASADI_PREFIX(dot)(n, x, y)


void CASADI_PREFIX(trans)(const real_t* x, const int* sp_x, real_t* y, const int* sp_y, int *tmp) {
  int ncol_x = sp_x[1];
  int nnz_x = sp_x[2 + ncol_x];
  const int* row_x = sp_x + 2 + ncol_x+1;
  int ncol_y = sp_y[1];
  const int* colind_y = sp_y+2;
  int k;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}
#define trans(x, sp_x, y, sp_y, tmp) CASADI_PREFIX(trans)(x, sp_x, y, sp_y, tmp)

void CASADI_PREFIX(mtimes)(const real_t* x, const int* sp_x, const real_t* y, const int* sp_y, real_t* z, const int* sp_z, real_t* w, int tr) {
  /* Get sparsities */
  int ncol_x = sp_x[1];
  const int *colind_x = sp_x+2, *row_x = sp_x + 2 + ncol_x+1;
  int ncol_y = sp_y[1];
  const int *colind_y = sp_y+2, *row_y = sp_y + 2 + ncol_y+1;
  int ncol_z = sp_z[1];
  const int *colind_z = sp_z+2, *row_z = sp_z + 2 + ncol_z+1;
  int cc,kk, kk1;
  if (tr) {
    /* Loop over the columns of y and z */
    for (cc=0; cc<ncol_z; ++cc) {
      /* Get the dense column of y */
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      /* Loop over the nonzeros of z */
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        int rr = row_z[kk];
        /* Loop over corresponding columns of x */
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    /* Loop over the columns of y and z */
    for (cc=0; cc<ncol_y; ++cc) {
      /* Get the dense column of z */
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      /* Loop over the nonzeros of y */
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        int rr = row_y[kk];
        /* Loop over corresponding columns of x */
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      /* Get the sparse column of z */
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}
#define mtimes(x, sp_x, y, sp_y, z, sp_z, w, tr) CASADI_PREFIX(mtimes)(x, sp_x, y, sp_y, z, sp_z, w, tr)

void CASADI_PREFIX(project)(const real_t* x, const int* sp_x, real_t* y, const int* sp_y, real_t* w) {
  int ncol_x = sp_x[1];
  const int *colind_x = sp_x+2, *row_x = sp_x + 2 + ncol_x+1;
  int ncol_y = sp_y[1];
  const int *colind_y = sp_y+2, *row_y = sp_y + 2 + ncol_y+1;
  /* Loop over columns of x and y */
  int i, el;
  for (i=0; i<ncol_x; ++i) {
    /* Zero out requested entries in y */
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) w[row_y[el]] = 0;
    /* Set x entries */
    for (el=colind_x[i]; el<colind_x[i+1]; ++el) w[row_x[el]] = x[el];
    /* Retrieve requested entries in y */
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) y[el] = w[row_y[el]];
  }
}
#define project(x, sp_x, y, sp_y, w) CASADI_PREFIX(project)(x, sp_x, y, sp_y, w)


static const int CASADI_PREFIX(s0)[] = {3, 3, 0, 3, 5, 6, 0, 1, 2, 1, 2, 2};
#define s0 CASADI_PREFIX(s0)
static const int CASADI_PREFIX(s1)[] = {3, 3, 0, 1, 3, 6, 0, 0, 1, 0, 1, 2};
#define s1 CASADI_PREFIX(s1)
static const int CASADI_PREFIX(s2)[] = {3, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};
#define s2 CASADI_PREFIX(s2)
static const int CASADI_PREFIX(s3)[] = {3, 1, 0, 3, 0, 1, 2};
#define s3 CASADI_PREFIX(s3)
static const int CASADI_PREFIX(s4)[] = {3, 1, 0, 1, 0};
#define s4 CASADI_PREFIX(s4)
static const int CASADI_PREFIX(s5)[] = {21, 24, 34, 44};
#define s5 CASADI_PREFIX(s5)
static const int CASADI_PREFIX(s6)[] = {3, 1, 0, 1, 1};
#define s6 CASADI_PREFIX(s6)
static const int CASADI_PREFIX(s7)[] = {22, 25, 35, 45};
#define s7 CASADI_PREFIX(s7)
static const int CASADI_PREFIX(s8)[] = {3, 1, 0, 1, 2};
#define s8 CASADI_PREFIX(s8)
static const int CASADI_PREFIX(s9)[] = {23, 26, 36, 46};
#define s9 CASADI_PREFIX(s9)
static const int CASADI_PREFIX(s10)[] = {4, 3, 0, 1, 2, 3, 1, 2, 3};
#define s10 CASADI_PREFIX(s10)
static const int CASADI_PREFIX(s11)[] = {3, 4, 0, 3, 6, 9, 12, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2};
#define s11 CASADI_PREFIX(s11)
static const int CASADI_PREFIX(s12)[] = {3, 4, 0, 0, 1, 2, 3, 0, 1, 2};
#define s12 CASADI_PREFIX(s12)
static const int CASADI_PREFIX(s13)[] = {4, 3, 0, 4, 8, 12, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
#define s13 CASADI_PREFIX(s13)
static const int CASADI_PREFIX(s14)[] = {0, 7, 14, 27, 37, 47};
#define s14 CASADI_PREFIX(s14)
static const int CASADI_PREFIX(s15)[] = {4, 3, 0, 1, 2, 3, 0, 3, 2};
#define s15 CASADI_PREFIX(s15)
static const int CASADI_PREFIX(s16)[] = {3, 4, 0, 1, 1, 2, 3, 0, 2, 1};
#define s16 CASADI_PREFIX(s16)
static const int CASADI_PREFIX(s17)[] = {1, 8, 15, 28, 38, 48};
#define s17 CASADI_PREFIX(s17)
static const int CASADI_PREFIX(s18)[] = {4, 3, 0, 1, 2, 3, 3, 0, 1};
#define s18 CASADI_PREFIX(s18)
static const int CASADI_PREFIX(s19)[] = {3, 4, 0, 1, 2, 2, 3, 1, 2, 0};
#define s19 CASADI_PREFIX(s19)
static const int CASADI_PREFIX(s20)[] = {2, 9, 16, 29, 39, 49};
#define s20 CASADI_PREFIX(s20)
static const int CASADI_PREFIX(s21)[] = {4, 3, 0, 1, 2, 3, 2, 1, 0};
#define s21 CASADI_PREFIX(s21)
static const int CASADI_PREFIX(s22)[] = {3, 4, 0, 1, 2, 3, 3, 2, 1, 0};
#define s22 CASADI_PREFIX(s22)
static const int CASADI_PREFIX(s23)[] = {3, 10, 17, 30, 40, 50};
#define s23 CASADI_PREFIX(s23)
static const int CASADI_PREFIX(s24)[] = {4, 11, 18, 31, 41, 51};
#define s24 CASADI_PREFIX(s24)
static const int CASADI_PREFIX(s25)[] = {5, 12, 19, 32, 42, 52};
#define s25 CASADI_PREFIX(s25)
static const int CASADI_PREFIX(s26)[] = {6, 13, 20, 33, 43, 53};
#define s26 CASADI_PREFIX(s26)
static const int CASADI_PREFIX(s27)[] = {9, 13, 0, 4, 8, 12, 18, 24, 30, 36, 36, 36, 36, 42, 48, 54, 3, 6, 7, 8, 4, 6, 7, 8, 5, 6, 7, 8, 0, 1, 2, 6, 7, 8, 0, 1, 2, 6, 7, 8, 0, 1, 2, 6, 7, 8, 0, 1, 2, 6, 7, 8, 0, 1, 2, 6, 7, 8, 0, 1, 2, 6, 7, 8, 0, 1, 2, 6, 7, 8};
#define s27 CASADI_PREFIX(s27)
static const int CASADI_PREFIX(s28)[] = {13, 9, 0, 7, 14, 21, 22, 23, 24, 34, 44, 54, 3, 4, 5, 6, 10, 11, 12, 3, 4, 5, 6, 10, 11, 12, 3, 4, 5, 6, 10, 11, 12, 0, 1, 2, 0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 0, 1, 2, 3, 4, 5, 6, 10, 11, 12};
#define s28 CASADI_PREFIX(s28)
static const int CASADI_PREFIX(s29)[] = {9, 13, 0, 9, 18, 27, 36, 45, 54, 63, 72, 81, 90, 99, 108, 117, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8};
#define s29 CASADI_PREFIX(s29)
static const int CASADI_PREFIX(s30)[] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
#define s30 CASADI_PREFIX(s30)
static const int CASADI_PREFIX(s31)[] = {3, 8, 0, 3, 3, 3, 3, 3, 3, 3, 3, 0, 1, 2};
#define s31 CASADI_PREFIX(s31)
static const int CASADI_PREFIX(s32)[] = {1, 8, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0};
#define s32 CASADI_PREFIX(s32)
static const int CASADI_PREFIX(s33)[] = {1, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 0, 0, 0, 0, 0, 0, 0};
#define s33 CASADI_PREFIX(s33)
static const int CASADI_PREFIX(s34)[] = {8, 3, 0, 1, 2, 3, 0, 0, 0};
#define s34 CASADI_PREFIX(s34)
static const int CASADI_PREFIX(s35)[] = {3, 8, 0, 3, 6, 9, 12, 15, 18, 21, 24, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2};
#define s35 CASADI_PREFIX(s35)
static const int CASADI_PREFIX(s36)[] = {3, 8, 0, 0, 3, 3, 3, 3, 3, 3, 3, 0, 1, 2};
#define s36 CASADI_PREFIX(s36)
static const int CASADI_PREFIX(s37)[] = {1, 8, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0};
#define s37 CASADI_PREFIX(s37)
static const int CASADI_PREFIX(s38)[] = {8, 3, 0, 1, 2, 3, 1, 1, 1};
#define s38 CASADI_PREFIX(s38)
static const int CASADI_PREFIX(s39)[] = {3, 8, 0, 0, 0, 3, 3, 3, 3, 3, 3, 0, 1, 2};
#define s39 CASADI_PREFIX(s39)
static const int CASADI_PREFIX(s40)[] = {1, 8, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0};
#define s40 CASADI_PREFIX(s40)
static const int CASADI_PREFIX(s41)[] = {8, 3, 0, 1, 2, 3, 2, 2, 2};
#define s41 CASADI_PREFIX(s41)
static const int CASADI_PREFIX(s42)[] = {3, 8, 0, 0, 0, 0, 3, 3, 3, 3, 3, 0, 1, 2};
#define s42 CASADI_PREFIX(s42)
static const int CASADI_PREFIX(s43)[] = {1, 8, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0};
#define s43 CASADI_PREFIX(s43)
static const int CASADI_PREFIX(s44)[] = {8, 3, 0, 1, 2, 3, 3, 3, 3};
#define s44 CASADI_PREFIX(s44)
static const int CASADI_PREFIX(s45)[] = {3, 8, 0, 0, 0, 0, 0, 3, 3, 3, 3, 0, 1, 2};
#define s45 CASADI_PREFIX(s45)
static const int CASADI_PREFIX(s46)[] = {1, 8, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0};
#define s46 CASADI_PREFIX(s46)
static const int CASADI_PREFIX(s47)[] = {8, 3, 0, 1, 2, 3, 4, 4, 4};
#define s47 CASADI_PREFIX(s47)
static const int CASADI_PREFIX(s48)[] = {3, 8, 0, 0, 0, 0, 0, 0, 3, 3, 3, 0, 1, 2};
#define s48 CASADI_PREFIX(s48)
static const int CASADI_PREFIX(s49)[] = {1, 8, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0};
#define s49 CASADI_PREFIX(s49)
static const int CASADI_PREFIX(s50)[] = {8, 3, 0, 1, 2, 3, 5, 5, 5};
#define s50 CASADI_PREFIX(s50)
static const int CASADI_PREFIX(s51)[] = {3, 8, 0, 0, 0, 0, 0, 0, 0, 3, 3, 0, 1, 2};
#define s51 CASADI_PREFIX(s51)
static const int CASADI_PREFIX(s52)[] = {1, 8, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0};
#define s52 CASADI_PREFIX(s52)
static const int CASADI_PREFIX(s53)[] = {8, 3, 0, 1, 2, 3, 6, 6, 6};
#define s53 CASADI_PREFIX(s53)
static const int CASADI_PREFIX(s54)[] = {3, 8, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 1, 2};
#define s54 CASADI_PREFIX(s54)
static const int CASADI_PREFIX(s55)[] = {1, 8, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0};
#define s55 CASADI_PREFIX(s55)
static const int CASADI_PREFIX(s56)[] = {8, 3, 0, 1, 2, 3, 7, 7, 7};
#define s56 CASADI_PREFIX(s56)
static const int CASADI_PREFIX(s57)[] = {9, 8, 0, 6, 12, 18, 24, 30, 36, 42, 48, 0, 1, 2, 6, 7, 8, 0, 1, 2, 6, 7, 8, 0, 1, 2, 6, 7, 8, 0, 1, 2, 6, 7, 8, 0, 1, 2, 6, 7, 8, 0, 1, 2, 6, 7, 8, 0, 1, 2, 6, 7, 8, 0, 1, 2, 6, 7, 8};
#define s57 CASADI_PREFIX(s57)
static const int CASADI_PREFIX(s58)[] = {8, 9, 0, 8, 16, 24, 24, 24, 24, 32, 40, 48, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7};
#define s58 CASADI_PREFIX(s58)
static const int CASADI_PREFIX(s59)[] = {9, 8, 0, 9, 18, 27, 36, 45, 54, 63, 72, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8};
#define s59 CASADI_PREFIX(s59)
static const int CASADI_PREFIX(s60)[] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
#define s60 CASADI_PREFIX(s60)
static const int CASADI_PREFIX(s61)[] = {9, 1, 0, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8};
#define s61 CASADI_PREFIX(s61)
static const real_t CASADI_PREFIX(c0)[] = {-1.3830000000000000e+00, 5.2800000000000002e-01, -7.4700000000000000e-01, -7.9900000000000004e-01, 1.2447999999999999e+00, 7.4570000000000003e-01, 1.4535000000000000e+00, 3.6969999999999997e-01, -7.4819999999999998e-01, 9.5389999999999997e-01, 1.1471000000000000e+00, 7.4500000000000000e-01, 8.1869999999999998e-01, -1.2676000000000001e+00, -7.4650000000000005e-01, 1.4027000000000001e+00, -5.5069999999999997e-01, 7.4639999999999995e-01, -9.3459999999999999e-01, -1.1698000000000000e+00, -7.4580000000000002e-01, -1.4341999999999999e+00, -3.9250000000000002e-01, 7.4750000000000005e-01};
#define c0 CASADI_PREFIX(c0)
static const real_t CASADI_PREFIX(c1)[] = {-5.2469999999999999e+00, 7.8650000000000002e+00, 6.2619999999999996e+00, -5.2460000000000004e+00, 7.8529999999999998e+00, -1.0349999999999999e+00, 5.2630000000000008e+00, 7.5809999999999995e+00, 6.3090000000000002e+00, 5.2670000000000003e+00, 7.5679999999999996e+00, -4.8599999999999999e-01, 5.1399999999999997e+00, -6.4150000000000000e+00, 6.3380000000000001e+00, 5.1480000000000006e+00, -6.4299999999999997e+00, -4.5799999999999996e-01, -5.6379999999999999e+00, -6.5030000000000001e+00, 6.3259999999999996e+00, -5.6360000000000001e+00, -6.5169999999999995e+00, -9.6899999999999986e-01};
#define c1 CASADI_PREFIX(c1)
static const real_t CASADI_PREFIX(c2)[] = {0., 0., -9.8100000000000005e+00};
#define c2 CASADI_PREFIX(c2)
/* cablerobot_output */
int cablerobot_output(const real_t** arg, real_t** res, int* iw, real_t* w, int mem) {
  int i, j, k, *ii, *jj, *kk;
  const int *cii;
  real_t r, s, t, *rr, *ss, *tt;
  const real_t *cr, *cs, *ct;
  const real_t** arg1=arg+3;
  real_t** res1=res+3;
  real_t *w0=w+9, w1, *w2=w+18, *w3=w+31, *w4=w+34, *w5=w+38, w6, w7, w8, w9, *w10=w+45, *w11=w+49, *w12=w+53, *w13=w+57, *w14=w+69, *w15=w+81, *w16=w+93, *w17=w+102, *w18=w+126, *w19=w+150, *w20=w+174, *w21=w+198, *w22=w+201, *w23=w+204, *w24=w+207, *w25=w+210, *w26=w+213, *w27=w+216, *w28=w+219, w29, w30, *w31=w+224, *w32=w+227, *w33=w+230, w34, w35, *w36=w+235, *w37=w+238, *w38=w+241, w39, w40, *w41=w+246, *w42=w+249, *w43=w+252, w44, w45, *w46=w+257, *w47=w+260, *w48=w+263, w49, w50, *w51=w+268, *w52=w+271, *w53=w+274, w54, *w55=w+278, *w56=w+281, *w57=w+287, w58, *w59=w+294, *w60=w+297, *w61=w+306, *w62=w+312, *w63=w+321, *w64=w+330, *w65=w+338, *w66=w+346, *w67=w+354, *w68=w+362, *w69=w+370, *w70=w+378, *w71=w+386, *w72=w+394, *w73=w+402, *w74=w+410, w75, *w76=w+414, *w77=w+423, w78, w79, w80, w81, w82, w83, w84, w85, w86, *w87=w+435, w88, w89, w90, w91, *w93=w+448, *w96=w+502, *w97=w+505, *w98=w+508, *w99=w+511, *w100=w+514, *w101=w+517, *w102=w+520, *w103=w+528, *w104=w+536, *w105=w+544, *w106=w+552, *w107=w+560, *w108=w+614, *w113=w+731, *w114=w+779, *w115=w+827;
  if (arg[1])
    copy(arg[1], 8, w0);
  else 
    fill(w0, 8, 0);
  for (rr=(&w1), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  if (arg[0])
    copy(arg[0], 13, w2);
  else 
    fill(w2, 13, 0);
  copy(w2, 3, w3);
  copy(w2+3, 4, w4);
  copy(w2+10, 3, w5);
  for (rr=(&w6), ss=w4+1; ss!=w4+2; ss+=1) *rr++ = *ss;
  w6 = (- w6 );
  for (rr=(&w7), ss=w4+0; ss!=w4+1; ss+=1) *rr++ = *ss;
  for (rr=(&w8), ss=w4+3; ss!=w4+4; ss+=1) *rr++ = *ss;
  for (rr=(&w9), ss=w4+2; ss!=w4+3; ss+=1) *rr++ = *ss;
  w9 = (- w9 );
  rr=w10;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  for (rr=(&w6), ss=w4+2; ss!=w4+3; ss+=1) *rr++ = *ss;
  w6 = (- w6 );
  for (rr=(&w7), ss=w4+3; ss!=w4+4; ss+=1) *rr++ = *ss;
  w7 = (- w7 );
  for (rr=(&w8), ss=w4+0; ss!=w4+1; ss+=1) *rr++ = *ss;
  for (rr=(&w9), ss=w4+1; ss!=w4+2; ss+=1) *rr++ = *ss;
  rr=w11;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  for (rr=(&w6), ss=w4+3; ss!=w4+4; ss+=1) *rr++ = *ss;
  w6 = (- w6 );
  for (rr=(&w7), ss=w4+2; ss!=w4+3; ss+=1) *rr++ = *ss;
  for (rr=(&w8), ss=w4+1; ss!=w4+2; ss+=1) *rr++ = *ss;
  w8 = (- w8 );
  for (rr=(&w9), ss=w4+0; ss!=w4+1; ss+=1) *rr++ = *ss;
  rr=w12;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  rr=w13;
  for (i=0, cs=w10; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<4; ++i) *rr++ = *cs++;
  for (rr=(&w6), ss=w4+1; ss!=w4+2; ss+=1) *rr++ = *ss;
  w6 = (- w6 );
  for (rr=(&w7), ss=w4+0; ss!=w4+1; ss+=1) *rr++ = *ss;
  for (rr=(&w8), ss=w4+3; ss!=w4+4; ss+=1) *rr++ = *ss;
  w8 = (- w8 );
  for (rr=(&w9), ss=w4+2; ss!=w4+3; ss+=1) *rr++ = *ss;
  rr=w10;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  for (rr=(&w6), ss=w4+2; ss!=w4+3; ss+=1) *rr++ = *ss;
  w6 = (- w6 );
  for (rr=(&w7), ss=w4+3; ss!=w4+4; ss+=1) *rr++ = *ss;
  for (rr=(&w8), ss=w4+0; ss!=w4+1; ss+=1) *rr++ = *ss;
  for (rr=(&w9), ss=w4+1; ss!=w4+2; ss+=1) *rr++ = *ss;
  w9 = (- w9 );
  rr=w11;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  for (rr=(&w6), ss=w4+3; ss!=w4+4; ss+=1) *rr++ = *ss;
  w6 = (- w6 );
  for (rr=(&w7), ss=w4+2; ss!=w4+3; ss+=1) *rr++ = *ss;
  w7 = (- w7 );
  for (rr=(&w8), ss=w4+1; ss!=w4+2; ss+=1) *rr++ = *ss;
  for (rr=(&w9), ss=w4+0; ss!=w4+1; ss+=1) *rr++ = *ss;
  rr=w4;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  rr=w14;
  for (i=0, cs=w10; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w4; i<4; ++i) *rr++ = *cs++;
  for (i=0, rr=w15, cs=w14; i<3; ++i) for (j=0; j<4; ++j) rr[i+j*3] = *cs++;
  fill(w16, 9, 0.);
  for (i=0, rr=w16; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w15+j, tt=w13+i*4; k<4; ++k) *rr += ss[k*3]**tt++;
  fill(w17, 24, 0.);
  copy(c0, 24, w18);
  for (i=0, rr=w17; i<8; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w16+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  for (i=0;i<8;++i) {
    copy(w5, 3, w19+ i*3);
  }
  for (i=0, rr=w19, cr=w17, cs=w19; i<24; ++i) (*rr++)  = ((*cr++)+(*cs++));
  copy(c1, 24, w20);
  for (i=0, rr=w20, cs=w19; i<24; ++i) (*rr++) -= (*cs++);
  for (rr=w5, ss=w20+0; ss!=w20+3; ss+=1) *rr++ = *ss;
  for (i=0, rr=w21, cs=w5; i<3; ++i) (*rr++)  = (w1*(*cs++));
  for (rr=w22, ss=w20+0; ss!=w20+3; ss+=1) *rr++ = *ss;
  w6 = sqrt(dot(3, w22, w22));
  for (i=0, rr=w21; i<3; ++i) (*rr++) /= w6;
  for (rr=(&w7), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  for (rr=w23, ss=w20+3; ss!=w20+6; ss+=1) *rr++ = *ss;
  for (i=0, rr=w24, cs=w23; i<3; ++i) (*rr++)  = (w7*(*cs++));
  for (rr=w25, ss=w20+3; ss!=w20+6; ss+=1) *rr++ = *ss;
  w8 = sqrt(dot(3, w25, w25));
  for (i=0, rr=w24; i<3; ++i) (*rr++) /= w8;
  for (rr=(&w9), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  for (rr=w26, ss=w20+6; ss!=w20+9; ss+=1) *rr++ = *ss;
  for (i=0, rr=w27, cs=w26; i<3; ++i) (*rr++)  = (w9*(*cs++));
  for (rr=w28, ss=w20+6; ss!=w20+9; ss+=1) *rr++ = *ss;
  w29 = sqrt(dot(3, w28, w28));
  for (i=0, rr=w27; i<3; ++i) (*rr++) /= w29;
  for (rr=(&w30), ss=w0+3; ss!=w0+4; ss+=1) *rr++ = *ss;
  for (rr=w31, ss=w20+9; ss!=w20+12; ss+=1) *rr++ = *ss;
  for (i=0, rr=w32, cs=w31; i<3; ++i) (*rr++)  = (w30*(*cs++));
  for (rr=w33, ss=w20+9; ss!=w20+12; ss+=1) *rr++ = *ss;
  w34 = sqrt(dot(3, w33, w33));
  for (i=0, rr=w32; i<3; ++i) (*rr++) /= w34;
  for (rr=(&w35), ss=w0+4; ss!=w0+5; ss+=1) *rr++ = *ss;
  for (rr=w36, ss=w20+12; ss!=w20+15; ss+=1) *rr++ = *ss;
  for (i=0, rr=w37, cs=w36; i<3; ++i) (*rr++)  = (w35*(*cs++));
  for (rr=w38, ss=w20+12; ss!=w20+15; ss+=1) *rr++ = *ss;
  w39 = sqrt(dot(3, w38, w38));
  for (i=0, rr=w37; i<3; ++i) (*rr++) /= w39;
  for (rr=(&w40), ss=w0+5; ss!=w0+6; ss+=1) *rr++ = *ss;
  for (rr=w41, ss=w20+15; ss!=w20+18; ss+=1) *rr++ = *ss;
  for (i=0, rr=w42, cs=w41; i<3; ++i) (*rr++)  = (w40*(*cs++));
  for (rr=w43, ss=w20+15; ss!=w20+18; ss+=1) *rr++ = *ss;
  w44 = sqrt(dot(3, w43, w43));
  for (i=0, rr=w42; i<3; ++i) (*rr++) /= w44;
  for (rr=(&w45), ss=w0+6; ss!=w0+7; ss+=1) *rr++ = *ss;
  for (rr=w46, ss=w20+18; ss!=w20+21; ss+=1) *rr++ = *ss;
  for (i=0, rr=w47, cs=w46; i<3; ++i) (*rr++)  = (w45*(*cs++));
  for (rr=w48, ss=w20+18; ss!=w20+21; ss+=1) *rr++ = *ss;
  w49 = sqrt(dot(3, w48, w48));
  for (i=0, rr=w47; i<3; ++i) (*rr++) /= w49;
  for (rr=(&w50), ss=w0+7; ss!=w0+8; ss+=1) *rr++ = *ss;
  for (rr=w51, ss=w20+21; ss!=w20+24; ss+=1) *rr++ = *ss;
  for (i=0, rr=w52, cs=w51; i<3; ++i) (*rr++)  = (w50*(*cs++));
  for (rr=w53, ss=w20+21; ss!=w20+24; ss+=1) *rr++ = *ss;
  w54 = sqrt(dot(3, w53, w53));
  for (i=0, rr=w52; i<3; ++i) (*rr++) /= w54;
  rr=w20;
  for (i=0, cs=w21; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w24; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w32; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w37; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w42; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w47; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w52; i<3; ++i) *rr++ = *cs++;
  fill(w55, 3, 0.);
  fill(w0, 8, 1.);
  for (i=0, rr=w55; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w20+j, tt=w0+i*8; k<8; ++k) *rr += ss[k*3]**tt++;
  if (arg[2])
    copy(arg[2], 13, w2);
  else 
    fill(w2, 13, 0);
  copy(w2, 6, w56);
  copy(w2+6, 6, w57);
  w58 = w2[12];
  copy(c2, 3, w59);
  for (i=0, rr=w59; i<3; ++i) (*rr++) *= w58;
  for (i=0, rr=w55, cs=w59; i<3; ++i) (*rr++) += (*cs++);
  for (i=0, rr=w55; i<3; ++i) (*rr++) /= w58;
  copy(c2, 3, w59);
  for (i=0, rr=w59, cs=w55; i<3; ++i) (*rr++) -= (*cs++);
  for (i=0, rr=w60, cs=w16; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  fill(w55, 3, 0.);
  for (i=0, rr=w55; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w60+j, tt=w59+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  for (rr=w61, ss=w57+0; ss!=w57+6; ss+=1) *rr++ = *ss;
  trans(w61, s1, w57, s0, iw);
  fill(w62, 9, 0.);
  mtimes(w61, s1, w57, s0, w62, s2, w, 0);
  for (i=0, rr=w63, cs=w16; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  for (rr=w64, ss=w17+1; ss!=w17+25; ss+=3) *rr++ = *ss;
  for (rr=w65, ss=w20+2; ss!=w20+26; ss+=3) *rr++ = *ss;
  for (i=0, rr=w66, cr=w64, cs=w65; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (rr=w67, ss=w17+2; ss!=w17+26; ss+=3) *rr++ = *ss;
  for (rr=w68, ss=w20+1; ss!=w20+25; ss+=3) *rr++ = *ss;
  for (i=0, rr=w69, cr=w67, cs=w68; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w66, cs=w69; i<8; ++i) (*rr++) -= (*cs++);
  for (rr=w69, ss=w20+0; ss!=w20+24; ss+=3) *rr++ = *ss;
  for (i=0, rr=w70, cr=w67, cs=w69; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (rr=w71, ss=w17+0; ss!=w17+24; ss+=3) *rr++ = *ss;
  for (i=0, rr=w72, cr=w71, cs=w65; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w70, cs=w72; i<8; ++i) (*rr++) -= (*cs++);
  for (i=0, rr=w72, cr=w71, cs=w68; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w73, cr=w64, cs=w69; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w72, cs=w73; i<8; ++i) (*rr++) -= (*cs++);
  rr=w17;
  for (i=0, cs=w66; i<8; ++i) *rr++ = *cs++;
  for (i=0, cs=w70; i<8; ++i) *rr++ = *cs++;
  for (i=0, cs=w72; i<8; ++i) *rr++ = *cs++;
  for (i=0, rr=w20, cs=w17; i<3; ++i) for (j=0; j<8; ++j) rr[i+j*3] = *cs++;
  fill(w17, 24, 0.);
  for (i=0, rr=w17; i<8; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w63+j, tt=w20+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  fill(w74, 3, 0.);
  fill(w66, 8, 1.);
  for (i=0, rr=w74; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w66+i*8; k<8; ++k) *rr += ss[k*3]**tt++;
  for (rr=(&w75), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
  for (rr=w61, ss=w56+0; ss!=w56+6; ss+=1) *rr++ = *ss;
  trans(w61, s1, w56, s0, iw);
  fill(w76, 9, 0.);
  mtimes(w56, s0, w61, s1, w76, s2, w, 0);
  fill(w77, 3, 0.);
  for (i=0, rr=w77; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w76+j, tt=w3+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  for (rr=(&w78), ss=w77+2; ss!=w77+3; ss+=1) *rr++ = *ss;
  w79  = (w75*w78);
  for (rr=(&w80), ss=w3+2; ss!=w3+3; ss+=1) *rr++ = *ss;
  for (rr=(&w81), ss=w77+1; ss!=w77+2; ss+=1) *rr++ = *ss;
  w82  = (w80*w81);
  w79 -= w82;
  for (rr=(&w82), ss=w77+0; ss!=w77+1; ss+=1) *rr++ = *ss;
  w83  = (w80*w82);
  for (rr=(&w84), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  w85  = (w84*w78);
  w83 -= w85;
  w85  = (w84*w81);
  w86  = (w75*w82);
  w85 -= w86;
  rr=w77;
  *rr++ = w79;
  *rr++ = w83;
  *rr++ = w85;
  for (i=0, rr=w74, cs=w77; i<3; ++i) (*rr++) -= (*cs++);
  fill(w77, 3, 0.);
  for (i=0, rr=w77; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w62+j, tt=w74+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  for (i=0, rr=w87, cs=w16; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  fill(w74, 3, 0.);
  for (i=0, rr=w74; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w87+j, tt=w77+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  rr=w16;
  for (i=0, cs=w55; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w3; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w74; i<3; ++i) *rr++ = *cs++;
  if (res[0]) copy(w16, 9, res[0]);
  fill(w10, 4, 1.);
  w79 = w10[0];
  fill(w55, 3, 0.);
  mtimes(w76, s2, (&w79), s4, w55, s3, w, 0);
  for (rr=(&w83), ss=w55+2; ss!=w55+3; ss+=1) *rr++ = *ss;
  w85  = (w75*w83);
  for (rr=(&w86), ss=w55+1; ss!=w55+2; ss+=1) *rr++ = *ss;
  w88  = (w80*w86);
  w85 -= w88;
  for (rr=(&w88), ss=w55+0; ss!=w55+1; ss+=1) *rr++ = *ss;
  w89  = (w80*w88);
  for (rr=(&w90), ss=(&w79)+0; ss!=(&w79)+1; ss+=1) *rr++ = *ss;
  w91  = (w78*w90);
  w83  = (w84*w83);
  w91 += w83;
  w89 -= w91;
  w90  = (w81*w90);
  w86  = (w84*w86);
  w90 += w86;
  w88  = (w75*w88);
  w90 -= w88;
  rr=w55;
  *rr++ = w85;
  *rr++ = w89;
  *rr++ = w90;
  for (i=0, rr=w55, cs=w55; i<3; ++i) *rr++ = (- *cs++ );
  fill(w3, 3, 0.);
  for (i=0, rr=w3; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w62+j, tt=w55+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  fill(w55, 3, 0.);
  for (i=0, rr=w55; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w87+j, tt=w3+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  rr=w10;
  *rr++ = w79;
  for (i=0, cs=w55; i<3; ++i) *rr++ = *cs++;
  for (rr=w11, ss=w10+0; ss!=w10+4; ss+=1) *rr++ = *ss;
  fill(w93, 54, 0.);
  for (cii=s5, rr=w93, ss=w11; cii!=s5+4; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  w79 = 1.;
  w85 = w79;
  for (rr=(&w79), ss=(&w85)+0; ss!=(&w85)+1; ss+=1) *rr++ = *ss;
  w78 *= w79;
  fill(w55, 3, 0.);
  mtimes(w76, s2, (&w85), s6, w55, s3, w, 0);
  for (rr=(&w89), ss=w55+2; ss!=w55+3; ss+=1) *rr++ = *ss;
  w90  = (w75*w89);
  w78 += w90;
  for (rr=(&w90), ss=w55+1; ss!=w55+2; ss+=1) *rr++ = *ss;
  w88  = (w80*w90);
  w78 -= w88;
  for (rr=(&w88), ss=w55+0; ss!=w55+1; ss+=1) *rr++ = *ss;
  w86  = (w80*w88);
  w89  = (w84*w89);
  w86 -= w89;
  w90  = (w84*w90);
  w79  = (w82*w79);
  w88  = (w75*w88);
  w79 += w88;
  w90 -= w79;
  rr=w55;
  *rr++ = w78;
  *rr++ = w86;
  *rr++ = w90;
  for (i=0, rr=w55, cs=w55; i<3; ++i) *rr++ = (- *cs++ );
  fill(w3, 3, 0.);
  for (i=0, rr=w3; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w62+j, tt=w55+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  fill(w55, 3, 0.);
  for (i=0, rr=w55; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w87+j, tt=w3+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  rr=w11;
  *rr++ = w85;
  for (i=0, cs=w55; i<3; ++i) *rr++ = *cs++;
  for (rr=w10, ss=w11+0; ss!=w11+4; ss+=1) *rr++ = *ss;
  for (cii=s7, rr=w93, ss=w10; cii!=s7+4; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  w85 = 1.;
  w78 = w85;
  fill(w55, 3, 0.);
  mtimes(w76, s2, (&w78), s8, w55, s3, w, 0);
  for (rr=(&w85), ss=w55+2; ss!=w55+3; ss+=1) *rr++ = *ss;
  w86  = (w75*w85);
  for (rr=(&w90), ss=(&w78)+0; ss!=(&w78)+1; ss+=1) *rr++ = *ss;
  w81 *= w90;
  for (rr=(&w79), ss=w55+1; ss!=w55+2; ss+=1) *rr++ = *ss;
  w88  = (w80*w79);
  w81 += w88;
  w86 -= w81;
  w82 *= w90;
  for (rr=(&w90), ss=w55+0; ss!=w55+1; ss+=1) *rr++ = *ss;
  w80 *= w90;
  w82 += w80;
  w85  = (w84*w85);
  w82 -= w85;
  w84 *= w79;
  w75 *= w90;
  w84 -= w75;
  rr=w55;
  *rr++ = w86;
  *rr++ = w82;
  *rr++ = w84;
  for (i=0, rr=w55, cs=w55; i<3; ++i) *rr++ = (- *cs++ );
  fill(w3, 3, 0.);
  for (i=0, rr=w3; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w62+j, tt=w55+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  fill(w55, 3, 0.);
  for (i=0, rr=w55; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w87+j, tt=w3+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  rr=w10;
  *rr++ = w78;
  for (i=0, cs=w55; i<3; ++i) *rr++ = *cs++;
  for (rr=w11, ss=w10+0; ss!=w10+4; ss+=1) *rr++ = *ss;
  for (cii=s9, rr=w93, ss=w11; cii!=s9+4; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  w78 = 1.;
  w86 = w78;
  for (rr=(&w78), ss=(&w86)+0; ss!=(&w86)+1; ss+=1) *rr++ = *ss;
  rr=(&w82);
  *rr++ = w78;
  for (rr=(&w78), ss=(&w86)+0; ss!=(&w86)+1; ss+=1) *rr++ = *ss;
  rr=(&w84);
  *rr++ = w78;
  for (rr=(&w78), ss=(&w86)+0; ss!=(&w86)+1; ss+=1) *rr++ = *ss;
  rr=(&w75);
  *rr++ = w78;
  rr=w55;
  *rr++ = w82;
  *rr++ = w84;
  *rr++ = w75;
  fill(w76, 9, 0.);
  mtimes(w15, s11, w55, s10, w76, s2, w, 0);
  for (rr=(&w82), ss=(&w86)+0; ss!=(&w86)+1; ss+=1) *rr++ = *ss;
  rr=(&w84);
  *rr++ = w82;
  for (rr=(&w82), ss=(&w86)+0; ss!=(&w86)+1; ss+=1) *rr++ = *ss;
  rr=(&w75);
  *rr++ = w82;
  for (rr=(&w82), ss=(&w86)+0; ss!=(&w86)+1; ss+=1) *rr++ = *ss;
  rr=(&w86);
  *rr++ = w82;
  rr=w55;
  *rr++ = w84;
  *rr++ = w75;
  *rr++ = w86;
  trans(w55, s10, w3, s12, iw);
  fill(w16, 9, 0.);
  mtimes(w3, s12, w13, s13, w16, s2, w, 0);
  for (i=0, rr=w76, cs=w16; i<9; ++i) (*rr++) += (*cs++);
  fill(w17, 24, 0.);
  for (i=0, rr=w17; i<8; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w76+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  for (i=0, rr=w19, cs=w17; i<24; ++i) *rr++ = (- *cs++ );
  for (rr=w3, ss=w19+0; ss!=w19+3; ss+=1) *rr++ = *ss;
  for (i=0, rr=w3, cs=w3; i<3; ++i) (*rr++)  = (w1*(*cs++));
  w84 = (1./ w6 );
  for (i=0, rr=w3, cs=w3; i<3; ++i) (*rr++)  = (w84*(*cs++));
  for (i=0, rr=w21; i<3; ++i) (*rr++) /= w6;
  for (rr=w55, ss=w19+0; ss!=w19+3; ss+=1) *rr++ = *ss;
  w75 = dot(3, w22, w55);
  w75 /= w6;
  for (i=0, rr=w55, cr=w21; i<3; ++i) (*rr++)  = ((*cr++)*w75);
  for (i=0, rr=w3, cs=w55; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=w55, ss=w19+3; ss!=w19+6; ss+=1) *rr++ = *ss;
  for (i=0, rr=w55, cs=w55; i<3; ++i) (*rr++)  = (w7*(*cs++));
  w75 = (1./ w8 );
  for (i=0, rr=w55, cs=w55; i<3; ++i) (*rr++)  = (w75*(*cs++));
  for (i=0, rr=w24; i<3; ++i) (*rr++) /= w8;
  for (rr=w74, ss=w19+3; ss!=w19+6; ss+=1) *rr++ = *ss;
  w86 = dot(3, w25, w74);
  w86 /= w8;
  for (i=0, rr=w74, cr=w24; i<3; ++i) (*rr++)  = ((*cr++)*w86);
  for (i=0, rr=w55, cs=w74; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=w74, ss=w19+6; ss!=w19+9; ss+=1) *rr++ = *ss;
  for (i=0, rr=w74, cs=w74; i<3; ++i) (*rr++)  = (w9*(*cs++));
  w86 = (1./ w29 );
  for (i=0, rr=w74, cs=w74; i<3; ++i) (*rr++)  = (w86*(*cs++));
  for (i=0, rr=w27; i<3; ++i) (*rr++) /= w29;
  for (rr=w96, ss=w19+6; ss!=w19+9; ss+=1) *rr++ = *ss;
  w82 = dot(3, w28, w96);
  w82 /= w29;
  for (i=0, rr=w96, cr=w27; i<3; ++i) (*rr++)  = ((*cr++)*w82);
  for (i=0, rr=w74, cs=w96; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=w96, ss=w19+9; ss!=w19+12; ss+=1) *rr++ = *ss;
  for (i=0, rr=w96, cs=w96; i<3; ++i) (*rr++)  = (w30*(*cs++));
  w82 = (1./ w34 );
  for (i=0, rr=w96, cs=w96; i<3; ++i) (*rr++)  = (w82*(*cs++));
  for (i=0, rr=w32; i<3; ++i) (*rr++) /= w34;
  for (rr=w97, ss=w19+9; ss!=w19+12; ss+=1) *rr++ = *ss;
  w78 = dot(3, w33, w97);
  w78 /= w34;
  for (i=0, rr=w97, cr=w32; i<3; ++i) (*rr++)  = ((*cr++)*w78);
  for (i=0, rr=w96, cs=w97; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=w97, ss=w19+12; ss!=w19+15; ss+=1) *rr++ = *ss;
  for (i=0, rr=w97, cs=w97; i<3; ++i) (*rr++)  = (w35*(*cs++));
  w78 = (1./ w39 );
  for (i=0, rr=w97, cs=w97; i<3; ++i) (*rr++)  = (w78*(*cs++));
  for (i=0, rr=w37; i<3; ++i) (*rr++) /= w39;
  for (rr=w98, ss=w19+12; ss!=w19+15; ss+=1) *rr++ = *ss;
  w90 = dot(3, w38, w98);
  w90 /= w39;
  for (i=0, rr=w98, cr=w37; i<3; ++i) (*rr++)  = ((*cr++)*w90);
  for (i=0, rr=w97, cs=w98; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=w98, ss=w19+15; ss!=w19+18; ss+=1) *rr++ = *ss;
  for (i=0, rr=w98, cs=w98; i<3; ++i) (*rr++)  = (w40*(*cs++));
  w90 = (1./ w44 );
  for (i=0, rr=w98, cs=w98; i<3; ++i) (*rr++)  = (w90*(*cs++));
  for (i=0, rr=w42; i<3; ++i) (*rr++) /= w44;
  for (rr=w99, ss=w19+15; ss!=w19+18; ss+=1) *rr++ = *ss;
  w79 = dot(3, w43, w99);
  w79 /= w44;
  for (i=0, rr=w99, cr=w42; i<3; ++i) (*rr++)  = ((*cr++)*w79);
  for (i=0, rr=w98, cs=w99; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=w99, ss=w19+18; ss!=w19+21; ss+=1) *rr++ = *ss;
  for (i=0, rr=w99, cs=w99; i<3; ++i) (*rr++)  = (w45*(*cs++));
  w79 = (1./ w49 );
  for (i=0, rr=w99, cs=w99; i<3; ++i) (*rr++)  = (w79*(*cs++));
  for (i=0, rr=w47; i<3; ++i) (*rr++) /= w49;
  for (rr=w100, ss=w19+18; ss!=w19+21; ss+=1) *rr++ = *ss;
  w85 = dot(3, w48, w100);
  w85 /= w49;
  for (i=0, rr=w100, cr=w47; i<3; ++i) (*rr++)  = ((*cr++)*w85);
  for (i=0, rr=w99, cs=w100; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=w100, ss=w19+21; ss!=w19+24; ss+=1) *rr++ = *ss;
  for (i=0, rr=w100, cs=w100; i<3; ++i) (*rr++)  = (w50*(*cs++));
  w85 = (1./ w54 );
  for (i=0, rr=w100, cs=w100; i<3; ++i) (*rr++)  = (w85*(*cs++));
  for (i=0, rr=w52; i<3; ++i) (*rr++) /= w54;
  for (rr=w101, ss=w19+21; ss!=w19+24; ss+=1) *rr++ = *ss;
  w80 = dot(3, w53, w101);
  w80 /= w54;
  for (i=0, rr=w101, cr=w52; i<3; ++i) (*rr++)  = ((*cr++)*w80);
  for (i=0, rr=w100, cs=w101; i<3; ++i) (*rr++) -= (*cs++);
  rr=w19;
  for (i=0, cs=w3; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w55; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w74; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w96; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w97; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w98; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w99; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w100; i<3; ++i) *rr++ = *cs++;
  fill(w3, 3, 0.);
  for (i=0, rr=w3; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w19+j, tt=w0+i*8; k<8; ++k) *rr += ss[k*3]**tt++;
  w80 = (1./ w58 );
  for (i=0, rr=w3, cs=w3; i<3; ++i) (*rr++)  = (w80*(*cs++));
  for (i=0, rr=w3, cs=w3; i<3; ++i) *rr++ = (- *cs++ );
  fill(w55, 3, 0.);
  for (i=0, rr=w55; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w60+j, tt=w3+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  for (i=0, rr=w16, cs=w76; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  fill(w3, 3, 0.);
  for (i=0, rr=w3; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w16+j, tt=w59+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  for (i=0, rr=w55, cs=w3; i<3; ++i) (*rr++) += (*cs++);
  for (rr=w70, ss=w17+1; ss!=w17+25; ss+=3) *rr++ = *ss;
  for (i=0, rr=w72, cr=w65, cs=w70; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (rr=w73, ss=w19+2; ss!=w19+26; ss+=3) *rr++ = *ss;
  for (i=0, rr=w102, cr=w64, cs=w73; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w72, cs=w102; i<8; ++i) (*rr++) += (*cs++);
  for (rr=w102, ss=w17+2; ss!=w17+26; ss+=3) *rr++ = *ss;
  for (i=0, rr=w103, cr=w68, cs=w102; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (rr=w104, ss=w19+1; ss!=w19+25; ss+=3) *rr++ = *ss;
  for (i=0, rr=w105, cr=w67, cs=w104; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w103, cs=w105; i<8; ++i) (*rr++) += (*cs++);
  for (i=0, rr=w72, cs=w103; i<8; ++i) (*rr++) -= (*cs++);
  for (i=0, rr=w102, cr=w69, cs=w102; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (rr=w103, ss=w19+0; ss!=w19+24; ss+=3) *rr++ = *ss;
  for (i=0, rr=w105, cr=w67, cs=w103; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w102, cs=w105; i<8; ++i) (*rr++) += (*cs++);
  for (rr=w105, ss=w17+0; ss!=w17+24; ss+=3) *rr++ = *ss;
  for (i=0, rr=w106, cr=w65, cs=w105; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w73, cr=w71, cs=w73; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w106, cs=w73; i<8; ++i) (*rr++) += (*cs++);
  for (i=0, rr=w102, cs=w106; i<8; ++i) (*rr++) -= (*cs++);
  for (i=0, rr=w105, cr=w68, cs=w105; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w104, cr=w71, cs=w104; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w105, cs=w104; i<8; ++i) (*rr++) += (*cs++);
  for (i=0, rr=w70, cr=w69, cs=w70; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w103, cr=w64, cs=w103; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w70, cs=w103; i<8; ++i) (*rr++) += (*cs++);
  for (i=0, rr=w105, cs=w70; i<8; ++i) (*rr++) -= (*cs++);
  rr=w17;
  for (i=0, cs=w72; i<8; ++i) *rr++ = *cs++;
  for (i=0, cs=w102; i<8; ++i) *rr++ = *cs++;
  for (i=0, cs=w105; i<8; ++i) *rr++ = *cs++;
  for (i=0, rr=w19, cs=w17; i<3; ++i) for (j=0; j<8; ++j) rr[i+j*3] = *cs++;
  fill(w17, 24, 0.);
  for (i=0, rr=w17; i<8; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w63+j, tt=w19+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  for (i=0, rr=w16, cs=w76; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  fill(w19, 24, 0.);
  for (i=0, rr=w19; i<8; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w16+j, tt=w20+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  for (i=0, rr=w17, cs=w19; i<24; ++i) (*rr++) += (*cs++);
  fill(w3, 3, 0.);
  for (i=0, rr=w3; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w66+i*8; k<8; ++k) *rr += ss[k*3]**tt++;
  fill(w74, 3, 0.);
  for (i=0, rr=w74; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w62+j, tt=w3+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  fill(w3, 3, 0.);
  for (i=0, rr=w3; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w87+j, tt=w74+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  for (i=0, rr=w16, cs=w76; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  fill(w74, 3, 0.);
  for (i=0, rr=w74; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w16+j, tt=w77+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  for (i=0, rr=w3, cs=w74; i<3; ++i) (*rr++) += (*cs++);
  rr=w56;
  for (i=0, cs=w55; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w3; i<3; ++i) *rr++ = *cs++;
  for (rr=w61, ss=w56+0; ss!=w56+6; ss+=1) *rr++ = *ss;
  for (cii=s14, rr=w93, ss=w61; cii!=s14+6; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  w81 = 1.;
  w88 = w81;
  for (rr=(&w81), ss=(&w88)+0; ss!=(&w88)+1; ss+=1) *rr++ = *ss;
  w81 = (- w81 );
  rr=(&w89);
  *rr++ = w81;
  for (rr=(&w81), ss=(&w88)+0; ss!=(&w88)+1; ss+=1) *rr++ = *ss;
  rr=(&w91);
  *rr++ = w81;
  for (rr=(&w81), ss=(&w88)+0; ss!=(&w88)+1; ss+=1) *rr++ = *ss;
  w81 = (- w81 );
  rr=(&w83);
  *rr++ = w81;
  rr=w55;
  *rr++ = w89;
  *rr++ = w91;
  *rr++ = w83;
  fill(w16, 9, 0.);
  mtimes(w15, s11, w55, s15, w16, s2, w, 0);
  for (rr=(&w89), ss=(&w88)+0; ss!=(&w88)+1; ss+=1) *rr++ = *ss;
  w89 = (- w89 );
  rr=(&w91);
  *rr++ = w89;
  for (rr=(&w89), ss=(&w88)+0; ss!=(&w88)+1; ss+=1) *rr++ = *ss;
  w89 = (- w89 );
  rr=(&w83);
  *rr++ = w89;
  for (rr=(&w89), ss=(&w88)+0; ss!=(&w88)+1; ss+=1) *rr++ = *ss;
  rr=(&w88);
  *rr++ = w89;
  rr=w55;
  *rr++ = w91;
  *rr++ = w83;
  *rr++ = w88;
  trans(w55, s15, w3, s16, iw);
  fill(w76, 9, 0.);
  mtimes(w3, s16, w13, s13, w76, s2, w, 0);
  for (i=0, rr=w16, cs=w76; i<9; ++i) (*rr++) += (*cs++);
  fill(w17, 24, 0.);
  for (i=0, rr=w17; i<8; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w16+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  for (i=0, rr=w19, cs=w17; i<24; ++i) *rr++ = (- *cs++ );
  for (rr=w3, ss=w19+0; ss!=w19+3; ss+=1) *rr++ = *ss;
  for (i=0, rr=w3, cs=w3; i<3; ++i) (*rr++)  = (w1*(*cs++));
  for (i=0, rr=w3, cs=w3; i<3; ++i) (*rr++)  = (w84*(*cs++));
  for (rr=w55, ss=w19+0; ss!=w19+3; ss+=1) *rr++ = *ss;
  w91 = dot(3, w22, w55);
  w91 /= w6;
  for (i=0, rr=w55, cr=w21; i<3; ++i) (*rr++)  = ((*cr++)*w91);
  for (i=0, rr=w3, cs=w55; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=w55, ss=w19+3; ss!=w19+6; ss+=1) *rr++ = *ss;
  for (i=0, rr=w55, cs=w55; i<3; ++i) (*rr++)  = (w7*(*cs++));
  for (i=0, rr=w55, cs=w55; i<3; ++i) (*rr++)  = (w75*(*cs++));
  for (rr=w74, ss=w19+3; ss!=w19+6; ss+=1) *rr++ = *ss;
  w91 = dot(3, w25, w74);
  w91 /= w8;
  for (i=0, rr=w74, cr=w24; i<3; ++i) (*rr++)  = ((*cr++)*w91);
  for (i=0, rr=w55, cs=w74; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=w74, ss=w19+6; ss!=w19+9; ss+=1) *rr++ = *ss;
  for (i=0, rr=w74, cs=w74; i<3; ++i) (*rr++)  = (w9*(*cs++));
  for (i=0, rr=w74, cs=w74; i<3; ++i) (*rr++)  = (w86*(*cs++));
  for (rr=w96, ss=w19+6; ss!=w19+9; ss+=1) *rr++ = *ss;
  w91 = dot(3, w28, w96);
  w91 /= w29;
  for (i=0, rr=w96, cr=w27; i<3; ++i) (*rr++)  = ((*cr++)*w91);
  for (i=0, rr=w74, cs=w96; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=w96, ss=w19+9; ss!=w19+12; ss+=1) *rr++ = *ss;
  for (i=0, rr=w96, cs=w96; i<3; ++i) (*rr++)  = (w30*(*cs++));
  for (i=0, rr=w96, cs=w96; i<3; ++i) (*rr++)  = (w82*(*cs++));
  for (rr=w97, ss=w19+9; ss!=w19+12; ss+=1) *rr++ = *ss;
  w91 = dot(3, w33, w97);
  w91 /= w34;
  for (i=0, rr=w97, cr=w32; i<3; ++i) (*rr++)  = ((*cr++)*w91);
  for (i=0, rr=w96, cs=w97; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=w97, ss=w19+12; ss!=w19+15; ss+=1) *rr++ = *ss;
  for (i=0, rr=w97, cs=w97; i<3; ++i) (*rr++)  = (w35*(*cs++));
  for (i=0, rr=w97, cs=w97; i<3; ++i) (*rr++)  = (w78*(*cs++));
  for (rr=w98, ss=w19+12; ss!=w19+15; ss+=1) *rr++ = *ss;
  w91 = dot(3, w38, w98);
  w91 /= w39;
  for (i=0, rr=w98, cr=w37; i<3; ++i) (*rr++)  = ((*cr++)*w91);
  for (i=0, rr=w97, cs=w98; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=w98, ss=w19+15; ss!=w19+18; ss+=1) *rr++ = *ss;
  for (i=0, rr=w98, cs=w98; i<3; ++i) (*rr++)  = (w40*(*cs++));
  for (i=0, rr=w98, cs=w98; i<3; ++i) (*rr++)  = (w90*(*cs++));
  for (rr=w99, ss=w19+15; ss!=w19+18; ss+=1) *rr++ = *ss;
  w91 = dot(3, w43, w99);
  w91 /= w44;
  for (i=0, rr=w99, cr=w42; i<3; ++i) (*rr++)  = ((*cr++)*w91);
  for (i=0, rr=w98, cs=w99; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=w99, ss=w19+18; ss!=w19+21; ss+=1) *rr++ = *ss;
  for (i=0, rr=w99, cs=w99; i<3; ++i) (*rr++)  = (w45*(*cs++));
  for (i=0, rr=w99, cs=w99; i<3; ++i) (*rr++)  = (w79*(*cs++));
  for (rr=w100, ss=w19+18; ss!=w19+21; ss+=1) *rr++ = *ss;
  w91 = dot(3, w48, w100);
  w91 /= w49;
  for (i=0, rr=w100, cr=w47; i<3; ++i) (*rr++)  = ((*cr++)*w91);
  for (i=0, rr=w99, cs=w100; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=w100, ss=w19+21; ss!=w19+24; ss+=1) *rr++ = *ss;
  for (i=0, rr=w100, cs=w100; i<3; ++i) (*rr++)  = (w50*(*cs++));
  for (i=0, rr=w100, cs=w100; i<3; ++i) (*rr++)  = (w85*(*cs++));
  for (rr=w101, ss=w19+21; ss!=w19+24; ss+=1) *rr++ = *ss;
  w91 = dot(3, w53, w101);
  w91 /= w54;
  for (i=0, rr=w101, cr=w52; i<3; ++i) (*rr++)  = ((*cr++)*w91);
  for (i=0, rr=w100, cs=w101; i<3; ++i) (*rr++) -= (*cs++);
  rr=w19;
  for (i=0, cs=w3; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w55; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w74; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w96; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w97; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w98; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w99; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w100; i<3; ++i) *rr++ = *cs++;
  fill(w3, 3, 0.);
  for (i=0, rr=w3; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w19+j, tt=w0+i*8; k<8; ++k) *rr += ss[k*3]**tt++;
  for (i=0, rr=w3, cs=w3; i<3; ++i) (*rr++)  = (w80*(*cs++));
  for (i=0, rr=w3, cs=w3; i<3; ++i) *rr++ = (- *cs++ );
  fill(w55, 3, 0.);
  for (i=0, rr=w55; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w60+j, tt=w3+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  for (i=0, rr=w76, cs=w16; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  fill(w3, 3, 0.);
  for (i=0, rr=w3; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w76+j, tt=w59+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  for (i=0, rr=w55, cs=w3; i<3; ++i) (*rr++) += (*cs++);
  for (rr=w72, ss=w17+1; ss!=w17+25; ss+=3) *rr++ = *ss;
  for (i=0, rr=w102, cr=w65, cs=w72; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (rr=w105, ss=w19+2; ss!=w19+26; ss+=3) *rr++ = *ss;
  for (i=0, rr=w70, cr=w64, cs=w105; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w102, cs=w70; i<8; ++i) (*rr++) += (*cs++);
  for (rr=w70, ss=w17+2; ss!=w17+26; ss+=3) *rr++ = *ss;
  for (i=0, rr=w103, cr=w68, cs=w70; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (rr=w104, ss=w19+1; ss!=w19+25; ss+=3) *rr++ = *ss;
  for (i=0, rr=w106, cr=w67, cs=w104; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w103, cs=w106; i<8; ++i) (*rr++) += (*cs++);
  for (i=0, rr=w102, cs=w103; i<8; ++i) (*rr++) -= (*cs++);
  for (i=0, rr=w70, cr=w69, cs=w70; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (rr=w103, ss=w19+0; ss!=w19+24; ss+=3) *rr++ = *ss;
  for (i=0, rr=w106, cr=w67, cs=w103; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w70, cs=w106; i<8; ++i) (*rr++) += (*cs++);
  for (rr=w106, ss=w17+0; ss!=w17+24; ss+=3) *rr++ = *ss;
  for (i=0, rr=w73, cr=w65, cs=w106; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w105, cr=w71, cs=w105; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w73, cs=w105; i<8; ++i) (*rr++) += (*cs++);
  for (i=0, rr=w70, cs=w73; i<8; ++i) (*rr++) -= (*cs++);
  for (i=0, rr=w106, cr=w68, cs=w106; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w104, cr=w71, cs=w104; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w106, cs=w104; i<8; ++i) (*rr++) += (*cs++);
  for (i=0, rr=w72, cr=w69, cs=w72; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w103, cr=w64, cs=w103; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w72, cs=w103; i<8; ++i) (*rr++) += (*cs++);
  for (i=0, rr=w106, cs=w72; i<8; ++i) (*rr++) -= (*cs++);
  rr=w17;
  for (i=0, cs=w102; i<8; ++i) *rr++ = *cs++;
  for (i=0, cs=w70; i<8; ++i) *rr++ = *cs++;
  for (i=0, cs=w106; i<8; ++i) *rr++ = *cs++;
  for (i=0, rr=w19, cs=w17; i<3; ++i) for (j=0; j<8; ++j) rr[i+j*3] = *cs++;
  fill(w17, 24, 0.);
  for (i=0, rr=w17; i<8; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w63+j, tt=w19+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  for (i=0, rr=w76, cs=w16; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  fill(w19, 24, 0.);
  for (i=0, rr=w19; i<8; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w76+j, tt=w20+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  for (i=0, rr=w17, cs=w19; i<24; ++i) (*rr++) += (*cs++);
  fill(w3, 3, 0.);
  for (i=0, rr=w3; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w66+i*8; k<8; ++k) *rr += ss[k*3]**tt++;
  fill(w74, 3, 0.);
  for (i=0, rr=w74; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w62+j, tt=w3+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  fill(w3, 3, 0.);
  for (i=0, rr=w3; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w87+j, tt=w74+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  for (i=0, rr=w76, cs=w16; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  fill(w74, 3, 0.);
  for (i=0, rr=w74; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w76+j, tt=w77+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  for (i=0, rr=w3, cs=w74; i<3; ++i) (*rr++) += (*cs++);
  rr=w61;
  for (i=0, cs=w55; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w3; i<3; ++i) *rr++ = *cs++;
  for (rr=w56, ss=w61+0; ss!=w61+6; ss+=1) *rr++ = *ss;
  for (cii=s17, rr=w93, ss=w56; cii!=s17+6; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  w91 = 1.;
  w83 = w91;
  for (rr=(&w91), ss=(&w83)+0; ss!=(&w83)+1; ss+=1) *rr++ = *ss;
  w91 = (- w91 );
  rr=(&w88);
  *rr++ = w91;
  for (rr=(&w91), ss=(&w83)+0; ss!=(&w83)+1; ss+=1) *rr++ = *ss;
  w91 = (- w91 );
  rr=(&w89);
  *rr++ = w91;
  for (rr=(&w91), ss=(&w83)+0; ss!=(&w83)+1; ss+=1) *rr++ = *ss;
  rr=(&w81);
  *rr++ = w91;
  rr=w55;
  *rr++ = w88;
  *rr++ = w89;
  *rr++ = w81;
  fill(w76, 9, 0.);
  mtimes(w15, s11, w55, s18, w76, s2, w, 0);
  for (rr=(&w88), ss=(&w83)+0; ss!=(&w83)+1; ss+=1) *rr++ = *ss;
  rr=(&w89);
  *rr++ = w88;
  for (rr=(&w88), ss=(&w83)+0; ss!=(&w83)+1; ss+=1) *rr++ = *ss;
  w88 = (- w88 );
  rr=(&w81);
  *rr++ = w88;
  for (rr=(&w88), ss=(&w83)+0; ss!=(&w83)+1; ss+=1) *rr++ = *ss;
  w88 = (- w88 );
  rr=(&w83);
  *rr++ = w88;
  rr=w55;
  *rr++ = w89;
  *rr++ = w81;
  *rr++ = w83;
  trans(w55, s18, w3, s19, iw);
  fill(w16, 9, 0.);
  mtimes(w3, s19, w13, s13, w16, s2, w, 0);
  for (i=0, rr=w76, cs=w16; i<9; ++i) (*rr++) += (*cs++);
  fill(w17, 24, 0.);
  for (i=0, rr=w17; i<8; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w76+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  for (i=0, rr=w19, cs=w17; i<24; ++i) *rr++ = (- *cs++ );
  for (rr=w3, ss=w19+0; ss!=w19+3; ss+=1) *rr++ = *ss;
  for (i=0, rr=w3, cs=w3; i<3; ++i) (*rr++)  = (w1*(*cs++));
  for (i=0, rr=w3, cs=w3; i<3; ++i) (*rr++)  = (w84*(*cs++));
  for (rr=w55, ss=w19+0; ss!=w19+3; ss+=1) *rr++ = *ss;
  w89 = dot(3, w22, w55);
  w89 /= w6;
  for (i=0, rr=w55, cr=w21; i<3; ++i) (*rr++)  = ((*cr++)*w89);
  for (i=0, rr=w3, cs=w55; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=w55, ss=w19+3; ss!=w19+6; ss+=1) *rr++ = *ss;
  for (i=0, rr=w55, cs=w55; i<3; ++i) (*rr++)  = (w7*(*cs++));
  for (i=0, rr=w55, cs=w55; i<3; ++i) (*rr++)  = (w75*(*cs++));
  for (rr=w74, ss=w19+3; ss!=w19+6; ss+=1) *rr++ = *ss;
  w89 = dot(3, w25, w74);
  w89 /= w8;
  for (i=0, rr=w74, cr=w24; i<3; ++i) (*rr++)  = ((*cr++)*w89);
  for (i=0, rr=w55, cs=w74; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=w74, ss=w19+6; ss!=w19+9; ss+=1) *rr++ = *ss;
  for (i=0, rr=w74, cs=w74; i<3; ++i) (*rr++)  = (w9*(*cs++));
  for (i=0, rr=w74, cs=w74; i<3; ++i) (*rr++)  = (w86*(*cs++));
  for (rr=w96, ss=w19+6; ss!=w19+9; ss+=1) *rr++ = *ss;
  w89 = dot(3, w28, w96);
  w89 /= w29;
  for (i=0, rr=w96, cr=w27; i<3; ++i) (*rr++)  = ((*cr++)*w89);
  for (i=0, rr=w74, cs=w96; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=w96, ss=w19+9; ss!=w19+12; ss+=1) *rr++ = *ss;
  for (i=0, rr=w96, cs=w96; i<3; ++i) (*rr++)  = (w30*(*cs++));
  for (i=0, rr=w96, cs=w96; i<3; ++i) (*rr++)  = (w82*(*cs++));
  for (rr=w97, ss=w19+9; ss!=w19+12; ss+=1) *rr++ = *ss;
  w89 = dot(3, w33, w97);
  w89 /= w34;
  for (i=0, rr=w97, cr=w32; i<3; ++i) (*rr++)  = ((*cr++)*w89);
  for (i=0, rr=w96, cs=w97; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=w97, ss=w19+12; ss!=w19+15; ss+=1) *rr++ = *ss;
  for (i=0, rr=w97, cs=w97; i<3; ++i) (*rr++)  = (w35*(*cs++));
  for (i=0, rr=w97, cs=w97; i<3; ++i) (*rr++)  = (w78*(*cs++));
  for (rr=w98, ss=w19+12; ss!=w19+15; ss+=1) *rr++ = *ss;
  w89 = dot(3, w38, w98);
  w89 /= w39;
  for (i=0, rr=w98, cr=w37; i<3; ++i) (*rr++)  = ((*cr++)*w89);
  for (i=0, rr=w97, cs=w98; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=w98, ss=w19+15; ss!=w19+18; ss+=1) *rr++ = *ss;
  for (i=0, rr=w98, cs=w98; i<3; ++i) (*rr++)  = (w40*(*cs++));
  for (i=0, rr=w98, cs=w98; i<3; ++i) (*rr++)  = (w90*(*cs++));
  for (rr=w99, ss=w19+15; ss!=w19+18; ss+=1) *rr++ = *ss;
  w89 = dot(3, w43, w99);
  w89 /= w44;
  for (i=0, rr=w99, cr=w42; i<3; ++i) (*rr++)  = ((*cr++)*w89);
  for (i=0, rr=w98, cs=w99; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=w99, ss=w19+18; ss!=w19+21; ss+=1) *rr++ = *ss;
  for (i=0, rr=w99, cs=w99; i<3; ++i) (*rr++)  = (w45*(*cs++));
  for (i=0, rr=w99, cs=w99; i<3; ++i) (*rr++)  = (w79*(*cs++));
  for (rr=w100, ss=w19+18; ss!=w19+21; ss+=1) *rr++ = *ss;
  w89 = dot(3, w48, w100);
  w89 /= w49;
  for (i=0, rr=w100, cr=w47; i<3; ++i) (*rr++)  = ((*cr++)*w89);
  for (i=0, rr=w99, cs=w100; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=w100, ss=w19+21; ss!=w19+24; ss+=1) *rr++ = *ss;
  for (i=0, rr=w100, cs=w100; i<3; ++i) (*rr++)  = (w50*(*cs++));
  for (i=0, rr=w100, cs=w100; i<3; ++i) (*rr++)  = (w85*(*cs++));
  for (rr=w101, ss=w19+21; ss!=w19+24; ss+=1) *rr++ = *ss;
  w89 = dot(3, w53, w101);
  w89 /= w54;
  for (i=0, rr=w101, cr=w52; i<3; ++i) (*rr++)  = ((*cr++)*w89);
  for (i=0, rr=w100, cs=w101; i<3; ++i) (*rr++) -= (*cs++);
  rr=w19;
  for (i=0, cs=w3; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w55; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w74; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w96; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w97; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w98; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w99; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w100; i<3; ++i) *rr++ = *cs++;
  fill(w3, 3, 0.);
  for (i=0, rr=w3; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w19+j, tt=w0+i*8; k<8; ++k) *rr += ss[k*3]**tt++;
  for (i=0, rr=w3, cs=w3; i<3; ++i) (*rr++)  = (w80*(*cs++));
  for (i=0, rr=w3, cs=w3; i<3; ++i) *rr++ = (- *cs++ );
  fill(w55, 3, 0.);
  for (i=0, rr=w55; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w60+j, tt=w3+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  for (i=0, rr=w16, cs=w76; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  fill(w3, 3, 0.);
  for (i=0, rr=w3; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w16+j, tt=w59+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  for (i=0, rr=w55, cs=w3; i<3; ++i) (*rr++) += (*cs++);
  for (rr=w102, ss=w17+1; ss!=w17+25; ss+=3) *rr++ = *ss;
  for (i=0, rr=w70, cr=w65, cs=w102; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (rr=w106, ss=w19+2; ss!=w19+26; ss+=3) *rr++ = *ss;
  for (i=0, rr=w72, cr=w64, cs=w106; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w70, cs=w72; i<8; ++i) (*rr++) += (*cs++);
  for (rr=w72, ss=w17+2; ss!=w17+26; ss+=3) *rr++ = *ss;
  for (i=0, rr=w103, cr=w68, cs=w72; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (rr=w104, ss=w19+1; ss!=w19+25; ss+=3) *rr++ = *ss;
  for (i=0, rr=w73, cr=w67, cs=w104; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w103, cs=w73; i<8; ++i) (*rr++) += (*cs++);
  for (i=0, rr=w70, cs=w103; i<8; ++i) (*rr++) -= (*cs++);
  for (i=0, rr=w72, cr=w69, cs=w72; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (rr=w103, ss=w19+0; ss!=w19+24; ss+=3) *rr++ = *ss;
  for (i=0, rr=w73, cr=w67, cs=w103; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w72, cs=w73; i<8; ++i) (*rr++) += (*cs++);
  for (rr=w73, ss=w17+0; ss!=w17+24; ss+=3) *rr++ = *ss;
  for (i=0, rr=w105, cr=w65, cs=w73; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w106, cr=w71, cs=w106; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w105, cs=w106; i<8; ++i) (*rr++) += (*cs++);
  for (i=0, rr=w72, cs=w105; i<8; ++i) (*rr++) -= (*cs++);
  for (i=0, rr=w73, cr=w68, cs=w73; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w104, cr=w71, cs=w104; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w73, cs=w104; i<8; ++i) (*rr++) += (*cs++);
  for (i=0, rr=w102, cr=w69, cs=w102; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w103, cr=w64, cs=w103; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w102, cs=w103; i<8; ++i) (*rr++) += (*cs++);
  for (i=0, rr=w73, cs=w102; i<8; ++i) (*rr++) -= (*cs++);
  rr=w17;
  for (i=0, cs=w70; i<8; ++i) *rr++ = *cs++;
  for (i=0, cs=w72; i<8; ++i) *rr++ = *cs++;
  for (i=0, cs=w73; i<8; ++i) *rr++ = *cs++;
  for (i=0, rr=w19, cs=w17; i<3; ++i) for (j=0; j<8; ++j) rr[i+j*3] = *cs++;
  fill(w17, 24, 0.);
  for (i=0, rr=w17; i<8; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w63+j, tt=w19+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  for (i=0, rr=w16, cs=w76; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  fill(w19, 24, 0.);
  for (i=0, rr=w19; i<8; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w16+j, tt=w20+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  for (i=0, rr=w17, cs=w19; i<24; ++i) (*rr++) += (*cs++);
  fill(w3, 3, 0.);
  for (i=0, rr=w3; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w66+i*8; k<8; ++k) *rr += ss[k*3]**tt++;
  fill(w74, 3, 0.);
  for (i=0, rr=w74; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w62+j, tt=w3+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  fill(w3, 3, 0.);
  for (i=0, rr=w3; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w87+j, tt=w74+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  for (i=0, rr=w16, cs=w76; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  fill(w74, 3, 0.);
  for (i=0, rr=w74; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w16+j, tt=w77+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  for (i=0, rr=w3, cs=w74; i<3; ++i) (*rr++) += (*cs++);
  rr=w56;
  for (i=0, cs=w55; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w3; i<3; ++i) *rr++ = *cs++;
  for (rr=w61, ss=w56+0; ss!=w56+6; ss+=1) *rr++ = *ss;
  for (cii=s20, rr=w93, ss=w61; cii!=s20+6; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  w89 = 1.;
  w81 = w89;
  for (rr=(&w89), ss=(&w81)+0; ss!=(&w81)+1; ss+=1) *rr++ = *ss;
  rr=(&w83);
  *rr++ = w89;
  for (rr=(&w89), ss=(&w81)+0; ss!=(&w81)+1; ss+=1) *rr++ = *ss;
  w89 = (- w89 );
  rr=(&w88);
  *rr++ = w89;
  for (rr=(&w89), ss=(&w81)+0; ss!=(&w81)+1; ss+=1) *rr++ = *ss;
  w89 = (- w89 );
  rr=(&w91);
  *rr++ = w89;
  rr=w55;
  *rr++ = w83;
  *rr++ = w88;
  *rr++ = w91;
  fill(w16, 9, 0.);
  mtimes(w15, s11, w55, s21, w16, s2, w, 0);
  for (rr=(&w83), ss=(&w81)+0; ss!=(&w81)+1; ss+=1) *rr++ = *ss;
  w83 = (- w83 );
  rr=(&w88);
  *rr++ = w83;
  for (rr=(&w83), ss=(&w81)+0; ss!=(&w81)+1; ss+=1) *rr++ = *ss;
  rr=(&w91);
  *rr++ = w83;
  for (rr=(&w83), ss=(&w81)+0; ss!=(&w81)+1; ss+=1) *rr++ = *ss;
  w83 = (- w83 );
  rr=(&w81);
  *rr++ = w83;
  rr=w55;
  *rr++ = w88;
  *rr++ = w91;
  *rr++ = w81;
  trans(w55, s21, w3, s22, iw);
  fill(w76, 9, 0.);
  mtimes(w3, s22, w13, s13, w76, s2, w, 0);
  for (i=0, rr=w16, cs=w76; i<9; ++i) (*rr++) += (*cs++);
  fill(w17, 24, 0.);
  for (i=0, rr=w17; i<8; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w16+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  for (i=0, rr=w18, cs=w17; i<24; ++i) *rr++ = (- *cs++ );
  for (rr=w3, ss=w18+0; ss!=w18+3; ss+=1) *rr++ = *ss;
  for (i=0, rr=w3, cs=w3; i<3; ++i) (*rr++)  = (w1*(*cs++));
  for (i=0, rr=w3, cs=w3; i<3; ++i) (*rr++)  = (w84*(*cs++));
  for (rr=w55, ss=w18+0; ss!=w18+3; ss+=1) *rr++ = *ss;
  w88 = dot(3, w22, w55);
  w88 /= w6;
  for (i=0, rr=w55, cr=w21; i<3; ++i) (*rr++)  = ((*cr++)*w88);
  for (i=0, rr=w3, cs=w55; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=w55, ss=w18+3; ss!=w18+6; ss+=1) *rr++ = *ss;
  for (i=0, rr=w55, cs=w55; i<3; ++i) (*rr++)  = (w7*(*cs++));
  for (i=0, rr=w55, cs=w55; i<3; ++i) (*rr++)  = (w75*(*cs++));
  for (rr=w74, ss=w18+3; ss!=w18+6; ss+=1) *rr++ = *ss;
  w88 = dot(3, w25, w74);
  w88 /= w8;
  for (i=0, rr=w74, cr=w24; i<3; ++i) (*rr++)  = ((*cr++)*w88);
  for (i=0, rr=w55, cs=w74; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=w74, ss=w18+6; ss!=w18+9; ss+=1) *rr++ = *ss;
  for (i=0, rr=w74, cs=w74; i<3; ++i) (*rr++)  = (w9*(*cs++));
  for (i=0, rr=w74, cs=w74; i<3; ++i) (*rr++)  = (w86*(*cs++));
  for (rr=w96, ss=w18+6; ss!=w18+9; ss+=1) *rr++ = *ss;
  w88 = dot(3, w28, w96);
  w88 /= w29;
  for (i=0, rr=w96, cr=w27; i<3; ++i) (*rr++)  = ((*cr++)*w88);
  for (i=0, rr=w74, cs=w96; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=w96, ss=w18+9; ss!=w18+12; ss+=1) *rr++ = *ss;
  for (i=0, rr=w96, cs=w96; i<3; ++i) (*rr++)  = (w30*(*cs++));
  for (i=0, rr=w96, cs=w96; i<3; ++i) (*rr++)  = (w82*(*cs++));
  for (rr=w97, ss=w18+9; ss!=w18+12; ss+=1) *rr++ = *ss;
  w88 = dot(3, w33, w97);
  w88 /= w34;
  for (i=0, rr=w97, cr=w32; i<3; ++i) (*rr++)  = ((*cr++)*w88);
  for (i=0, rr=w96, cs=w97; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=w97, ss=w18+12; ss!=w18+15; ss+=1) *rr++ = *ss;
  for (i=0, rr=w97, cs=w97; i<3; ++i) (*rr++)  = (w35*(*cs++));
  for (i=0, rr=w97, cs=w97; i<3; ++i) (*rr++)  = (w78*(*cs++));
  for (rr=w98, ss=w18+12; ss!=w18+15; ss+=1) *rr++ = *ss;
  w88 = dot(3, w38, w98);
  w88 /= w39;
  for (i=0, rr=w98, cr=w37; i<3; ++i) (*rr++)  = ((*cr++)*w88);
  for (i=0, rr=w97, cs=w98; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=w98, ss=w18+15; ss!=w18+18; ss+=1) *rr++ = *ss;
  for (i=0, rr=w98, cs=w98; i<3; ++i) (*rr++)  = (w40*(*cs++));
  for (i=0, rr=w98, cs=w98; i<3; ++i) (*rr++)  = (w90*(*cs++));
  for (rr=w99, ss=w18+15; ss!=w18+18; ss+=1) *rr++ = *ss;
  w88 = dot(3, w43, w99);
  w88 /= w44;
  for (i=0, rr=w99, cr=w42; i<3; ++i) (*rr++)  = ((*cr++)*w88);
  for (i=0, rr=w98, cs=w99; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=w99, ss=w18+18; ss!=w18+21; ss+=1) *rr++ = *ss;
  for (i=0, rr=w99, cs=w99; i<3; ++i) (*rr++)  = (w45*(*cs++));
  for (i=0, rr=w99, cs=w99; i<3; ++i) (*rr++)  = (w79*(*cs++));
  for (rr=w100, ss=w18+18; ss!=w18+21; ss+=1) *rr++ = *ss;
  w88 = dot(3, w48, w100);
  w88 /= w49;
  for (i=0, rr=w100, cr=w47; i<3; ++i) (*rr++)  = ((*cr++)*w88);
  for (i=0, rr=w99, cs=w100; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=w100, ss=w18+21; ss!=w18+24; ss+=1) *rr++ = *ss;
  for (i=0, rr=w100, cs=w100; i<3; ++i) (*rr++)  = (w50*(*cs++));
  for (i=0, rr=w100, cs=w100; i<3; ++i) (*rr++)  = (w85*(*cs++));
  for (rr=w101, ss=w18+21; ss!=w18+24; ss+=1) *rr++ = *ss;
  w88 = dot(3, w53, w101);
  w88 /= w54;
  for (i=0, rr=w101, cr=w52; i<3; ++i) (*rr++)  = ((*cr++)*w88);
  for (i=0, rr=w100, cs=w101; i<3; ++i) (*rr++) -= (*cs++);
  rr=w18;
  for (i=0, cs=w3; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w55; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w74; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w96; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w97; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w98; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w99; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w100; i<3; ++i) *rr++ = *cs++;
  fill(w3, 3, 0.);
  for (i=0, rr=w3; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w18+j, tt=w0+i*8; k<8; ++k) *rr += ss[k*3]**tt++;
  for (i=0, rr=w3, cs=w3; i<3; ++i) (*rr++)  = (w80*(*cs++));
  for (i=0, rr=w3, cs=w3; i<3; ++i) *rr++ = (- *cs++ );
  fill(w55, 3, 0.);
  for (i=0, rr=w55; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w60+j, tt=w3+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  for (i=0, rr=w76, cs=w16; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  fill(w3, 3, 0.);
  for (i=0, rr=w3; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w76+j, tt=w59+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  for (i=0, rr=w55, cs=w3; i<3; ++i) (*rr++) += (*cs++);
  for (rr=w70, ss=w17+1; ss!=w17+25; ss+=3) *rr++ = *ss;
  for (i=0, rr=w72, cr=w65, cs=w70; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (rr=w73, ss=w18+2; ss!=w18+26; ss+=3) *rr++ = *ss;
  for (i=0, rr=w102, cr=w64, cs=w73; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w72, cs=w102; i<8; ++i) (*rr++) += (*cs++);
  for (rr=w102, ss=w17+2; ss!=w17+26; ss+=3) *rr++ = *ss;
  for (i=0, rr=w103, cr=w68, cs=w102; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (rr=w104, ss=w18+1; ss!=w18+25; ss+=3) *rr++ = *ss;
  for (i=0, rr=w105, cr=w67, cs=w104; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w103, cs=w105; i<8; ++i) (*rr++) += (*cs++);
  for (i=0, rr=w72, cs=w103; i<8; ++i) (*rr++) -= (*cs++);
  for (i=0, rr=w102, cr=w69, cs=w102; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (rr=w103, ss=w18+0; ss!=w18+24; ss+=3) *rr++ = *ss;
  for (i=0, rr=w105, cr=w67, cs=w103; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w102, cs=w105; i<8; ++i) (*rr++) += (*cs++);
  for (rr=w105, ss=w17+0; ss!=w17+24; ss+=3) *rr++ = *ss;
  for (i=0, rr=w65, cs=w105; i<8; ++i) (*rr++) *= (*cs++);
  for (i=0, rr=w73, cr=w71, cs=w73; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w65, cs=w73; i<8; ++i) (*rr++) += (*cs++);
  for (i=0, rr=w102, cs=w65; i<8; ++i) (*rr++) -= (*cs++);
  for (i=0, rr=w68, cs=w105; i<8; ++i) (*rr++) *= (*cs++);
  for (i=0, rr=w104, cr=w71, cs=w104; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w68, cs=w104; i<8; ++i) (*rr++) += (*cs++);
  for (i=0, rr=w69, cs=w70; i<8; ++i) (*rr++) *= (*cs++);
  for (i=0, rr=w103, cr=w64, cs=w103; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w69, cs=w103; i<8; ++i) (*rr++) += (*cs++);
  for (i=0, rr=w68, cs=w69; i<8; ++i) (*rr++) -= (*cs++);
  rr=w17;
  for (i=0, cs=w72; i<8; ++i) *rr++ = *cs++;
  for (i=0, cs=w102; i<8; ++i) *rr++ = *cs++;
  for (i=0, cs=w68; i<8; ++i) *rr++ = *cs++;
  for (i=0, rr=w18, cs=w17; i<3; ++i) for (j=0; j<8; ++j) rr[i+j*3] = *cs++;
  fill(w17, 24, 0.);
  for (i=0, rr=w17; i<8; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w63+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  for (i=0, rr=w76, cs=w16; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  fill(w18, 24, 0.);
  for (i=0, rr=w18; i<8; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w76+j, tt=w20+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  for (i=0, rr=w17, cs=w18; i<24; ++i) (*rr++) += (*cs++);
  fill(w3, 3, 0.);
  for (i=0, rr=w3; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w66+i*8; k<8; ++k) *rr += ss[k*3]**tt++;
  fill(w59, 3, 0.);
  for (i=0, rr=w59; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w62+j, tt=w3+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  fill(w3, 3, 0.);
  for (i=0, rr=w3; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w87+j, tt=w59+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  for (i=0, rr=w76, cs=w16; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  fill(w59, 3, 0.);
  for (i=0, rr=w59; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w76+j, tt=w77+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  for (i=0, rr=w3, cs=w59; i<3; ++i) (*rr++) += (*cs++);
  rr=w61;
  for (i=0, cs=w55; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w3; i<3; ++i) *rr++ = *cs++;
  for (rr=w56, ss=w61+0; ss!=w61+6; ss+=1) *rr++ = *ss;
  for (cii=s23, rr=w93, ss=w56; cii!=s23+6; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  w88 = 1.;
  w91 = w88;
  for (i=0;i<8;++i) {
    copy((&w91), 1, w72+ i*1);
  }
  for (i=0, rr=w72, cs=w72; i<8; ++i) *rr++ = (- *cs++ );
  for (rr=(&w91), ss=w72+0; ss!=w72+1; ss+=1) *rr++ = *ss;
  w91  = (w1*w91);
    project((&w91), s4, w55, s3, w);
  for (i=0, rr=w55, cs=w55; i<3; ++i) (*rr++)  = (w84*(*cs++));
    project(w22, s3, (&w91), s4, w);
  for (rr=(&w88), ss=w72+0; ss!=w72+1; ss+=1) *rr++ = *ss;
  w81 = dot(1, (&w91), (&w88));
  w81 /= w6;
  for (i=0, rr=w3, cr=w21; i<3; ++i) (*rr++)  = ((*cr++)*w81);
  for (i=0, rr=w55, cs=w3; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=(&w81), ss=w72+1; ss!=w72+2; ss+=1) *rr++ = *ss;
  w81  = (w7*w81);
    project((&w81), s4, w3, s3, w);
  for (i=0, rr=w3, cs=w3; i<3; ++i) (*rr++)  = (w75*(*cs++));
    project(w25, s3, (&w81), s4, w);
  for (rr=(&w91), ss=w72+1; ss!=w72+2; ss+=1) *rr++ = *ss;
  w88 = dot(1, (&w81), (&w91));
  w88 /= w8;
  for (i=0, rr=w59, cr=w24; i<3; ++i) (*rr++)  = ((*cr++)*w88);
  for (i=0, rr=w3, cs=w59; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=(&w88), ss=w72+2; ss!=w72+3; ss+=1) *rr++ = *ss;
  w88  = (w9*w88);
    project((&w88), s4, w59, s3, w);
  for (i=0, rr=w59, cs=w59; i<3; ++i) (*rr++)  = (w86*(*cs++));
    project(w28, s3, (&w88), s4, w);
  for (rr=(&w81), ss=w72+2; ss!=w72+3; ss+=1) *rr++ = *ss;
  w91 = dot(1, (&w88), (&w81));
  w91 /= w29;
  for (i=0, rr=w77, cr=w27; i<3; ++i) (*rr++)  = ((*cr++)*w91);
  for (i=0, rr=w59, cs=w77; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=(&w91), ss=w72+3; ss!=w72+4; ss+=1) *rr++ = *ss;
  w91  = (w30*w91);
    project((&w91), s4, w77, s3, w);
  for (i=0, rr=w77, cs=w77; i<3; ++i) (*rr++)  = (w82*(*cs++));
    project(w33, s3, (&w91), s4, w);
  for (rr=(&w88), ss=w72+3; ss!=w72+4; ss+=1) *rr++ = *ss;
  w81 = dot(1, (&w91), (&w88));
  w81 /= w34;
  for (i=0, rr=w74, cr=w32; i<3; ++i) (*rr++)  = ((*cr++)*w81);
  for (i=0, rr=w77, cs=w74; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=(&w81), ss=w72+4; ss!=w72+5; ss+=1) *rr++ = *ss;
  w81  = (w35*w81);
    project((&w81), s4, w74, s3, w);
  for (i=0, rr=w74, cs=w74; i<3; ++i) (*rr++)  = (w78*(*cs++));
    project(w38, s3, (&w81), s4, w);
  for (rr=(&w91), ss=w72+4; ss!=w72+5; ss+=1) *rr++ = *ss;
  w88 = dot(1, (&w81), (&w91));
  w88 /= w39;
  for (i=0, rr=w96, cr=w37; i<3; ++i) (*rr++)  = ((*cr++)*w88);
  for (i=0, rr=w74, cs=w96; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=(&w88), ss=w72+5; ss!=w72+6; ss+=1) *rr++ = *ss;
  w88  = (w40*w88);
    project((&w88), s4, w96, s3, w);
  for (i=0, rr=w96, cs=w96; i<3; ++i) (*rr++)  = (w90*(*cs++));
    project(w43, s3, (&w88), s4, w);
  for (rr=(&w81), ss=w72+5; ss!=w72+6; ss+=1) *rr++ = *ss;
  w91 = dot(1, (&w88), (&w81));
  w91 /= w44;
  for (i=0, rr=w97, cr=w42; i<3; ++i) (*rr++)  = ((*cr++)*w91);
  for (i=0, rr=w96, cs=w97; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=(&w91), ss=w72+6; ss!=w72+7; ss+=1) *rr++ = *ss;
  w91  = (w45*w91);
    project((&w91), s4, w97, s3, w);
  for (i=0, rr=w97, cs=w97; i<3; ++i) (*rr++)  = (w79*(*cs++));
    project(w48, s3, (&w91), s4, w);
  for (rr=(&w88), ss=w72+6; ss!=w72+7; ss+=1) *rr++ = *ss;
  w81 = dot(1, (&w91), (&w88));
  w81 /= w49;
  for (i=0, rr=w98, cr=w47; i<3; ++i) (*rr++)  = ((*cr++)*w81);
  for (i=0, rr=w97, cs=w98; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=(&w81), ss=w72+7; ss!=w72+8; ss+=1) *rr++ = *ss;
  w81  = (w50*w81);
    project((&w81), s4, w98, s3, w);
  for (i=0, rr=w98, cs=w98; i<3; ++i) (*rr++)  = (w85*(*cs++));
    project(w53, s3, (&w81), s4, w);
  for (rr=(&w91), ss=w72+7; ss!=w72+8; ss+=1) *rr++ = *ss;
  w88 = dot(1, (&w81), (&w91));
  w88 /= w54;
  for (i=0, rr=w99, cr=w52; i<3; ++i) (*rr++)  = ((*cr++)*w88);
  for (i=0, rr=w98, cs=w99; i<3; ++i) (*rr++) -= (*cs++);
  rr=w17;
  for (i=0, cs=w55; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w3; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w59; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w77; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w74; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w96; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w97; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w98; i<3; ++i) *rr++ = *cs++;
  fill(w55, 3, 0.);
  for (i=0, rr=w55; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w0+i*8; k<8; ++k) *rr += ss[k*3]**tt++;
  for (i=0, rr=w55, cs=w55; i<3; ++i) (*rr++)  = (w80*(*cs++));
  for (i=0, rr=w55, cs=w55; i<3; ++i) *rr++ = (- *cs++ );
  fill(w3, 3, 0.);
  for (i=0, rr=w3; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w60+j, tt=w55+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  for (rr=w72, ss=w17+2; ss!=w17+26; ss+=3) *rr++ = *ss;
  for (i=0, rr=w102, cr=w64, cs=w72; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (rr=w68, ss=w17+1; ss!=w17+25; ss+=3) *rr++ = *ss;
  for (i=0, rr=w69, cr=w67, cs=w68; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w102, cs=w69; i<8; ++i) (*rr++) -= (*cs++);
  for (rr=w69, ss=w17+0; ss!=w17+24; ss+=3) *rr++ = *ss;
  for (i=0, rr=w103, cr=w67, cs=w69; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w72, cr=w71, cs=w72; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w103, cs=w72; i<8; ++i) (*rr++) -= (*cs++);
  for (i=0, rr=w68, cr=w71, cs=w68; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w69, cr=w64, cs=w69; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w68, cs=w69; i<8; ++i) (*rr++) -= (*cs++);
  rr=w17;
  for (i=0, cs=w102; i<8; ++i) *rr++ = *cs++;
  for (i=0, cs=w103; i<8; ++i) *rr++ = *cs++;
  for (i=0, cs=w68; i<8; ++i) *rr++ = *cs++;
  for (i=0, rr=w18, cs=w17; i<3; ++i) for (j=0; j<8; ++j) rr[i+j*3] = *cs++;
  fill(w17, 24, 0.);
  for (i=0, rr=w17; i<8; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w63+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  fill(w55, 3, 0.);
  for (i=0, rr=w55; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w66+i*8; k<8; ++k) *rr += ss[k*3]**tt++;
  fill(w59, 3, 0.);
  for (i=0, rr=w59; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w62+j, tt=w55+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  fill(w55, 3, 0.);
  for (i=0, rr=w55; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w87+j, tt=w59+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  rr=w56;
  for (i=0, cs=w3; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w55; i<3; ++i) *rr++ = *cs++;
  for (rr=w61, ss=w56+0; ss!=w56+6; ss+=1) *rr++ = *ss;
  for (cii=s24, rr=w93, ss=w61; cii!=s24+6; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  w88 = 1.;
  w81 = w88;
  for (i=0;i<8;++i) {
    copy((&w81), 1, w102+ i*1);
  }
  for (i=0, rr=w102, cs=w102; i<8; ++i) *rr++ = (- *cs++ );
  for (rr=(&w81), ss=w102+0; ss!=w102+1; ss+=1) *rr++ = *ss;
  w81  = (w1*w81);
    project((&w81), s6, w3, s3, w);
  for (i=0, rr=w3, cs=w3; i<3; ++i) (*rr++)  = (w84*(*cs++));
    project(w22, s3, (&w81), s6, w);
  for (rr=(&w88), ss=w102+0; ss!=w102+1; ss+=1) *rr++ = *ss;
  w91 = dot(1, (&w81), (&w88));
  w91 /= w6;
  for (i=0, rr=w55, cr=w21; i<3; ++i) (*rr++)  = ((*cr++)*w91);
  for (i=0, rr=w3, cs=w55; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=(&w91), ss=w102+1; ss!=w102+2; ss+=1) *rr++ = *ss;
  w91  = (w7*w91);
    project((&w91), s6, w55, s3, w);
  for (i=0, rr=w55, cs=w55; i<3; ++i) (*rr++)  = (w75*(*cs++));
    project(w25, s3, (&w91), s6, w);
  for (rr=(&w81), ss=w102+1; ss!=w102+2; ss+=1) *rr++ = *ss;
  w88 = dot(1, (&w91), (&w81));
  w88 /= w8;
  for (i=0, rr=w59, cr=w24; i<3; ++i) (*rr++)  = ((*cr++)*w88);
  for (i=0, rr=w55, cs=w59; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=(&w88), ss=w102+2; ss!=w102+3; ss+=1) *rr++ = *ss;
  w88  = (w9*w88);
    project((&w88), s6, w59, s3, w);
  for (i=0, rr=w59, cs=w59; i<3; ++i) (*rr++)  = (w86*(*cs++));
    project(w28, s3, (&w88), s6, w);
  for (rr=(&w91), ss=w102+2; ss!=w102+3; ss+=1) *rr++ = *ss;
  w81 = dot(1, (&w88), (&w91));
  w81 /= w29;
  for (i=0, rr=w77, cr=w27; i<3; ++i) (*rr++)  = ((*cr++)*w81);
  for (i=0, rr=w59, cs=w77; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=(&w81), ss=w102+3; ss!=w102+4; ss+=1) *rr++ = *ss;
  w81  = (w30*w81);
    project((&w81), s6, w77, s3, w);
  for (i=0, rr=w77, cs=w77; i<3; ++i) (*rr++)  = (w82*(*cs++));
    project(w33, s3, (&w81), s6, w);
  for (rr=(&w88), ss=w102+3; ss!=w102+4; ss+=1) *rr++ = *ss;
  w91 = dot(1, (&w81), (&w88));
  w91 /= w34;
  for (i=0, rr=w74, cr=w32; i<3; ++i) (*rr++)  = ((*cr++)*w91);
  for (i=0, rr=w77, cs=w74; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=(&w91), ss=w102+4; ss!=w102+5; ss+=1) *rr++ = *ss;
  w91  = (w35*w91);
    project((&w91), s6, w74, s3, w);
  for (i=0, rr=w74, cs=w74; i<3; ++i) (*rr++)  = (w78*(*cs++));
    project(w38, s3, (&w91), s6, w);
  for (rr=(&w81), ss=w102+4; ss!=w102+5; ss+=1) *rr++ = *ss;
  w88 = dot(1, (&w91), (&w81));
  w88 /= w39;
  for (i=0, rr=w96, cr=w37; i<3; ++i) (*rr++)  = ((*cr++)*w88);
  for (i=0, rr=w74, cs=w96; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=(&w88), ss=w102+5; ss!=w102+6; ss+=1) *rr++ = *ss;
  w88  = (w40*w88);
    project((&w88), s6, w96, s3, w);
  for (i=0, rr=w96, cs=w96; i<3; ++i) (*rr++)  = (w90*(*cs++));
    project(w43, s3, (&w88), s6, w);
  for (rr=(&w91), ss=w102+5; ss!=w102+6; ss+=1) *rr++ = *ss;
  w81 = dot(1, (&w88), (&w91));
  w81 /= w44;
  for (i=0, rr=w97, cr=w42; i<3; ++i) (*rr++)  = ((*cr++)*w81);
  for (i=0, rr=w96, cs=w97; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=(&w81), ss=w102+6; ss!=w102+7; ss+=1) *rr++ = *ss;
  w81  = (w45*w81);
    project((&w81), s6, w97, s3, w);
  for (i=0, rr=w97, cs=w97; i<3; ++i) (*rr++)  = (w79*(*cs++));
    project(w48, s3, (&w81), s6, w);
  for (rr=(&w88), ss=w102+6; ss!=w102+7; ss+=1) *rr++ = *ss;
  w91 = dot(1, (&w81), (&w88));
  w91 /= w49;
  for (i=0, rr=w98, cr=w47; i<3; ++i) (*rr++)  = ((*cr++)*w91);
  for (i=0, rr=w97, cs=w98; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=(&w91), ss=w102+7; ss!=w102+8; ss+=1) *rr++ = *ss;
  w91  = (w50*w91);
    project((&w91), s6, w98, s3, w);
  for (i=0, rr=w98, cs=w98; i<3; ++i) (*rr++)  = (w85*(*cs++));
    project(w53, s3, (&w91), s6, w);
  for (rr=(&w81), ss=w102+7; ss!=w102+8; ss+=1) *rr++ = *ss;
  w88 = dot(1, (&w91), (&w81));
  w88 /= w54;
  for (i=0, rr=w99, cr=w52; i<3; ++i) (*rr++)  = ((*cr++)*w88);
  for (i=0, rr=w98, cs=w99; i<3; ++i) (*rr++) -= (*cs++);
  rr=w17;
  for (i=0, cs=w3; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w55; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w59; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w77; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w74; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w96; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w97; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w98; i<3; ++i) *rr++ = *cs++;
  fill(w3, 3, 0.);
  for (i=0, rr=w3; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w0+i*8; k<8; ++k) *rr += ss[k*3]**tt++;
  for (i=0, rr=w3, cs=w3; i<3; ++i) (*rr++)  = (w80*(*cs++));
  for (i=0, rr=w3, cs=w3; i<3; ++i) *rr++ = (- *cs++ );
  fill(w55, 3, 0.);
  for (i=0, rr=w55; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w60+j, tt=w3+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  for (rr=w102, ss=w17+2; ss!=w17+26; ss+=3) *rr++ = *ss;
  for (i=0, rr=w103, cr=w64, cs=w102; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (rr=w68, ss=w17+1; ss!=w17+25; ss+=3) *rr++ = *ss;
  for (i=0, rr=w69, cr=w67, cs=w68; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w103, cs=w69; i<8; ++i) (*rr++) -= (*cs++);
  for (rr=w69, ss=w17+0; ss!=w17+24; ss+=3) *rr++ = *ss;
  for (i=0, rr=w72, cr=w67, cs=w69; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w102, cr=w71, cs=w102; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w72, cs=w102; i<8; ++i) (*rr++) -= (*cs++);
  for (i=0, rr=w68, cr=w71, cs=w68; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w69, cr=w64, cs=w69; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w68, cs=w69; i<8; ++i) (*rr++) -= (*cs++);
  rr=w17;
  for (i=0, cs=w103; i<8; ++i) *rr++ = *cs++;
  for (i=0, cs=w72; i<8; ++i) *rr++ = *cs++;
  for (i=0, cs=w68; i<8; ++i) *rr++ = *cs++;
  for (i=0, rr=w18, cs=w17; i<3; ++i) for (j=0; j<8; ++j) rr[i+j*3] = *cs++;
  fill(w17, 24, 0.);
  for (i=0, rr=w17; i<8; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w63+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  fill(w3, 3, 0.);
  for (i=0, rr=w3; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w66+i*8; k<8; ++k) *rr += ss[k*3]**tt++;
  fill(w59, 3, 0.);
  for (i=0, rr=w59; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w62+j, tt=w3+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  fill(w3, 3, 0.);
  for (i=0, rr=w3; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w87+j, tt=w59+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  rr=w61;
  for (i=0, cs=w55; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w3; i<3; ++i) *rr++ = *cs++;
  for (rr=w56, ss=w61+0; ss!=w61+6; ss+=1) *rr++ = *ss;
  for (cii=s25, rr=w93, ss=w56; cii!=s25+6; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  w88 = 1.;
  w91 = w88;
  for (i=0;i<8;++i) {
    copy((&w91), 1, w103+ i*1);
  }
  for (i=0, rr=w103, cs=w103; i<8; ++i) *rr++ = (- *cs++ );
  for (rr=(&w91), ss=w103+0; ss!=w103+1; ss+=1) *rr++ = *ss;
  w1 *= w91;
    project((&w1), s8, w55, s3, w);
  for (i=0, rr=w55, cs=w55; i<3; ++i) (*rr++)  = (w84*(*cs++));
    project(w22, s3, (&w84), s8, w);
  for (rr=(&w1), ss=w103+0; ss!=w103+1; ss+=1) *rr++ = *ss;
  w91 = dot(1, (&w84), (&w1));
  w91 /= w6;
  for (i=0, rr=w21; i<3; ++i) (*rr++) *= w91;
  for (i=0, rr=w55, cs=w21; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=(&w91), ss=w103+1; ss!=w103+2; ss+=1) *rr++ = *ss;
  w7 *= w91;
    project((&w7), s8, w21, s3, w);
  for (i=0, rr=w21, cs=w21; i<3; ++i) (*rr++)  = (w75*(*cs++));
    project(w25, s3, (&w75), s8, w);
  for (rr=(&w7), ss=w103+1; ss!=w103+2; ss+=1) *rr++ = *ss;
  w91 = dot(1, (&w75), (&w7));
  w91 /= w8;
  for (i=0, rr=w24; i<3; ++i) (*rr++) *= w91;
  for (i=0, rr=w21, cs=w24; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=(&w91), ss=w103+2; ss!=w103+3; ss+=1) *rr++ = *ss;
  w9 *= w91;
    project((&w9), s8, w24, s3, w);
  for (i=0, rr=w24, cs=w24; i<3; ++i) (*rr++)  = (w86*(*cs++));
    project(w28, s3, (&w86), s8, w);
  for (rr=(&w9), ss=w103+2; ss!=w103+3; ss+=1) *rr++ = *ss;
  w91 = dot(1, (&w86), (&w9));
  w91 /= w29;
  for (i=0, rr=w27; i<3; ++i) (*rr++) *= w91;
  for (i=0, rr=w24, cs=w27; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=(&w91), ss=w103+3; ss!=w103+4; ss+=1) *rr++ = *ss;
  w30 *= w91;
    project((&w30), s8, w27, s3, w);
  for (i=0, rr=w27, cs=w27; i<3; ++i) (*rr++)  = (w82*(*cs++));
    project(w33, s3, (&w82), s8, w);
  for (rr=(&w30), ss=w103+3; ss!=w103+4; ss+=1) *rr++ = *ss;
  w91 = dot(1, (&w82), (&w30));
  w91 /= w34;
  for (i=0, rr=w32; i<3; ++i) (*rr++) *= w91;
  for (i=0, rr=w27, cs=w32; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=(&w91), ss=w103+4; ss!=w103+5; ss+=1) *rr++ = *ss;
  w35 *= w91;
    project((&w35), s8, w32, s3, w);
  for (i=0, rr=w32, cs=w32; i<3; ++i) (*rr++)  = (w78*(*cs++));
    project(w38, s3, (&w78), s8, w);
  for (rr=(&w35), ss=w103+4; ss!=w103+5; ss+=1) *rr++ = *ss;
  w91 = dot(1, (&w78), (&w35));
  w91 /= w39;
  for (i=0, rr=w37; i<3; ++i) (*rr++) *= w91;
  for (i=0, rr=w32, cs=w37; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=(&w91), ss=w103+5; ss!=w103+6; ss+=1) *rr++ = *ss;
  w40 *= w91;
    project((&w40), s8, w37, s3, w);
  for (i=0, rr=w37, cs=w37; i<3; ++i) (*rr++)  = (w90*(*cs++));
    project(w43, s3, (&w90), s8, w);
  for (rr=(&w40), ss=w103+5; ss!=w103+6; ss+=1) *rr++ = *ss;
  w91 = dot(1, (&w90), (&w40));
  w91 /= w44;
  for (i=0, rr=w42; i<3; ++i) (*rr++) *= w91;
  for (i=0, rr=w37, cs=w42; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=(&w91), ss=w103+6; ss!=w103+7; ss+=1) *rr++ = *ss;
  w45 *= w91;
    project((&w45), s8, w42, s3, w);
  for (i=0, rr=w42, cs=w42; i<3; ++i) (*rr++)  = (w79*(*cs++));
    project(w48, s3, (&w79), s8, w);
  for (rr=(&w45), ss=w103+6; ss!=w103+7; ss+=1) *rr++ = *ss;
  w91 = dot(1, (&w79), (&w45));
  w91 /= w49;
  for (i=0, rr=w47; i<3; ++i) (*rr++) *= w91;
  for (i=0, rr=w42, cs=w47; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=(&w91), ss=w103+7; ss!=w103+8; ss+=1) *rr++ = *ss;
  w50 *= w91;
    project((&w50), s8, w47, s3, w);
  for (i=0, rr=w47, cs=w47; i<3; ++i) (*rr++)  = (w85*(*cs++));
    project(w53, s3, (&w85), s8, w);
  for (rr=(&w50), ss=w103+7; ss!=w103+8; ss+=1) *rr++ = *ss;
  w91 = dot(1, (&w85), (&w50));
  w91 /= w54;
  for (i=0, rr=w52; i<3; ++i) (*rr++) *= w91;
  for (i=0, rr=w47, cs=w52; i<3; ++i) (*rr++) -= (*cs++);
  rr=w17;
  for (i=0, cs=w55; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w21; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w24; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w32; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w37; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w42; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w47; i<3; ++i) *rr++ = *cs++;
  fill(w55, 3, 0.);
  for (i=0, rr=w55; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w0+i*8; k<8; ++k) *rr += ss[k*3]**tt++;
  for (i=0, rr=w55, cs=w55; i<3; ++i) (*rr++)  = (w80*(*cs++));
  for (i=0, rr=w55, cs=w55; i<3; ++i) *rr++ = (- *cs++ );
  fill(w21, 3, 0.);
  for (i=0, rr=w21; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w60+j, tt=w55+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  for (rr=w103, ss=w17+2; ss!=w17+26; ss+=3) *rr++ = *ss;
  for (i=0, rr=w72, cr=w64, cs=w103; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (rr=w68, ss=w17+1; ss!=w17+25; ss+=3) *rr++ = *ss;
  for (i=0, rr=w69, cr=w67, cs=w68; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w72, cs=w69; i<8; ++i) (*rr++) -= (*cs++);
  for (rr=w69, ss=w17+0; ss!=w17+24; ss+=3) *rr++ = *ss;
  for (i=0, rr=w102, cr=w67, cs=w69; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w103, cr=w71, cs=w103; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w102, cs=w103; i<8; ++i) (*rr++) -= (*cs++);
  for (i=0, rr=w68, cr=w71, cs=w68; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w69, cr=w64, cs=w69; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w68, cs=w69; i<8; ++i) (*rr++) -= (*cs++);
  rr=w17;
  for (i=0, cs=w72; i<8; ++i) *rr++ = *cs++;
  for (i=0, cs=w102; i<8; ++i) *rr++ = *cs++;
  for (i=0, cs=w68; i<8; ++i) *rr++ = *cs++;
  for (i=0, rr=w18, cs=w17; i<3; ++i) for (j=0; j<8; ++j) rr[i+j*3] = *cs++;
  fill(w17, 24, 0.);
  for (i=0, rr=w17; i<8; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w63+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  fill(w55, 3, 0.);
  for (i=0, rr=w55; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w66+i*8; k<8; ++k) *rr += ss[k*3]**tt++;
  fill(w24, 3, 0.);
  for (i=0, rr=w24; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w62+j, tt=w55+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  fill(w55, 3, 0.);
  for (i=0, rr=w55; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w87+j, tt=w24+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  rr=w56;
  for (i=0, cs=w21; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w55; i<3; ++i) *rr++ = *cs++;
  for (rr=w61, ss=w56+0; ss!=w56+6; ss+=1) *rr++ = *ss;
  for (cii=s26, rr=w93, ss=w61; cii!=s26+6; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  trans(w93, s28, w107, s27, iw);
    project(w107, s27, w108, s29, w);
  if (res[1]) copy(w108, 117, res[1]);
  w6 = (1./ w6 );
  for (i=0, rr=w5, cs=w5; i<3; ++i) (*rr++)  = (w6*(*cs++));
  rr=w21;
  for (i=0, cs=w5; i<3; ++i) *rr++ = *cs++;
  fill(w55, 3, 0.);
  mtimes(w21, s31, w0, s30, w55, s3, w, 0);
  w58 = (1./ w58 );
  for (i=0, rr=w55, cs=w55; i<3; ++i) (*rr++)  = (w58*(*cs++));
  for (i=0, rr=w55, cs=w55; i<3; ++i) *rr++ = (- *cs++ );
  fill(w21, 3, 0.);
  for (i=0, rr=w21; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w60+j, tt=w55+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
    project(w64, s33, (&w6), s32, w);
  for (rr=(&w80), ss=w5+2; ss!=w5+3; ss+=1) *rr++ = *ss;
  w6 *= w80;
    project(w67, s33, (&w91), s32, w);
  for (rr=(&w85), ss=w5+1; ss!=w5+2; ss+=1) *rr++ = *ss;
  w91 *= w85;
  w6 -= w91;
    project(w67, s33, (&w91), s32, w);
  for (rr=(&w50), ss=w5+0; ss!=w5+1; ss+=1) *rr++ = *ss;
  w91 *= w50;
    project(w71, s33, (&w79), s32, w);
  w79 *= w80;
  w91 -= w79;
    project(w71, s33, (&w79), s32, w);
  w79 *= w85;
    project(w64, s33, (&w85), s32, w);
  w85 *= w50;
  w79 -= w85;
  rr=w5;
  *rr++ = w6;
  *rr++ = w91;
  *rr++ = w79;
  trans(w5, s34, w55, s31, iw);
  fill(w17, 24, 0.);
  mtimes(w63, s2, w55, s31, w17, s35, w, 0);
  fill(w55, 3, 0.);
  for (i=0, rr=w55; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w66+i*8; k<8; ++k) *rr += ss[k*3]**tt++;
  fill(w5, 3, 0.);
  for (i=0, rr=w5; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w62+j, tt=w55+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  fill(w55, 3, 0.);
  for (i=0, rr=w55; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w87+j, tt=w5+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  rr=w61;
  for (i=0, cs=w21; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w55; i<3; ++i) *rr++ = *cs++;
  for (rr=w56, ss=w61+0; ss!=w61+6; ss+=1) *rr++ = *ss;
  fill(w113, 48, 0.);
  for (rr=w113+0, ss=w56; rr!=w113+48; rr+=8) *rr = *ss++;
  w8 = (1./ w8 );
  for (i=0, rr=w23, cs=w23; i<3; ++i) (*rr++)  = (w8*(*cs++));
  rr=w21;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  fill(w55, 3, 0.);
  mtimes(w21, s36, w0, s30, w55, s3, w, 0);
  for (i=0, rr=w55, cs=w55; i<3; ++i) (*rr++)  = (w58*(*cs++));
  for (i=0, rr=w55, cs=w55; i<3; ++i) *rr++ = (- *cs++ );
  fill(w21, 3, 0.);
  for (i=0, rr=w21; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w60+j, tt=w55+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
    project(w64, s33, (&w8), s37, w);
  for (rr=(&w6), ss=w23+2; ss!=w23+3; ss+=1) *rr++ = *ss;
  w8 *= w6;
    project(w67, s33, (&w91), s37, w);
  for (rr=(&w79), ss=w23+1; ss!=w23+2; ss+=1) *rr++ = *ss;
  w91 *= w79;
  w8 -= w91;
    project(w67, s33, (&w91), s37, w);
  for (rr=(&w85), ss=w23+0; ss!=w23+1; ss+=1) *rr++ = *ss;
  w91 *= w85;
    project(w71, s33, (&w50), s37, w);
  w50 *= w6;
  w91 -= w50;
    project(w71, s33, (&w50), s37, w);
  w50 *= w79;
    project(w64, s33, (&w79), s37, w);
  w79 *= w85;
  w50 -= w79;
  rr=w23;
  *rr++ = w8;
  *rr++ = w91;
  *rr++ = w50;
  trans(w23, s38, w55, s36, iw);
  fill(w17, 24, 0.);
  mtimes(w63, s2, w55, s36, w17, s35, w, 0);
  fill(w55, 3, 0.);
  for (i=0, rr=w55; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w66+i*8; k<8; ++k) *rr += ss[k*3]**tt++;
  fill(w23, 3, 0.);
  for (i=0, rr=w23; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w62+j, tt=w55+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  fill(w55, 3, 0.);
  for (i=0, rr=w55; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w87+j, tt=w23+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  rr=w56;
  for (i=0, cs=w21; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w55; i<3; ++i) *rr++ = *cs++;
  for (rr=w61, ss=w56+0; ss!=w56+6; ss+=1) *rr++ = *ss;
  for (rr=w113+1, ss=w61; rr!=w113+49; rr+=8) *rr = *ss++;
  w29 = (1./ w29 );
  for (i=0, rr=w26, cs=w26; i<3; ++i) (*rr++)  = (w29*(*cs++));
  rr=w21;
  for (i=0, cs=w26; i<3; ++i) *rr++ = *cs++;
  fill(w55, 3, 0.);
  mtimes(w21, s39, w0, s30, w55, s3, w, 0);
  for (i=0, rr=w55, cs=w55; i<3; ++i) (*rr++)  = (w58*(*cs++));
  for (i=0, rr=w55, cs=w55; i<3; ++i) *rr++ = (- *cs++ );
  fill(w21, 3, 0.);
  for (i=0, rr=w21; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w60+j, tt=w55+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
    project(w64, s33, (&w29), s40, w);
  for (rr=(&w8), ss=w26+2; ss!=w26+3; ss+=1) *rr++ = *ss;
  w29 *= w8;
    project(w67, s33, (&w91), s40, w);
  for (rr=(&w50), ss=w26+1; ss!=w26+2; ss+=1) *rr++ = *ss;
  w91 *= w50;
  w29 -= w91;
    project(w67, s33, (&w91), s40, w);
  for (rr=(&w79), ss=w26+0; ss!=w26+1; ss+=1) *rr++ = *ss;
  w91 *= w79;
    project(w71, s33, (&w85), s40, w);
  w85 *= w8;
  w91 -= w85;
    project(w71, s33, (&w85), s40, w);
  w85 *= w50;
    project(w64, s33, (&w50), s40, w);
  w50 *= w79;
  w85 -= w50;
  rr=w26;
  *rr++ = w29;
  *rr++ = w91;
  *rr++ = w85;
  trans(w26, s41, w55, s39, iw);
  fill(w17, 24, 0.);
  mtimes(w63, s2, w55, s39, w17, s35, w, 0);
  fill(w55, 3, 0.);
  for (i=0, rr=w55; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w66+i*8; k<8; ++k) *rr += ss[k*3]**tt++;
  fill(w26, 3, 0.);
  for (i=0, rr=w26; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w62+j, tt=w55+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  fill(w55, 3, 0.);
  for (i=0, rr=w55; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w87+j, tt=w26+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  rr=w61;
  for (i=0, cs=w21; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w55; i<3; ++i) *rr++ = *cs++;
  for (rr=w56, ss=w61+0; ss!=w61+6; ss+=1) *rr++ = *ss;
  for (rr=w113+2, ss=w56; rr!=w113+50; rr+=8) *rr = *ss++;
  w34 = (1./ w34 );
  for (i=0, rr=w31, cs=w31; i<3; ++i) (*rr++)  = (w34*(*cs++));
  rr=w21;
  for (i=0, cs=w31; i<3; ++i) *rr++ = *cs++;
  fill(w55, 3, 0.);
  mtimes(w21, s42, w0, s30, w55, s3, w, 0);
  for (i=0, rr=w55, cs=w55; i<3; ++i) (*rr++)  = (w58*(*cs++));
  for (i=0, rr=w55, cs=w55; i<3; ++i) *rr++ = (- *cs++ );
  fill(w21, 3, 0.);
  for (i=0, rr=w21; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w60+j, tt=w55+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
    project(w64, s33, (&w34), s43, w);
  for (rr=(&w29), ss=w31+2; ss!=w31+3; ss+=1) *rr++ = *ss;
  w34 *= w29;
    project(w67, s33, (&w91), s43, w);
  for (rr=(&w85), ss=w31+1; ss!=w31+2; ss+=1) *rr++ = *ss;
  w91 *= w85;
  w34 -= w91;
    project(w67, s33, (&w91), s43, w);
  for (rr=(&w50), ss=w31+0; ss!=w31+1; ss+=1) *rr++ = *ss;
  w91 *= w50;
    project(w71, s33, (&w79), s43, w);
  w79 *= w29;
  w91 -= w79;
    project(w71, s33, (&w79), s43, w);
  w79 *= w85;
    project(w64, s33, (&w85), s43, w);
  w85 *= w50;
  w79 -= w85;
  rr=w31;
  *rr++ = w34;
  *rr++ = w91;
  *rr++ = w79;
  trans(w31, s44, w55, s42, iw);
  fill(w17, 24, 0.);
  mtimes(w63, s2, w55, s42, w17, s35, w, 0);
  fill(w55, 3, 0.);
  for (i=0, rr=w55; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w66+i*8; k<8; ++k) *rr += ss[k*3]**tt++;
  fill(w31, 3, 0.);
  for (i=0, rr=w31; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w62+j, tt=w55+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  fill(w55, 3, 0.);
  for (i=0, rr=w55; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w87+j, tt=w31+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  rr=w56;
  for (i=0, cs=w21; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w55; i<3; ++i) *rr++ = *cs++;
  for (rr=w61, ss=w56+0; ss!=w56+6; ss+=1) *rr++ = *ss;
  for (rr=w113+3, ss=w61; rr!=w113+51; rr+=8) *rr = *ss++;
  w39 = (1./ w39 );
  for (i=0, rr=w36, cs=w36; i<3; ++i) (*rr++)  = (w39*(*cs++));
  rr=w21;
  for (i=0, cs=w36; i<3; ++i) *rr++ = *cs++;
  fill(w55, 3, 0.);
  mtimes(w21, s45, w0, s30, w55, s3, w, 0);
  for (i=0, rr=w55, cs=w55; i<3; ++i) (*rr++)  = (w58*(*cs++));
  for (i=0, rr=w55, cs=w55; i<3; ++i) *rr++ = (- *cs++ );
  fill(w21, 3, 0.);
  for (i=0, rr=w21; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w60+j, tt=w55+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
    project(w64, s33, (&w39), s46, w);
  for (rr=(&w34), ss=w36+2; ss!=w36+3; ss+=1) *rr++ = *ss;
  w39 *= w34;
    project(w67, s33, (&w91), s46, w);
  for (rr=(&w79), ss=w36+1; ss!=w36+2; ss+=1) *rr++ = *ss;
  w91 *= w79;
  w39 -= w91;
    project(w67, s33, (&w91), s46, w);
  for (rr=(&w85), ss=w36+0; ss!=w36+1; ss+=1) *rr++ = *ss;
  w91 *= w85;
    project(w71, s33, (&w50), s46, w);
  w50 *= w34;
  w91 -= w50;
    project(w71, s33, (&w50), s46, w);
  w50 *= w79;
    project(w64, s33, (&w79), s46, w);
  w79 *= w85;
  w50 -= w79;
  rr=w36;
  *rr++ = w39;
  *rr++ = w91;
  *rr++ = w50;
  trans(w36, s47, w55, s45, iw);
  fill(w17, 24, 0.);
  mtimes(w63, s2, w55, s45, w17, s35, w, 0);
  fill(w55, 3, 0.);
  for (i=0, rr=w55; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w66+i*8; k<8; ++k) *rr += ss[k*3]**tt++;
  fill(w36, 3, 0.);
  for (i=0, rr=w36; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w62+j, tt=w55+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  fill(w55, 3, 0.);
  for (i=0, rr=w55; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w87+j, tt=w36+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  rr=w61;
  for (i=0, cs=w21; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w55; i<3; ++i) *rr++ = *cs++;
  for (rr=w56, ss=w61+0; ss!=w61+6; ss+=1) *rr++ = *ss;
  for (rr=w113+4, ss=w56; rr!=w113+52; rr+=8) *rr = *ss++;
  w44 = (1./ w44 );
  for (i=0, rr=w41, cs=w41; i<3; ++i) (*rr++)  = (w44*(*cs++));
  rr=w21;
  for (i=0, cs=w41; i<3; ++i) *rr++ = *cs++;
  fill(w55, 3, 0.);
  mtimes(w21, s48, w0, s30, w55, s3, w, 0);
  for (i=0, rr=w55, cs=w55; i<3; ++i) (*rr++)  = (w58*(*cs++));
  for (i=0, rr=w55, cs=w55; i<3; ++i) *rr++ = (- *cs++ );
  fill(w21, 3, 0.);
  for (i=0, rr=w21; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w60+j, tt=w55+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
    project(w64, s33, (&w44), s49, w);
  for (rr=(&w39), ss=w41+2; ss!=w41+3; ss+=1) *rr++ = *ss;
  w44 *= w39;
    project(w67, s33, (&w91), s49, w);
  for (rr=(&w50), ss=w41+1; ss!=w41+2; ss+=1) *rr++ = *ss;
  w91 *= w50;
  w44 -= w91;
    project(w67, s33, (&w91), s49, w);
  for (rr=(&w79), ss=w41+0; ss!=w41+1; ss+=1) *rr++ = *ss;
  w91 *= w79;
    project(w71, s33, (&w85), s49, w);
  w85 *= w39;
  w91 -= w85;
    project(w71, s33, (&w85), s49, w);
  w85 *= w50;
    project(w64, s33, (&w50), s49, w);
  w50 *= w79;
  w85 -= w50;
  rr=w41;
  *rr++ = w44;
  *rr++ = w91;
  *rr++ = w85;
  trans(w41, s50, w55, s48, iw);
  fill(w17, 24, 0.);
  mtimes(w63, s2, w55, s48, w17, s35, w, 0);
  fill(w55, 3, 0.);
  for (i=0, rr=w55; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w66+i*8; k<8; ++k) *rr += ss[k*3]**tt++;
  fill(w41, 3, 0.);
  for (i=0, rr=w41; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w62+j, tt=w55+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  fill(w55, 3, 0.);
  for (i=0, rr=w55; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w87+j, tt=w41+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  rr=w56;
  for (i=0, cs=w21; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w55; i<3; ++i) *rr++ = *cs++;
  for (rr=w61, ss=w56+0; ss!=w56+6; ss+=1) *rr++ = *ss;
  for (rr=w113+5, ss=w61; rr!=w113+53; rr+=8) *rr = *ss++;
  w49 = (1./ w49 );
  for (i=0, rr=w46, cs=w46; i<3; ++i) (*rr++)  = (w49*(*cs++));
  rr=w21;
  for (i=0, cs=w46; i<3; ++i) *rr++ = *cs++;
  fill(w55, 3, 0.);
  mtimes(w21, s51, w0, s30, w55, s3, w, 0);
  for (i=0, rr=w55, cs=w55; i<3; ++i) (*rr++)  = (w58*(*cs++));
  for (i=0, rr=w55, cs=w55; i<3; ++i) *rr++ = (- *cs++ );
  fill(w21, 3, 0.);
  for (i=0, rr=w21; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w60+j, tt=w55+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
    project(w64, s33, (&w49), s52, w);
  for (rr=(&w44), ss=w46+2; ss!=w46+3; ss+=1) *rr++ = *ss;
  w49 *= w44;
    project(w67, s33, (&w91), s52, w);
  for (rr=(&w85), ss=w46+1; ss!=w46+2; ss+=1) *rr++ = *ss;
  w91 *= w85;
  w49 -= w91;
    project(w67, s33, (&w91), s52, w);
  for (rr=(&w50), ss=w46+0; ss!=w46+1; ss+=1) *rr++ = *ss;
  w91 *= w50;
    project(w71, s33, (&w79), s52, w);
  w79 *= w44;
  w91 -= w79;
    project(w71, s33, (&w79), s52, w);
  w79 *= w85;
    project(w64, s33, (&w85), s52, w);
  w85 *= w50;
  w79 -= w85;
  rr=w46;
  *rr++ = w49;
  *rr++ = w91;
  *rr++ = w79;
  trans(w46, s53, w55, s51, iw);
  fill(w17, 24, 0.);
  mtimes(w63, s2, w55, s51, w17, s35, w, 0);
  fill(w55, 3, 0.);
  for (i=0, rr=w55; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w66+i*8; k<8; ++k) *rr += ss[k*3]**tt++;
  fill(w46, 3, 0.);
  for (i=0, rr=w46; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w62+j, tt=w55+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  fill(w55, 3, 0.);
  for (i=0, rr=w55; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w87+j, tt=w46+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  rr=w61;
  for (i=0, cs=w21; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w55; i<3; ++i) *rr++ = *cs++;
  for (rr=w56, ss=w61+0; ss!=w61+6; ss+=1) *rr++ = *ss;
  for (rr=w113+6, ss=w56; rr!=w113+54; rr+=8) *rr = *ss++;
  w54 = (1./ w54 );
  for (i=0, rr=w51, cs=w51; i<3; ++i) (*rr++)  = (w54*(*cs++));
  rr=w21;
  for (i=0, cs=w51; i<3; ++i) *rr++ = *cs++;
  fill(w55, 3, 0.);
  mtimes(w21, s54, w0, s30, w55, s3, w, 0);
  for (i=0, rr=w55, cs=w55; i<3; ++i) (*rr++)  = (w58*(*cs++));
  for (i=0, rr=w55, cs=w55; i<3; ++i) *rr++ = (- *cs++ );
  fill(w21, 3, 0.);
  for (i=0, rr=w21; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w60+j, tt=w55+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
    project(w64, s33, (&w58), s55, w);
  for (rr=(&w54), ss=w51+2; ss!=w51+3; ss+=1) *rr++ = *ss;
  w58 *= w54;
    project(w67, s33, (&w49), s55, w);
  for (rr=(&w91), ss=w51+1; ss!=w51+2; ss+=1) *rr++ = *ss;
  w49 *= w91;
  w58 -= w49;
    project(w67, s33, (&w49), s55, w);
  for (rr=(&w79), ss=w51+0; ss!=w51+1; ss+=1) *rr++ = *ss;
  w49 *= w79;
    project(w71, s33, (&w85), s55, w);
  w85 *= w54;
  w49 -= w85;
    project(w71, s33, (&w85), s55, w);
  w85 *= w91;
    project(w64, s33, (&w91), s55, w);
  w91 *= w79;
  w85 -= w91;
  rr=w51;
  *rr++ = w58;
  *rr++ = w49;
  *rr++ = w85;
  trans(w51, s56, w55, s54, iw);
  fill(w17, 24, 0.);
  mtimes(w63, s2, w55, s54, w17, s35, w, 0);
  fill(w55, 3, 0.);
  for (i=0, rr=w55; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w66+i*8; k<8; ++k) *rr += ss[k*3]**tt++;
  fill(w51, 3, 0.);
  for (i=0, rr=w51; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w62+j, tt=w55+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  fill(w55, 3, 0.);
  for (i=0, rr=w55; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w87+j, tt=w51+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  rr=w56;
  for (i=0, cs=w21; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w55; i<3; ++i) *rr++ = *cs++;
  for (rr=w61, ss=w56+0; ss!=w56+6; ss+=1) *rr++ = *ss;
  for (rr=w113+7, ss=w61; rr!=w113+55; rr+=8) *rr = *ss++;
  trans(w113, s58, w114, s57, iw);
    project(w114, s57, w115, s59, w);
  if (res[2]) copy(w115, 72, res[2]);
  return 0;
}

void cablerobot_output_incref(void) {
}

void cablerobot_output_decref(void) {
}

int cablerobot_output_n_in(void) { return 3;}

int cablerobot_output_n_out(void) { return 3;}

const char* cablerobot_output_name_in(int i){
  switch (i) {
  case 0: return "i0";
  case 1: return "i1";
  case 2: return "i2";
  default: return 0;
  }
}

const char* cablerobot_output_name_out(int i){
  switch (i) {
  case 0: return "o0";
  case 1: return "o1";
  case 2: return "o2";
  default: return 0;
  }
}

const int* cablerobot_output_sparsity_in(int i) {
  switch (i) {
  case 0: return s60;
  case 1: return s30;
  case 2: return s60;
  default: return 0;
  }
}

const int* cablerobot_output_sparsity_out(int i) {
  switch (i) {
  case 0: return s61;
  case 1: return s29;
  case 2: return s59;
  default: return 0;
  }
}

int cablerobot_output_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 11;
  if (sz_res) *sz_res = 7;
  if (sz_iw) *sz_iw = 14;
  if (sz_w) *sz_w = 899;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
