/* This function was automatically generated by CasADi */
#ifdef __cplusplus
extern "C" {
#endif

#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else /* CODEGEN_PREFIX */
  #define CASADI_PREFIX(ID) cablerobot_ode_ ## ID
#endif /* CODEGEN_PREFIX */

#include <math.h>

#ifndef real_t
#define real_t double
#define to_double(x) (double) x
#define to_int(x) (int) x
#endif /* real_t */

/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
real_t CASADI_PREFIX(fmin)(real_t x, real_t y) { return x<y ? x : y;}
#define fmin(x,y) CASADI_PREFIX(fmin)(x,y)
real_t CASADI_PREFIX(fmax)(real_t x, real_t y) { return x>y ? x : y;}
#define fmax(x,y) CASADI_PREFIX(fmax)(x,y)
#endif

#define PRINTF printf
real_t CASADI_PREFIX(sq)(real_t x) { return x*x;}
#define sq(x) CASADI_PREFIX(sq)(x)

real_t CASADI_PREFIX(sign)(real_t x) { return x<0 ? -1 : x>0 ? 1 : x;}
#define sign(x) CASADI_PREFIX(sign)(x)

void CASADI_PREFIX(fill)(real_t* x, int n, real_t alpha) {
  int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}
#define fill(x, n, alpha) CASADI_PREFIX(fill)(x, n, alpha)


void CASADI_PREFIX(copy)(const real_t* x, int n, real_t* y) {
  int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}
#define copy(x, n, y) CASADI_PREFIX(copy)(x, n, y)


void CASADI_PREFIX(trans)(const real_t* x, const int* sp_x, real_t* y, const int* sp_y, int *tmp) {
  int ncol_x = sp_x[1];
  int nnz_x = sp_x[2 + ncol_x];
  const int* row_x = sp_x + 2 + ncol_x+1;
  int ncol_y = sp_y[1];
  const int* colind_y = sp_y+2;
  int k;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}
#define trans(x, sp_x, y, sp_y, tmp) CASADI_PREFIX(trans)(x, sp_x, y, sp_y, tmp)

void CASADI_PREFIX(mtimes)(const real_t* x, const int* sp_x, const real_t* y, const int* sp_y, real_t* z, const int* sp_z, real_t* w, int tr) {
  /* Get sparsities */
  int ncol_x = sp_x[1];
  const int *colind_x = sp_x+2, *row_x = sp_x + 2 + ncol_x+1;
  int ncol_y = sp_y[1];
  const int *colind_y = sp_y+2, *row_y = sp_y + 2 + ncol_y+1;
  int ncol_z = sp_z[1];
  const int *colind_z = sp_z+2, *row_z = sp_z + 2 + ncol_z+1;
  int cc,kk, kk1;
  if (tr) {
    /* Loop over the columns of y and z */
    for (cc=0; cc<ncol_z; ++cc) {
      /* Get the dense column of y */
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      /* Loop over the nonzeros of z */
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        int rr = row_z[kk];
        /* Loop over corresponding columns of x */
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    /* Loop over the columns of y and z */
    for (cc=0; cc<ncol_y; ++cc) {
      /* Get the dense column of z */
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      /* Loop over the nonzeros of y */
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        int rr = row_y[kk];
        /* Loop over corresponding columns of x */
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      /* Get the sparse column of z */
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}
#define mtimes(x, sp_x, y, sp_y, z, sp_z, w, tr) CASADI_PREFIX(mtimes)(x, sp_x, y, sp_y, z, sp_z, w, tr)

real_t CASADI_PREFIX(dot)(int n, const real_t* x, const real_t* y) {
  real_t r = 0;
  int i;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}
#define dot(n, x, y) CASADI_PREFIX(dot)(n, x, y)


void CASADI_PREFIX(project)(const real_t* x, const int* sp_x, real_t* y, const int* sp_y, real_t* w) {
  int ncol_x = sp_x[1];
  const int *colind_x = sp_x+2, *row_x = sp_x + 2 + ncol_x+1;
  int ncol_y = sp_y[1];
  const int *colind_y = sp_y+2, *row_y = sp_y + 2 + ncol_y+1;
  /* Loop over columns of x and y */
  int i, el;
  for (i=0; i<ncol_x; ++i) {
    /* Zero out requested entries in y */
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) w[row_y[el]] = 0;
    /* Set x entries */
    for (el=colind_x[i]; el<colind_x[i+1]; ++el) w[row_x[el]] = x[el];
    /* Retrieve requested entries in y */
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) y[el] = w[row_y[el]];
  }
}
#define project(x, sp_x, y, sp_y, w) CASADI_PREFIX(project)(x, sp_x, y, sp_y, w)


static const int CASADI_PREFIX(s0)[] = {3, 3, 0, 3, 5, 6, 0, 1, 2, 1, 2, 2};
#define s0 CASADI_PREFIX(s0)
static const int CASADI_PREFIX(s1)[] = {3, 3, 0, 1, 3, 6, 0, 0, 1, 0, 1, 2};
#define s1 CASADI_PREFIX(s1)
static const int CASADI_PREFIX(s2)[] = {3, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};
#define s2 CASADI_PREFIX(s2)
static const int CASADI_PREFIX(s3)[] = {3, 1, 0, 3, 0, 1, 2};
#define s3 CASADI_PREFIX(s3)
static const int CASADI_PREFIX(s4)[] = {3, 1, 0, 1, 0};
#define s4 CASADI_PREFIX(s4)
static const int CASADI_PREFIX(s5)[] = {4, 1, 0, 4, 0, 1, 2, 3};
#define s5 CASADI_PREFIX(s5)
static const int CASADI_PREFIX(s6)[] = {4, 3, 0, 4, 8, 12, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
#define s6 CASADI_PREFIX(s6)
static const int CASADI_PREFIX(s7)[] = {0, 10, 20, 30, 36, 42, 48, 75, 76, 77};
#define s7 CASADI_PREFIX(s7)
static const int CASADI_PREFIX(s8)[] = {3, 1, 0, 1, 1};
#define s8 CASADI_PREFIX(s8)
static const int CASADI_PREFIX(s9)[] = {1, 11, 21, 31, 37, 43, 49};
#define s9 CASADI_PREFIX(s9)
static const int CASADI_PREFIX(s10)[] = {3, 1, 0, 1, 2};
#define s10 CASADI_PREFIX(s10)
static const int CASADI_PREFIX(s11)[] = {2, 12, 22, 32, 38, 44, 50};
#define s11 CASADI_PREFIX(s11)
static const int CASADI_PREFIX(s12)[] = {4, 3, 0, 1, 2, 3, 1, 2, 3};
#define s12 CASADI_PREFIX(s12)
static const int CASADI_PREFIX(s13)[] = {3, 4, 0, 3, 6, 9, 12, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2};
#define s13 CASADI_PREFIX(s13)
static const int CASADI_PREFIX(s14)[] = {3, 4, 0, 0, 1, 2, 3, 0, 1, 2};
#define s14 CASADI_PREFIX(s14)
static const int CASADI_PREFIX(s15)[] = {0, 1, 2, 4, 5, 6, 7, 8, 9};
#define s15 CASADI_PREFIX(s15)
static const int CASADI_PREFIX(s16)[] = {3, 13, 23, 39, 45, 51, 54, 61, 68};
#define s16 CASADI_PREFIX(s16)
static const int CASADI_PREFIX(s17)[] = {4, 3, 0, 1, 2, 3, 0, 3, 2};
#define s17 CASADI_PREFIX(s17)
static const int CASADI_PREFIX(s18)[] = {3, 4, 0, 1, 1, 2, 3, 0, 2, 1};
#define s18 CASADI_PREFIX(s18)
static const int CASADI_PREFIX(s19)[] = {0, 1, 2, 3, 5, 6, 7, 8, 9};
#define s19 CASADI_PREFIX(s19)
static const int CASADI_PREFIX(s20)[] = {4, 14, 24, 33, 46, 52, 55, 62, 69};
#define s20 CASADI_PREFIX(s20)
static const int CASADI_PREFIX(s21)[] = {4, 3, 0, 1, 2, 3, 3, 0, 1};
#define s21 CASADI_PREFIX(s21)
static const int CASADI_PREFIX(s22)[] = {3, 4, 0, 1, 2, 2, 3, 1, 2, 0};
#define s22 CASADI_PREFIX(s22)
static const int CASADI_PREFIX(s23)[] = {0, 1, 2, 3, 4, 6, 7, 8, 9};
#define s23 CASADI_PREFIX(s23)
static const int CASADI_PREFIX(s24)[] = {5, 15, 25, 34, 40, 53, 56, 63, 70};
#define s24 CASADI_PREFIX(s24)
static const int CASADI_PREFIX(s25)[] = {4, 3, 0, 1, 2, 3, 2, 1, 0};
#define s25 CASADI_PREFIX(s25)
static const int CASADI_PREFIX(s26)[] = {3, 4, 0, 1, 2, 3, 3, 2, 1, 0};
#define s26 CASADI_PREFIX(s26)
static const int CASADI_PREFIX(s27)[] = {0, 1, 2, 3, 4, 5, 7, 8, 9};
#define s27 CASADI_PREFIX(s27)
static const int CASADI_PREFIX(s28)[] = {6, 16, 26, 35, 41, 47, 57, 64, 71};
#define s28 CASADI_PREFIX(s28)
static const int CASADI_PREFIX(s29)[] = {7, 17, 27, 58, 65, 72};
#define s29 CASADI_PREFIX(s29)
static const int CASADI_PREFIX(s30)[] = {8, 18, 28, 59, 66, 73};
#define s30 CASADI_PREFIX(s30)
static const int CASADI_PREFIX(s31)[] = {9, 19, 29, 60, 67, 74};
#define s31 CASADI_PREFIX(s31)
static const int CASADI_PREFIX(s32)[] = {13, 13, 0, 7, 14, 21, 30, 39, 48, 57, 58, 59, 60, 66, 72, 78, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 7, 8, 9, 10, 11, 12, 0, 1, 2, 7, 8, 9, 0, 1, 2, 7, 8, 9, 0, 1, 2, 7, 8, 9};
#define s32 CASADI_PREFIX(s32)
static const int CASADI_PREFIX(s33)[] = {13, 13, 0, 10, 20, 30, 36, 42, 48, 54, 61, 68, 75, 76, 77, 78, 0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 0, 1, 2, 4, 5, 6, 0, 1, 2, 3, 5, 6, 0, 1, 2, 3, 4, 6, 0, 1, 2, 3, 4, 5, 3, 4, 5, 6, 10, 11, 12, 3, 4, 5, 6, 10, 11, 12, 3, 4, 5, 6, 10, 11, 12, 7, 8, 9};
#define s33 CASADI_PREFIX(s33)
static const int CASADI_PREFIX(s34)[] = {13, 13, 0, 13, 26, 39, 52, 65, 78, 91, 104, 117, 130, 143, 156, 169, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
#define s34 CASADI_PREFIX(s34)
static const int CASADI_PREFIX(s35)[] = {1, 8, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0};
#define s35 CASADI_PREFIX(s35)
static const int CASADI_PREFIX(s36)[] = {1, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 0, 0, 0, 0, 0, 0, 0};
#define s36 CASADI_PREFIX(s36)
static const int CASADI_PREFIX(s37)[] = {3, 8, 0, 3, 3, 3, 3, 3, 3, 3, 3, 0, 1, 2};
#define s37 CASADI_PREFIX(s37)
static const int CASADI_PREFIX(s38)[] = {8, 3, 0, 1, 2, 3, 0, 0, 0};
#define s38 CASADI_PREFIX(s38)
static const int CASADI_PREFIX(s39)[] = {3, 8, 0, 3, 6, 9, 12, 15, 18, 21, 24, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2};
#define s39 CASADI_PREFIX(s39)
static const int CASADI_PREFIX(s40)[] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
#define s40 CASADI_PREFIX(s40)
static const int CASADI_PREFIX(s41)[] = {1, 8, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0};
#define s41 CASADI_PREFIX(s41)
static const int CASADI_PREFIX(s42)[] = {3, 8, 0, 0, 3, 3, 3, 3, 3, 3, 3, 0, 1, 2};
#define s42 CASADI_PREFIX(s42)
static const int CASADI_PREFIX(s43)[] = {8, 3, 0, 1, 2, 3, 1, 1, 1};
#define s43 CASADI_PREFIX(s43)
static const int CASADI_PREFIX(s44)[] = {1, 8, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0};
#define s44 CASADI_PREFIX(s44)
static const int CASADI_PREFIX(s45)[] = {3, 8, 0, 0, 0, 3, 3, 3, 3, 3, 3, 0, 1, 2};
#define s45 CASADI_PREFIX(s45)
static const int CASADI_PREFIX(s46)[] = {8, 3, 0, 1, 2, 3, 2, 2, 2};
#define s46 CASADI_PREFIX(s46)
static const int CASADI_PREFIX(s47)[] = {1, 8, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0};
#define s47 CASADI_PREFIX(s47)
static const int CASADI_PREFIX(s48)[] = {3, 8, 0, 0, 0, 0, 3, 3, 3, 3, 3, 0, 1, 2};
#define s48 CASADI_PREFIX(s48)
static const int CASADI_PREFIX(s49)[] = {8, 3, 0, 1, 2, 3, 3, 3, 3};
#define s49 CASADI_PREFIX(s49)
static const int CASADI_PREFIX(s50)[] = {1, 8, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0};
#define s50 CASADI_PREFIX(s50)
static const int CASADI_PREFIX(s51)[] = {3, 8, 0, 0, 0, 0, 0, 3, 3, 3, 3, 0, 1, 2};
#define s51 CASADI_PREFIX(s51)
static const int CASADI_PREFIX(s52)[] = {8, 3, 0, 1, 2, 3, 4, 4, 4};
#define s52 CASADI_PREFIX(s52)
static const int CASADI_PREFIX(s53)[] = {1, 8, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0};
#define s53 CASADI_PREFIX(s53)
static const int CASADI_PREFIX(s54)[] = {3, 8, 0, 0, 0, 0, 0, 0, 3, 3, 3, 0, 1, 2};
#define s54 CASADI_PREFIX(s54)
static const int CASADI_PREFIX(s55)[] = {8, 3, 0, 1, 2, 3, 5, 5, 5};
#define s55 CASADI_PREFIX(s55)
static const int CASADI_PREFIX(s56)[] = {1, 8, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0};
#define s56 CASADI_PREFIX(s56)
static const int CASADI_PREFIX(s57)[] = {3, 8, 0, 0, 0, 0, 0, 0, 0, 3, 3, 0, 1, 2};
#define s57 CASADI_PREFIX(s57)
static const int CASADI_PREFIX(s58)[] = {8, 3, 0, 1, 2, 3, 6, 6, 6};
#define s58 CASADI_PREFIX(s58)
static const int CASADI_PREFIX(s59)[] = {1, 8, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0};
#define s59 CASADI_PREFIX(s59)
static const int CASADI_PREFIX(s60)[] = {3, 8, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 1, 2};
#define s60 CASADI_PREFIX(s60)
static const int CASADI_PREFIX(s61)[] = {8, 3, 0, 1, 2, 3, 7, 7, 7};
#define s61 CASADI_PREFIX(s61)
static const int CASADI_PREFIX(s62)[] = {13, 8, 0, 6, 12, 18, 24, 30, 36, 42, 48, 0, 1, 2, 7, 8, 9, 0, 1, 2, 7, 8, 9, 0, 1, 2, 7, 8, 9, 0, 1, 2, 7, 8, 9, 0, 1, 2, 7, 8, 9, 0, 1, 2, 7, 8, 9, 0, 1, 2, 7, 8, 9, 0, 1, 2, 7, 8, 9};
#define s62 CASADI_PREFIX(s62)
static const int CASADI_PREFIX(s63)[] = {8, 13, 0, 8, 16, 24, 24, 24, 24, 24, 32, 40, 48, 48, 48, 48, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7};
#define s63 CASADI_PREFIX(s63)
static const int CASADI_PREFIX(s64)[] = {13, 8, 0, 13, 26, 39, 52, 65, 78, 91, 104, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
#define s64 CASADI_PREFIX(s64)
static const int CASADI_PREFIX(s65)[] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
#define s65 CASADI_PREFIX(s65)
static const real_t CASADI_PREFIX(c0)[] = {-1.3830000000000000e+00, 5.2800000000000002e-01, -7.4700000000000000e-01, -7.9900000000000004e-01, 1.2447999999999999e+00, 7.4570000000000003e-01, 1.4535000000000000e+00, 3.6969999999999997e-01, -7.4819999999999998e-01, 9.5389999999999997e-01, 1.1471000000000000e+00, 7.4500000000000000e-01, 8.1869999999999998e-01, -1.2676000000000001e+00, -7.4650000000000005e-01, 1.4027000000000001e+00, -5.5069999999999997e-01, 7.4639999999999995e-01, -9.3459999999999999e-01, -1.1698000000000000e+00, -7.4580000000000002e-01, -1.4341999999999999e+00, -3.9250000000000002e-01, 7.4750000000000005e-01};
#define c0 CASADI_PREFIX(c0)
static const real_t CASADI_PREFIX(c1)[] = {-5.2469999999999999e+00, 7.8650000000000002e+00, 6.2619999999999996e+00, -5.2460000000000004e+00, 7.8529999999999998e+00, -1.0349999999999999e+00, 5.2630000000000008e+00, 7.5809999999999995e+00, 6.3090000000000002e+00, 5.2670000000000003e+00, 7.5679999999999996e+00, -4.8599999999999999e-01, 5.1399999999999997e+00, -6.4150000000000000e+00, 6.3380000000000001e+00, 5.1480000000000006e+00, -6.4299999999999997e+00, -4.5799999999999996e-01, -5.6379999999999999e+00, -6.5030000000000001e+00, 6.3259999999999996e+00, -5.6360000000000001e+00, -6.5169999999999995e+00, -9.6899999999999986e-01};
#define c1 CASADI_PREFIX(c1)
static const real_t CASADI_PREFIX(c2)[] = {0., 0., -9.8100000000000005e+00};
#define c2 CASADI_PREFIX(c2)
/* cablerobot_ode */
int cablerobot_ode(const real_t** arg, real_t** res, int* iw, real_t* w, int mem) {
  int i, j, k, *ii, *jj, *kk;
  const int *cii;
  real_t r, s, t, *rr, *ss, *tt;
  const real_t *cr, *cs, *ct;
  const real_t** arg1=arg+3;
  real_t** res1=res+3;
  real_t *w0=w+13, *w1=w+26, *w2=w+32, w3, *w4=w+39, *w5=w+45, *w6=w+54, *w7=w+57, *w8=w+61, *w9=w+64, w10, w11, w12, w13, *w14=w+71, *w15=w+75, *w16=w+79, *w17=w+83, *w18=w+95, *w19=w+107, *w20=w+119, *w21=w+128, *w22=w+137, *w23=w+161, *w24=w+185, *w25=w+193, *w26=w+201, *w27=w+225, *w28=w+249, *w29=w+252, *w30=w+255, *w31=w+258, *w32=w+261, w33, *w34=w+265, *w35=w+268, *w36=w+271, w37, w38, *w39=w+276, *w40=w+279, *w41=w+282, w42, w43, *w44=w+287, *w45=w+290, *w46=w+293, w47, w48, *w49=w+298, *w50=w+301, *w51=w+304, w52, w53, *w54=w+309, *w55=w+312, *w56=w+315, w57, w58, *w59=w+320, *w60=w+323, *w61=w+326, w62, *w63=w+330, *w64=w+338, *w65=w+346, *w66=w+354, *w67=w+362, *w68=w+370, *w69=w+378, *w70=w+386, *w71=w+394, w72, *w73=w+398, w74, w75, w76, w77, w78, w79, w80, w81, w82, *w83=w+410, w84, w85, w86, w87, *w89=w+417, *w90=w+427, *w91=w+437, *w93=w+515, *w94=w+522, *w96=w+529, *w97=w+538, *w98=w+541, *w99=w+544, *w100=w+547, *w101=w+550, *w102=w+553, *w103=w+561, *w104=w+569, *w105=w+577, *w106=w+585, *w107=w+593, *w108=w+601, w109, *w110=w+626, *w111=w+704, *w116=w+873, *w117=w+921, *w118=w+969;
  if (arg[2])
    copy(arg[2], 13, w0);
  else 
    fill(w0, 13, 0);
  copy(w0, 6, w1);
  copy(w0+6, 6, w2);
  w3 = w0[12];
  for (rr=w4, ss=w2+0; ss!=w2+6; ss+=1) *rr++ = *ss;
  trans(w4, s1, w2, s0, iw);
  fill(w5, 9, 0.);
  mtimes(w4, s1, w2, s0, w5, s2, w, 0);
  if (arg[0])
    copy(arg[0], 13, w0);
  else 
    fill(w0, 13, 0);
  copy(w0, 3, w6);
  copy(w0+3, 4, w7);
  copy(w0+7, 3, w8);
  copy(w0+10, 3, w9);
  for (rr=(&w10), ss=w7+1; ss!=w7+2; ss+=1) *rr++ = *ss;
  w10 = (- w10 );
  for (rr=(&w11), ss=w7+0; ss!=w7+1; ss+=1) *rr++ = *ss;
  for (rr=(&w12), ss=w7+3; ss!=w7+4; ss+=1) *rr++ = *ss;
  for (rr=(&w13), ss=w7+2; ss!=w7+3; ss+=1) *rr++ = *ss;
  w13 = (- w13 );
  rr=w14;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  for (rr=(&w10), ss=w7+2; ss!=w7+3; ss+=1) *rr++ = *ss;
  w10 = (- w10 );
  for (rr=(&w11), ss=w7+3; ss!=w7+4; ss+=1) *rr++ = *ss;
  w11 = (- w11 );
  for (rr=(&w12), ss=w7+0; ss!=w7+1; ss+=1) *rr++ = *ss;
  for (rr=(&w13), ss=w7+1; ss!=w7+2; ss+=1) *rr++ = *ss;
  rr=w15;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  for (rr=(&w10), ss=w7+3; ss!=w7+4; ss+=1) *rr++ = *ss;
  w10 = (- w10 );
  for (rr=(&w11), ss=w7+2; ss!=w7+3; ss+=1) *rr++ = *ss;
  for (rr=(&w12), ss=w7+1; ss!=w7+2; ss+=1) *rr++ = *ss;
  w12 = (- w12 );
  for (rr=(&w13), ss=w7+0; ss!=w7+1; ss+=1) *rr++ = *ss;
  rr=w16;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  rr=w17;
  for (i=0, cs=w14; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<4; ++i) *rr++ = *cs++;
  for (rr=(&w10), ss=w7+1; ss!=w7+2; ss+=1) *rr++ = *ss;
  w10 = (- w10 );
  for (rr=(&w11), ss=w7+0; ss!=w7+1; ss+=1) *rr++ = *ss;
  for (rr=(&w12), ss=w7+3; ss!=w7+4; ss+=1) *rr++ = *ss;
  w12 = (- w12 );
  for (rr=(&w13), ss=w7+2; ss!=w7+3; ss+=1) *rr++ = *ss;
  rr=w14;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  for (rr=(&w10), ss=w7+2; ss!=w7+3; ss+=1) *rr++ = *ss;
  w10 = (- w10 );
  for (rr=(&w11), ss=w7+3; ss!=w7+4; ss+=1) *rr++ = *ss;
  for (rr=(&w12), ss=w7+0; ss!=w7+1; ss+=1) *rr++ = *ss;
  for (rr=(&w13), ss=w7+1; ss!=w7+2; ss+=1) *rr++ = *ss;
  w13 = (- w13 );
  rr=w15;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  for (rr=(&w10), ss=w7+3; ss!=w7+4; ss+=1) *rr++ = *ss;
  w10 = (- w10 );
  for (rr=(&w11), ss=w7+2; ss!=w7+3; ss+=1) *rr++ = *ss;
  w11 = (- w11 );
  for (rr=(&w12), ss=w7+1; ss!=w7+2; ss+=1) *rr++ = *ss;
  for (rr=(&w13), ss=w7+0; ss!=w7+1; ss+=1) *rr++ = *ss;
  rr=w16;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  rr=w18;
  for (i=0, cs=w14; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<4; ++i) *rr++ = *cs++;
  for (i=0, rr=w19, cs=w18; i<3; ++i) for (j=0; j<4; ++j) rr[i+j*3] = *cs++;
  fill(w20, 9, 0.);
  for (i=0, rr=w20; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w19+j, tt=w17+i*4; k<4; ++k) *rr += ss[k*3]**tt++;
  for (i=0, rr=w21, cs=w20; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  fill(w22, 24, 0.);
  copy(c0, 24, w23);
  for (i=0, rr=w22; i<8; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w20+j, tt=w23+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  for (rr=w24, ss=w22+1; ss!=w22+25; ss+=3) *rr++ = *ss;
  if (arg[1])
    copy(arg[1], 8, w25);
  else 
    fill(w25, 8, 0);
  for (rr=(&w10), ss=w25+0; ss!=w25+1; ss+=1) *rr++ = *ss;
  for (i=0;i<8;++i) {
    copy(w9, 3, w26+ i*3);
  }
  for (i=0, rr=w26, cr=w22, cs=w26; i<24; ++i) (*rr++)  = ((*cr++)+(*cs++));
  copy(c1, 24, w27);
  for (i=0, rr=w27, cs=w26; i<24; ++i) (*rr++) -= (*cs++);
  for (rr=w9, ss=w27+0; ss!=w27+3; ss+=1) *rr++ = *ss;
  for (i=0, rr=w28, cs=w9; i<3; ++i) (*rr++)  = (w10*(*cs++));
  for (rr=w29, ss=w27+0; ss!=w27+3; ss+=1) *rr++ = *ss;
  w11 = sqrt(dot(3, w29, w29));
  for (i=0, rr=w28; i<3; ++i) (*rr++) /= w11;
  for (rr=(&w12), ss=w25+1; ss!=w25+2; ss+=1) *rr++ = *ss;
  for (rr=w30, ss=w27+3; ss!=w27+6; ss+=1) *rr++ = *ss;
  for (i=0, rr=w31, cs=w30; i<3; ++i) (*rr++)  = (w12*(*cs++));
  for (rr=w32, ss=w27+3; ss!=w27+6; ss+=1) *rr++ = *ss;
  w13 = sqrt(dot(3, w32, w32));
  for (i=0, rr=w31; i<3; ++i) (*rr++) /= w13;
  for (rr=(&w33), ss=w25+2; ss!=w25+3; ss+=1) *rr++ = *ss;
  for (rr=w34, ss=w27+6; ss!=w27+9; ss+=1) *rr++ = *ss;
  for (i=0, rr=w35, cs=w34; i<3; ++i) (*rr++)  = (w33*(*cs++));
  for (rr=w36, ss=w27+6; ss!=w27+9; ss+=1) *rr++ = *ss;
  w37 = sqrt(dot(3, w36, w36));
  for (i=0, rr=w35; i<3; ++i) (*rr++) /= w37;
  for (rr=(&w38), ss=w25+3; ss!=w25+4; ss+=1) *rr++ = *ss;
  for (rr=w39, ss=w27+9; ss!=w27+12; ss+=1) *rr++ = *ss;
  for (i=0, rr=w40, cs=w39; i<3; ++i) (*rr++)  = (w38*(*cs++));
  for (rr=w41, ss=w27+9; ss!=w27+12; ss+=1) *rr++ = *ss;
  w42 = sqrt(dot(3, w41, w41));
  for (i=0, rr=w40; i<3; ++i) (*rr++) /= w42;
  for (rr=(&w43), ss=w25+4; ss!=w25+5; ss+=1) *rr++ = *ss;
  for (rr=w44, ss=w27+12; ss!=w27+15; ss+=1) *rr++ = *ss;
  for (i=0, rr=w45, cs=w44; i<3; ++i) (*rr++)  = (w43*(*cs++));
  for (rr=w46, ss=w27+12; ss!=w27+15; ss+=1) *rr++ = *ss;
  w47 = sqrt(dot(3, w46, w46));
  for (i=0, rr=w45; i<3; ++i) (*rr++) /= w47;
  for (rr=(&w48), ss=w25+5; ss!=w25+6; ss+=1) *rr++ = *ss;
  for (rr=w49, ss=w27+15; ss!=w27+18; ss+=1) *rr++ = *ss;
  for (i=0, rr=w50, cs=w49; i<3; ++i) (*rr++)  = (w48*(*cs++));
  for (rr=w51, ss=w27+15; ss!=w27+18; ss+=1) *rr++ = *ss;
  w52 = sqrt(dot(3, w51, w51));
  for (i=0, rr=w50; i<3; ++i) (*rr++) /= w52;
  for (rr=(&w53), ss=w25+6; ss!=w25+7; ss+=1) *rr++ = *ss;
  for (rr=w54, ss=w27+18; ss!=w27+21; ss+=1) *rr++ = *ss;
  for (i=0, rr=w55, cs=w54; i<3; ++i) (*rr++)  = (w53*(*cs++));
  for (rr=w56, ss=w27+18; ss!=w27+21; ss+=1) *rr++ = *ss;
  w57 = sqrt(dot(3, w56, w56));
  for (i=0, rr=w55; i<3; ++i) (*rr++) /= w57;
  for (rr=(&w58), ss=w25+7; ss!=w25+8; ss+=1) *rr++ = *ss;
  for (rr=w59, ss=w27+21; ss!=w27+24; ss+=1) *rr++ = *ss;
  for (i=0, rr=w60, cs=w59; i<3; ++i) (*rr++)  = (w58*(*cs++));
  for (rr=w61, ss=w27+21; ss!=w27+24; ss+=1) *rr++ = *ss;
  w62 = sqrt(dot(3, w61, w61));
  for (i=0, rr=w60; i<3; ++i) (*rr++) /= w62;
  rr=w27;
  for (i=0, cs=w28; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w31; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w35; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w40; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w45; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w50; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w55; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w60; i<3; ++i) *rr++ = *cs++;
  for (rr=w25, ss=w27+2; ss!=w27+26; ss+=3) *rr++ = *ss;
  for (i=0, rr=w63, cr=w24, cs=w25; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (rr=w64, ss=w22+2; ss!=w22+26; ss+=3) *rr++ = *ss;
  for (rr=w65, ss=w27+1; ss!=w27+25; ss+=3) *rr++ = *ss;
  for (i=0, rr=w66, cr=w64, cs=w65; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w63, cs=w66; i<8; ++i) (*rr++) -= (*cs++);
  for (rr=w66, ss=w27+0; ss!=w27+24; ss+=3) *rr++ = *ss;
  for (i=0, rr=w67, cr=w64, cs=w66; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (rr=w68, ss=w22+0; ss!=w22+24; ss+=3) *rr++ = *ss;
  for (i=0, rr=w69, cr=w68, cs=w25; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w67, cs=w69; i<8; ++i) (*rr++) -= (*cs++);
  for (i=0, rr=w69, cr=w68, cs=w65; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w70, cr=w24, cs=w66; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w69, cs=w70; i<8; ++i) (*rr++) -= (*cs++);
  rr=w22;
  for (i=0, cs=w63; i<8; ++i) *rr++ = *cs++;
  for (i=0, cs=w67; i<8; ++i) *rr++ = *cs++;
  for (i=0, cs=w69; i<8; ++i) *rr++ = *cs++;
  for (i=0, rr=w26, cs=w22; i<3; ++i) for (j=0; j<8; ++j) rr[i+j*3] = *cs++;
  fill(w22, 24, 0.);
  for (i=0, rr=w22; i<8; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w21+j, tt=w26+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  fill(w71, 3, 0.);
  fill(w63, 8, 1.);
  for (i=0, rr=w71; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w22+j, tt=w63+i*8; k<8; ++k) *rr += ss[k*3]**tt++;
  for (rr=(&w72), ss=w6+1; ss!=w6+2; ss+=1) *rr++ = *ss;
  for (rr=w4, ss=w1+0; ss!=w1+6; ss+=1) *rr++ = *ss;
  trans(w4, s1, w1, s0, iw);
  fill(w20, 9, 0.);
  mtimes(w1, s0, w4, s1, w20, s2, w, 0);
  fill(w73, 3, 0.);
  for (i=0, rr=w73; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w20+j, tt=w6+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  for (rr=(&w74), ss=w73+2; ss!=w73+3; ss+=1) *rr++ = *ss;
  w75  = (w72*w74);
  for (rr=(&w76), ss=w6+2; ss!=w6+3; ss+=1) *rr++ = *ss;
  for (rr=(&w77), ss=w73+1; ss!=w73+2; ss+=1) *rr++ = *ss;
  w78  = (w76*w77);
  w75 -= w78;
  for (rr=(&w78), ss=w73+0; ss!=w73+1; ss+=1) *rr++ = *ss;
  w79  = (w76*w78);
  for (rr=(&w80), ss=w6+0; ss!=w6+1; ss+=1) *rr++ = *ss;
  w81  = (w80*w74);
  w79 -= w81;
  w81  = (w80*w77);
  w82  = (w72*w78);
  w81 -= w82;
  rr=w73;
  *rr++ = w75;
  *rr++ = w79;
  *rr++ = w81;
  for (i=0, rr=w71, cs=w73; i<3; ++i) (*rr++) -= (*cs++);
  fill(w73, 3, 0.);
  for (i=0, rr=w73; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w5+j, tt=w71+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  for (rr=(&w75), ss=w7+1; ss!=w7+2; ss+=1) *rr++ = *ss;
  w75 = (- w75 );
  for (rr=(&w79), ss=w7+0; ss!=w7+1; ss+=1) *rr++ = *ss;
  for (rr=(&w81), ss=w7+3; ss!=w7+4; ss+=1) *rr++ = *ss;
  for (rr=(&w82), ss=w7+2; ss!=w7+3; ss+=1) *rr++ = *ss;
  w82 = (- w82 );
  rr=w14;
  *rr++ = w75;
  *rr++ = w79;
  *rr++ = w81;
  *rr++ = w82;
  for (rr=(&w75), ss=w7+2; ss!=w7+3; ss+=1) *rr++ = *ss;
  w75 = (- w75 );
  for (rr=(&w79), ss=w7+3; ss!=w7+4; ss+=1) *rr++ = *ss;
  w79 = (- w79 );
  for (rr=(&w81), ss=w7+0; ss!=w7+1; ss+=1) *rr++ = *ss;
  for (rr=(&w82), ss=w7+1; ss!=w7+2; ss+=1) *rr++ = *ss;
  rr=w15;
  *rr++ = w75;
  *rr++ = w79;
  *rr++ = w81;
  *rr++ = w82;
  for (rr=(&w75), ss=w7+3; ss!=w7+4; ss+=1) *rr++ = *ss;
  w75 = (- w75 );
  for (rr=(&w79), ss=w7+2; ss!=w7+3; ss+=1) *rr++ = *ss;
  for (rr=(&w81), ss=w7+1; ss!=w7+2; ss+=1) *rr++ = *ss;
  w81 = (- w81 );
  for (rr=(&w82), ss=w7+0; ss!=w7+1; ss+=1) *rr++ = *ss;
  rr=w7;
  *rr++ = w75;
  *rr++ = w79;
  *rr++ = w81;
  *rr++ = w82;
  rr=w18;
  for (i=0, cs=w14; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w7; i<4; ++i) *rr++ = *cs++;
  fill(w14, 4, 0.);
  for (i=0, rr=w14; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w18+j, tt=w6+i*3; k<3; ++k) *rr += ss[k*4]**tt++;
  w75 = 2.;
  for (i=0, rr=w14; i<4; ++i) (*rr++) /= w75;
  fill(w71, 3, 0.);
  fill(w67, 8, 1.);
  for (i=0, rr=w71; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w27+j, tt=w67+i*8; k<8; ++k) *rr += ss[k*3]**tt++;
  copy(c2, 3, w83);
  for (i=0, rr=w83; i<3; ++i) (*rr++) *= w3;
  for (i=0, rr=w71, cs=w83; i<3; ++i) (*rr++) += (*cs++);
  for (i=0, rr=w71; i<3; ++i) (*rr++) /= w3;
  rr=w0;
  for (i=0, cs=w73; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w71; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w8; i<3; ++i) *rr++ = *cs++;
  if (res[0]) copy(w0, 13, res[0]);
  fill(w14, 4, 1.);
  w75 = w14[0];
  copy(w14+1, 3, w73);
  fill(w71, 3, 0.);
  mtimes(w20, s2, (&w75), s4, w71, s3, w, 0);
  for (rr=(&w79), ss=w71+2; ss!=w71+3; ss+=1) *rr++ = *ss;
  w81  = (w72*w79);
  for (rr=(&w82), ss=w71+1; ss!=w71+2; ss+=1) *rr++ = *ss;
  w84  = (w76*w82);
  w81 -= w84;
  for (rr=(&w84), ss=w71+0; ss!=w71+1; ss+=1) *rr++ = *ss;
  w85  = (w76*w84);
  for (rr=(&w86), ss=(&w75)+0; ss!=(&w75)+1; ss+=1) *rr++ = *ss;
  w87  = (w74*w86);
  w79  = (w80*w79);
  w87 += w79;
  w85 -= w87;
  w86  = (w77*w86);
  w82  = (w80*w82);
  w86 += w82;
  w84  = (w72*w84);
  w86 -= w84;
  rr=w71;
  *rr++ = w81;
  *rr++ = w85;
  *rr++ = w86;
  for (i=0, rr=w71, cs=w71; i<3; ++i) *rr++ = (- *cs++ );
  fill(w8, 3, 0.);
  for (i=0, rr=w8; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w5+j, tt=w71+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  fill(w14, 4, 0.);
  mtimes(w18, s6, (&w75), s4, w14, s5, w, 0);
  w75 = 5.0000000000000000e-01;
  for (i=0, rr=w14, cs=w14; i<4; ++i) (*rr++)  = (w75*(*cs++));
  rr=w89;
  for (i=0, cs=w8; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w73; i<3; ++i) *rr++ = *cs++;
  for (rr=w90, ss=w89+0; ss!=w89+10; ss+=1) *rr++ = *ss;
  fill(w91, 78, 0.);
  for (cii=s7, rr=w91, ss=w90; cii!=s7+10; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  w81 = 1.;
  w85 = w81;
  for (rr=(&w81), ss=(&w85)+0; ss!=(&w85)+1; ss+=1) *rr++ = *ss;
  w74 *= w81;
  fill(w8, 3, 0.);
  mtimes(w20, s2, (&w85), s8, w8, s3, w, 0);
  for (rr=(&w86), ss=w8+2; ss!=w8+3; ss+=1) *rr++ = *ss;
  w84  = (w72*w86);
  w74 += w84;
  for (rr=(&w84), ss=w8+1; ss!=w8+2; ss+=1) *rr++ = *ss;
  w82  = (w76*w84);
  w74 -= w82;
  for (rr=(&w82), ss=w8+0; ss!=w8+1; ss+=1) *rr++ = *ss;
  w87  = (w76*w82);
  w86  = (w80*w86);
  w87 -= w86;
  w84  = (w80*w84);
  w81  = (w78*w81);
  w82  = (w72*w82);
  w81 += w82;
  w84 -= w81;
  rr=w8;
  *rr++ = w74;
  *rr++ = w87;
  *rr++ = w84;
  for (i=0, rr=w8, cs=w8; i<3; ++i) *rr++ = (- *cs++ );
  fill(w73, 3, 0.);
  for (i=0, rr=w73; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w5+j, tt=w8+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  fill(w14, 4, 0.);
  mtimes(w18, s6, (&w85), s8, w14, s5, w, 0);
  for (i=0, rr=w14, cs=w14; i<4; ++i) (*rr++)  = (w75*(*cs++));
  rr=w93;
  for (i=0, cs=w73; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<4; ++i) *rr++ = *cs++;
  for (rr=w94, ss=w93+0; ss!=w93+7; ss+=1) *rr++ = *ss;
  for (cii=s9, rr=w91, ss=w94; cii!=s9+7; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  w85 = 1.;
  w74 = w85;
  fill(w73, 3, 0.);
  mtimes(w20, s2, (&w74), s10, w73, s3, w, 0);
  for (rr=(&w85), ss=w73+2; ss!=w73+3; ss+=1) *rr++ = *ss;
  w87  = (w72*w85);
  for (rr=(&w84), ss=(&w74)+0; ss!=(&w74)+1; ss+=1) *rr++ = *ss;
  w77 *= w84;
  for (rr=(&w81), ss=w73+1; ss!=w73+2; ss+=1) *rr++ = *ss;
  w82  = (w76*w81);
  w77 += w82;
  w87 -= w77;
  w78 *= w84;
  for (rr=(&w84), ss=w73+0; ss!=w73+1; ss+=1) *rr++ = *ss;
  w76 *= w84;
  w78 += w76;
  w85  = (w80*w85);
  w78 -= w85;
  w80 *= w81;
  w72 *= w84;
  w80 -= w72;
  rr=w73;
  *rr++ = w87;
  *rr++ = w78;
  *rr++ = w80;
  for (i=0, rr=w73, cs=w73; i<3; ++i) *rr++ = (- *cs++ );
  fill(w8, 3, 0.);
  for (i=0, rr=w8; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w5+j, tt=w73+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  fill(w14, 4, 0.);
  mtimes(w18, s6, (&w74), s10, w14, s5, w, 0);
  for (i=0, rr=w14, cs=w14; i<4; ++i) (*rr++)  = (w75*(*cs++));
  rr=w94;
  for (i=0, cs=w8; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<4; ++i) *rr++ = *cs++;
  for (rr=w93, ss=w94+0; ss!=w94+7; ss+=1) *rr++ = *ss;
  for (cii=s11, rr=w91, ss=w93; cii!=s11+7; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  w74 = 1.;
  w87 = w74;
  for (rr=(&w74), ss=(&w87)+0; ss!=(&w87)+1; ss+=1) *rr++ = *ss;
  rr=(&w78);
  *rr++ = w74;
  for (rr=(&w74), ss=(&w87)+0; ss!=(&w87)+1; ss+=1) *rr++ = *ss;
  rr=(&w80);
  *rr++ = w74;
  for (rr=(&w74), ss=(&w87)+0; ss!=(&w87)+1; ss+=1) *rr++ = *ss;
  rr=(&w72);
  *rr++ = w74;
  rr=w8;
  *rr++ = w78;
  *rr++ = w80;
  *rr++ = w72;
  fill(w20, 9, 0.);
  mtimes(w19, s13, w8, s12, w20, s2, w, 0);
  for (rr=(&w78), ss=(&w87)+0; ss!=(&w87)+1; ss+=1) *rr++ = *ss;
  rr=(&w80);
  *rr++ = w78;
  for (rr=(&w78), ss=(&w87)+0; ss!=(&w87)+1; ss+=1) *rr++ = *ss;
  rr=(&w72);
  *rr++ = w78;
  for (rr=(&w78), ss=(&w87)+0; ss!=(&w87)+1; ss+=1) *rr++ = *ss;
  rr=(&w74);
  *rr++ = w78;
  rr=w8;
  *rr++ = w80;
  *rr++ = w72;
  *rr++ = w74;
  trans(w8, s12, w73, s14, iw);
  fill(w96, 9, 0.);
  mtimes(w73, s14, w17, s6, w96, s2, w, 0);
  for (i=0, rr=w20, cs=w96; i<9; ++i) (*rr++) += (*cs++);
  fill(w27, 24, 0.);
  for (i=0, rr=w27; i<8; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w20+j, tt=w23+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  for (rr=w69, ss=w27+1; ss!=w27+25; ss+=3) *rr++ = *ss;
  for (i=0, rr=w70, cr=w25, cs=w69; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w22, cs=w27; i<24; ++i) *rr++ = (- *cs++ );
  for (rr=w73, ss=w22+0; ss!=w22+3; ss+=1) *rr++ = *ss;
  for (i=0, rr=w73, cs=w73; i<3; ++i) (*rr++)  = (w10*(*cs++));
  w80 = (1./ w11 );
  for (i=0, rr=w73, cs=w73; i<3; ++i) (*rr++)  = (w80*(*cs++));
  for (i=0, rr=w28; i<3; ++i) (*rr++) /= w11;
  for (rr=w8, ss=w22+0; ss!=w22+3; ss+=1) *rr++ = *ss;
  w72 = dot(3, w29, w8);
  w72 /= w11;
  for (i=0, rr=w8, cr=w28; i<3; ++i) (*rr++)  = ((*cr++)*w72);
  for (i=0, rr=w73, cs=w8; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=w8, ss=w22+3; ss!=w22+6; ss+=1) *rr++ = *ss;
  for (i=0, rr=w8, cs=w8; i<3; ++i) (*rr++)  = (w12*(*cs++));
  w72 = (1./ w13 );
  for (i=0, rr=w8, cs=w8; i<3; ++i) (*rr++)  = (w72*(*cs++));
  for (i=0, rr=w31; i<3; ++i) (*rr++) /= w13;
  for (rr=w71, ss=w22+3; ss!=w22+6; ss+=1) *rr++ = *ss;
  w74 = dot(3, w32, w71);
  w74 /= w13;
  for (i=0, rr=w71, cr=w31; i<3; ++i) (*rr++)  = ((*cr++)*w74);
  for (i=0, rr=w8, cs=w71; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=w71, ss=w22+6; ss!=w22+9; ss+=1) *rr++ = *ss;
  for (i=0, rr=w71, cs=w71; i<3; ++i) (*rr++)  = (w33*(*cs++));
  w74 = (1./ w37 );
  for (i=0, rr=w71, cs=w71; i<3; ++i) (*rr++)  = (w74*(*cs++));
  for (i=0, rr=w35; i<3; ++i) (*rr++) /= w37;
  for (rr=w83, ss=w22+6; ss!=w22+9; ss+=1) *rr++ = *ss;
  w78 = dot(3, w36, w83);
  w78 /= w37;
  for (i=0, rr=w83, cr=w35; i<3; ++i) (*rr++)  = ((*cr++)*w78);
  for (i=0, rr=w71, cs=w83; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=w83, ss=w22+9; ss!=w22+12; ss+=1) *rr++ = *ss;
  for (i=0, rr=w83, cs=w83; i<3; ++i) (*rr++)  = (w38*(*cs++));
  w78 = (1./ w42 );
  for (i=0, rr=w83, cs=w83; i<3; ++i) (*rr++)  = (w78*(*cs++));
  for (i=0, rr=w40; i<3; ++i) (*rr++) /= w42;
  for (rr=w97, ss=w22+9; ss!=w22+12; ss+=1) *rr++ = *ss;
  w84 = dot(3, w41, w97);
  w84 /= w42;
  for (i=0, rr=w97, cr=w40; i<3; ++i) (*rr++)  = ((*cr++)*w84);
  for (i=0, rr=w83, cs=w97; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=w97, ss=w22+12; ss!=w22+15; ss+=1) *rr++ = *ss;
  for (i=0, rr=w97, cs=w97; i<3; ++i) (*rr++)  = (w43*(*cs++));
  w84 = (1./ w47 );
  for (i=0, rr=w97, cs=w97; i<3; ++i) (*rr++)  = (w84*(*cs++));
  for (i=0, rr=w45; i<3; ++i) (*rr++) /= w47;
  for (rr=w98, ss=w22+12; ss!=w22+15; ss+=1) *rr++ = *ss;
  w81 = dot(3, w46, w98);
  w81 /= w47;
  for (i=0, rr=w98, cr=w45; i<3; ++i) (*rr++)  = ((*cr++)*w81);
  for (i=0, rr=w97, cs=w98; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=w98, ss=w22+15; ss!=w22+18; ss+=1) *rr++ = *ss;
  for (i=0, rr=w98, cs=w98; i<3; ++i) (*rr++)  = (w48*(*cs++));
  w81 = (1./ w52 );
  for (i=0, rr=w98, cs=w98; i<3; ++i) (*rr++)  = (w81*(*cs++));
  for (i=0, rr=w50; i<3; ++i) (*rr++) /= w52;
  for (rr=w99, ss=w22+15; ss!=w22+18; ss+=1) *rr++ = *ss;
  w85 = dot(3, w51, w99);
  w85 /= w52;
  for (i=0, rr=w99, cr=w50; i<3; ++i) (*rr++)  = ((*cr++)*w85);
  for (i=0, rr=w98, cs=w99; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=w99, ss=w22+18; ss!=w22+21; ss+=1) *rr++ = *ss;
  for (i=0, rr=w99, cs=w99; i<3; ++i) (*rr++)  = (w53*(*cs++));
  w85 = (1./ w57 );
  for (i=0, rr=w99, cs=w99; i<3; ++i) (*rr++)  = (w85*(*cs++));
  for (i=0, rr=w55; i<3; ++i) (*rr++) /= w57;
  for (rr=w100, ss=w22+18; ss!=w22+21; ss+=1) *rr++ = *ss;
  w76 = dot(3, w56, w100);
  w76 /= w57;
  for (i=0, rr=w100, cr=w55; i<3; ++i) (*rr++)  = ((*cr++)*w76);
  for (i=0, rr=w99, cs=w100; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=w100, ss=w22+21; ss!=w22+24; ss+=1) *rr++ = *ss;
  for (i=0, rr=w100, cs=w100; i<3; ++i) (*rr++)  = (w58*(*cs++));
  w76 = (1./ w62 );
  for (i=0, rr=w100, cs=w100; i<3; ++i) (*rr++)  = (w76*(*cs++));
  for (i=0, rr=w60; i<3; ++i) (*rr++) /= w62;
  for (rr=w101, ss=w22+21; ss!=w22+24; ss+=1) *rr++ = *ss;
  w77 = dot(3, w61, w101);
  w77 /= w62;
  for (i=0, rr=w101, cr=w60; i<3; ++i) (*rr++)  = ((*cr++)*w77);
  for (i=0, rr=w100, cs=w101; i<3; ++i) (*rr++) -= (*cs++);
  rr=w22;
  for (i=0, cs=w73; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w8; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w71; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w83; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w97; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w98; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w99; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w100; i<3; ++i) *rr++ = *cs++;
  for (rr=w102, ss=w22+2; ss!=w22+26; ss+=3) *rr++ = *ss;
  for (i=0, rr=w103, cr=w24, cs=w102; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w70, cs=w103; i<8; ++i) (*rr++) += (*cs++);
  for (rr=w103, ss=w27+2; ss!=w27+26; ss+=3) *rr++ = *ss;
  for (i=0, rr=w104, cr=w65, cs=w103; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (rr=w105, ss=w22+1; ss!=w22+25; ss+=3) *rr++ = *ss;
  for (i=0, rr=w106, cr=w64, cs=w105; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w104, cs=w106; i<8; ++i) (*rr++) += (*cs++);
  for (i=0, rr=w70, cs=w104; i<8; ++i) (*rr++) -= (*cs++);
  for (i=0, rr=w103, cr=w66, cs=w103; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (rr=w104, ss=w22+0; ss!=w22+24; ss+=3) *rr++ = *ss;
  for (i=0, rr=w106, cr=w64, cs=w104; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w103, cs=w106; i<8; ++i) (*rr++) += (*cs++);
  for (rr=w106, ss=w27+0; ss!=w27+24; ss+=3) *rr++ = *ss;
  for (i=0, rr=w107, cr=w25, cs=w106; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w102, cr=w68, cs=w102; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w107, cs=w102; i<8; ++i) (*rr++) += (*cs++);
  for (i=0, rr=w103, cs=w107; i<8; ++i) (*rr++) -= (*cs++);
  for (i=0, rr=w106, cr=w65, cs=w106; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w105, cr=w68, cs=w105; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w106, cs=w105; i<8; ++i) (*rr++) += (*cs++);
  for (i=0, rr=w69, cr=w66, cs=w69; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w104, cr=w24, cs=w104; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w69, cs=w104; i<8; ++i) (*rr++) += (*cs++);
  for (i=0, rr=w106, cs=w69; i<8; ++i) (*rr++) -= (*cs++);
  rr=w27;
  for (i=0, cs=w70; i<8; ++i) *rr++ = *cs++;
  for (i=0, cs=w103; i<8; ++i) *rr++ = *cs++;
  for (i=0, cs=w106; i<8; ++i) *rr++ = *cs++;
  for (i=0, rr=w108, cs=w27; i<3; ++i) for (j=0; j<8; ++j) rr[i+j*3] = *cs++;
  fill(w27, 24, 0.);
  for (i=0, rr=w27; i<8; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w21+j, tt=w108+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  for (i=0, rr=w96, cs=w20; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  fill(w108, 24, 0.);
  for (i=0, rr=w108; i<8; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w96+j, tt=w26+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  for (i=0, rr=w27, cs=w108; i<24; ++i) (*rr++) += (*cs++);
  fill(w73, 3, 0.);
  for (i=0, rr=w73; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w27+j, tt=w63+i*8; k<8; ++k) *rr += ss[k*3]**tt++;
  fill(w8, 3, 0.);
  for (i=0, rr=w8; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w5+j, tt=w73+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  for (rr=(&w77), ss=(&w87)+0; ss!=(&w87)+1; ss+=1) *rr++ = *ss;
  rr=(&w82);
  *rr++ = w77;
  for (rr=(&w77), ss=(&w87)+0; ss!=(&w87)+1; ss+=1) *rr++ = *ss;
  rr=(&w86);
  *rr++ = w77;
  for (rr=(&w77), ss=(&w87)+0; ss!=(&w87)+1; ss+=1) *rr++ = *ss;
  rr=(&w87);
  *rr++ = w77;
  rr=w73;
  *rr++ = w82;
  *rr++ = w86;
  *rr++ = w87;
  fill(w14, 4, 0.);
  mtimes(w73, s12, w6, s3, w14, s5, w, 0);
  for (i=0, rr=w14, cs=w14; i<4; ++i) (*rr++)  = (w75*(*cs++));
  fill(w73, 3, 0.);
  for (i=0, rr=w73; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w22+j, tt=w67+i*8; k<8; ++k) *rr += ss[k*3]**tt++;
  w82 = (1./ w3 );
  for (i=0, rr=w73, cs=w73; i<3; ++i) (*rr++)  = (w82*(*cs++));
  rr=w90;
  for (i=0, cs=w8; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w73; i<3; ++i) *rr++ = *cs++;
  for (cii=s15, rr=w96, ss=w90; cii!=s15+9; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  for (cii=s16, rr=w91, ss=w96; cii!=s16+9; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  w86 = 1.;
  w87 = w86;
  for (rr=(&w86), ss=(&w87)+0; ss!=(&w87)+1; ss+=1) *rr++ = *ss;
  w86 = (- w86 );
  rr=(&w77);
  *rr++ = w86;
  for (rr=(&w86), ss=(&w87)+0; ss!=(&w87)+1; ss+=1) *rr++ = *ss;
  rr=(&w79);
  *rr++ = w86;
  for (rr=(&w86), ss=(&w87)+0; ss!=(&w87)+1; ss+=1) *rr++ = *ss;
  w86 = (- w86 );
  rr=(&w109);
  *rr++ = w86;
  rr=w8;
  *rr++ = w77;
  *rr++ = w79;
  *rr++ = w109;
  fill(w96, 9, 0.);
  mtimes(w19, s13, w8, s17, w96, s2, w, 0);
  for (rr=(&w77), ss=(&w87)+0; ss!=(&w87)+1; ss+=1) *rr++ = *ss;
  w77 = (- w77 );
  rr=(&w79);
  *rr++ = w77;
  for (rr=(&w77), ss=(&w87)+0; ss!=(&w87)+1; ss+=1) *rr++ = *ss;
  w77 = (- w77 );
  rr=(&w109);
  *rr++ = w77;
  for (rr=(&w77), ss=(&w87)+0; ss!=(&w87)+1; ss+=1) *rr++ = *ss;
  rr=(&w86);
  *rr++ = w77;
  rr=w8;
  *rr++ = w79;
  *rr++ = w109;
  *rr++ = w86;
  trans(w8, s17, w73, s18, iw);
  fill(w20, 9, 0.);
  mtimes(w73, s18, w17, s6, w20, s2, w, 0);
  for (i=0, rr=w96, cs=w20; i<9; ++i) (*rr++) += (*cs++);
  fill(w22, 24, 0.);
  for (i=0, rr=w22; i<8; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w96+j, tt=w23+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  for (rr=w70, ss=w22+1; ss!=w22+25; ss+=3) *rr++ = *ss;
  for (i=0, rr=w103, cr=w25, cs=w70; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w27, cs=w22; i<24; ++i) *rr++ = (- *cs++ );
  for (rr=w73, ss=w27+0; ss!=w27+3; ss+=1) *rr++ = *ss;
  for (i=0, rr=w73, cs=w73; i<3; ++i) (*rr++)  = (w10*(*cs++));
  for (i=0, rr=w73, cs=w73; i<3; ++i) (*rr++)  = (w80*(*cs++));
  for (rr=w8, ss=w27+0; ss!=w27+3; ss+=1) *rr++ = *ss;
  w79 = dot(3, w29, w8);
  w79 /= w11;
  for (i=0, rr=w8, cr=w28; i<3; ++i) (*rr++)  = ((*cr++)*w79);
  for (i=0, rr=w73, cs=w8; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=w8, ss=w27+3; ss!=w27+6; ss+=1) *rr++ = *ss;
  for (i=0, rr=w8, cs=w8; i<3; ++i) (*rr++)  = (w12*(*cs++));
  for (i=0, rr=w8, cs=w8; i<3; ++i) (*rr++)  = (w72*(*cs++));
  for (rr=w71, ss=w27+3; ss!=w27+6; ss+=1) *rr++ = *ss;
  w79 = dot(3, w32, w71);
  w79 /= w13;
  for (i=0, rr=w71, cr=w31; i<3; ++i) (*rr++)  = ((*cr++)*w79);
  for (i=0, rr=w8, cs=w71; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=w71, ss=w27+6; ss!=w27+9; ss+=1) *rr++ = *ss;
  for (i=0, rr=w71, cs=w71; i<3; ++i) (*rr++)  = (w33*(*cs++));
  for (i=0, rr=w71, cs=w71; i<3; ++i) (*rr++)  = (w74*(*cs++));
  for (rr=w83, ss=w27+6; ss!=w27+9; ss+=1) *rr++ = *ss;
  w79 = dot(3, w36, w83);
  w79 /= w37;
  for (i=0, rr=w83, cr=w35; i<3; ++i) (*rr++)  = ((*cr++)*w79);
  for (i=0, rr=w71, cs=w83; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=w83, ss=w27+9; ss!=w27+12; ss+=1) *rr++ = *ss;
  for (i=0, rr=w83, cs=w83; i<3; ++i) (*rr++)  = (w38*(*cs++));
  for (i=0, rr=w83, cs=w83; i<3; ++i) (*rr++)  = (w78*(*cs++));
  for (rr=w97, ss=w27+9; ss!=w27+12; ss+=1) *rr++ = *ss;
  w79 = dot(3, w41, w97);
  w79 /= w42;
  for (i=0, rr=w97, cr=w40; i<3; ++i) (*rr++)  = ((*cr++)*w79);
  for (i=0, rr=w83, cs=w97; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=w97, ss=w27+12; ss!=w27+15; ss+=1) *rr++ = *ss;
  for (i=0, rr=w97, cs=w97; i<3; ++i) (*rr++)  = (w43*(*cs++));
  for (i=0, rr=w97, cs=w97; i<3; ++i) (*rr++)  = (w84*(*cs++));
  for (rr=w98, ss=w27+12; ss!=w27+15; ss+=1) *rr++ = *ss;
  w79 = dot(3, w46, w98);
  w79 /= w47;
  for (i=0, rr=w98, cr=w45; i<3; ++i) (*rr++)  = ((*cr++)*w79);
  for (i=0, rr=w97, cs=w98; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=w98, ss=w27+15; ss!=w27+18; ss+=1) *rr++ = *ss;
  for (i=0, rr=w98, cs=w98; i<3; ++i) (*rr++)  = (w48*(*cs++));
  for (i=0, rr=w98, cs=w98; i<3; ++i) (*rr++)  = (w81*(*cs++));
  for (rr=w99, ss=w27+15; ss!=w27+18; ss+=1) *rr++ = *ss;
  w79 = dot(3, w51, w99);
  w79 /= w52;
  for (i=0, rr=w99, cr=w50; i<3; ++i) (*rr++)  = ((*cr++)*w79);
  for (i=0, rr=w98, cs=w99; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=w99, ss=w27+18; ss!=w27+21; ss+=1) *rr++ = *ss;
  for (i=0, rr=w99, cs=w99; i<3; ++i) (*rr++)  = (w53*(*cs++));
  for (i=0, rr=w99, cs=w99; i<3; ++i) (*rr++)  = (w85*(*cs++));
  for (rr=w100, ss=w27+18; ss!=w27+21; ss+=1) *rr++ = *ss;
  w79 = dot(3, w56, w100);
  w79 /= w57;
  for (i=0, rr=w100, cr=w55; i<3; ++i) (*rr++)  = ((*cr++)*w79);
  for (i=0, rr=w99, cs=w100; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=w100, ss=w27+21; ss!=w27+24; ss+=1) *rr++ = *ss;
  for (i=0, rr=w100, cs=w100; i<3; ++i) (*rr++)  = (w58*(*cs++));
  for (i=0, rr=w100, cs=w100; i<3; ++i) (*rr++)  = (w76*(*cs++));
  for (rr=w101, ss=w27+21; ss!=w27+24; ss+=1) *rr++ = *ss;
  w79 = dot(3, w61, w101);
  w79 /= w62;
  for (i=0, rr=w101, cr=w60; i<3; ++i) (*rr++)  = ((*cr++)*w79);
  for (i=0, rr=w100, cs=w101; i<3; ++i) (*rr++) -= (*cs++);
  rr=w27;
  for (i=0, cs=w73; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w8; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w71; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w83; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w97; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w98; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w99; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w100; i<3; ++i) *rr++ = *cs++;
  for (rr=w106, ss=w27+2; ss!=w27+26; ss+=3) *rr++ = *ss;
  for (i=0, rr=w69, cr=w24, cs=w106; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w103, cs=w69; i<8; ++i) (*rr++) += (*cs++);
  for (rr=w69, ss=w22+2; ss!=w22+26; ss+=3) *rr++ = *ss;
  for (i=0, rr=w104, cr=w65, cs=w69; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (rr=w105, ss=w27+1; ss!=w27+25; ss+=3) *rr++ = *ss;
  for (i=0, rr=w107, cr=w64, cs=w105; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w104, cs=w107; i<8; ++i) (*rr++) += (*cs++);
  for (i=0, rr=w103, cs=w104; i<8; ++i) (*rr++) -= (*cs++);
  for (i=0, rr=w69, cr=w66, cs=w69; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (rr=w104, ss=w27+0; ss!=w27+24; ss+=3) *rr++ = *ss;
  for (i=0, rr=w107, cr=w64, cs=w104; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w69, cs=w107; i<8; ++i) (*rr++) += (*cs++);
  for (rr=w107, ss=w22+0; ss!=w22+24; ss+=3) *rr++ = *ss;
  for (i=0, rr=w102, cr=w25, cs=w107; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w106, cr=w68, cs=w106; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w102, cs=w106; i<8; ++i) (*rr++) += (*cs++);
  for (i=0, rr=w69, cs=w102; i<8; ++i) (*rr++) -= (*cs++);
  for (i=0, rr=w107, cr=w65, cs=w107; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w105, cr=w68, cs=w105; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w107, cs=w105; i<8; ++i) (*rr++) += (*cs++);
  for (i=0, rr=w70, cr=w66, cs=w70; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w104, cr=w24, cs=w104; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w70, cs=w104; i<8; ++i) (*rr++) += (*cs++);
  for (i=0, rr=w107, cs=w70; i<8; ++i) (*rr++) -= (*cs++);
  rr=w22;
  for (i=0, cs=w103; i<8; ++i) *rr++ = *cs++;
  for (i=0, cs=w69; i<8; ++i) *rr++ = *cs++;
  for (i=0, cs=w107; i<8; ++i) *rr++ = *cs++;
  for (i=0, rr=w108, cs=w22; i<3; ++i) for (j=0; j<8; ++j) rr[i+j*3] = *cs++;
  fill(w22, 24, 0.);
  for (i=0, rr=w22; i<8; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w21+j, tt=w108+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  for (i=0, rr=w20, cs=w96; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  fill(w108, 24, 0.);
  for (i=0, rr=w108; i<8; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w20+j, tt=w26+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  for (i=0, rr=w22, cs=w108; i<24; ++i) (*rr++) += (*cs++);
  fill(w73, 3, 0.);
  for (i=0, rr=w73; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w22+j, tt=w63+i*8; k<8; ++k) *rr += ss[k*3]**tt++;
  fill(w8, 3, 0.);
  for (i=0, rr=w8; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w5+j, tt=w73+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  for (rr=(&w79), ss=(&w87)+0; ss!=(&w87)+1; ss+=1) *rr++ = *ss;
  w79 = (- w79 );
  rr=(&w109);
  *rr++ = w79;
  for (rr=(&w79), ss=(&w87)+0; ss!=(&w87)+1; ss+=1) *rr++ = *ss;
  rr=(&w86);
  *rr++ = w79;
  for (rr=(&w79), ss=(&w87)+0; ss!=(&w87)+1; ss+=1) *rr++ = *ss;
  w79 = (- w79 );
  rr=(&w87);
  *rr++ = w79;
  rr=w73;
  *rr++ = w109;
  *rr++ = w86;
  *rr++ = w87;
  fill(w14, 4, 0.);
  mtimes(w73, s17, w6, s3, w14, s5, w, 0);
  for (i=0, rr=w14, cs=w14; i<4; ++i) (*rr++)  = (w75*(*cs++));
  fill(w73, 3, 0.);
  for (i=0, rr=w73; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w27+j, tt=w67+i*8; k<8; ++k) *rr += ss[k*3]**tt++;
  for (i=0, rr=w73, cs=w73; i<3; ++i) (*rr++)  = (w82*(*cs++));
  rr=w90;
  for (i=0, cs=w8; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w73; i<3; ++i) *rr++ = *cs++;
  for (cii=s19, rr=w20, ss=w90; cii!=s19+9; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  for (cii=s20, rr=w91, ss=w20; cii!=s20+9; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  w109 = 1.;
  w86 = w109;
  for (rr=(&w109), ss=(&w86)+0; ss!=(&w86)+1; ss+=1) *rr++ = *ss;
  w109 = (- w109 );
  rr=(&w87);
  *rr++ = w109;
  for (rr=(&w109), ss=(&w86)+0; ss!=(&w86)+1; ss+=1) *rr++ = *ss;
  w109 = (- w109 );
  rr=(&w79);
  *rr++ = w109;
  for (rr=(&w109), ss=(&w86)+0; ss!=(&w86)+1; ss+=1) *rr++ = *ss;
  rr=(&w77);
  *rr++ = w109;
  rr=w8;
  *rr++ = w87;
  *rr++ = w79;
  *rr++ = w77;
  fill(w20, 9, 0.);
  mtimes(w19, s13, w8, s21, w20, s2, w, 0);
  for (rr=(&w87), ss=(&w86)+0; ss!=(&w86)+1; ss+=1) *rr++ = *ss;
  rr=(&w79);
  *rr++ = w87;
  for (rr=(&w87), ss=(&w86)+0; ss!=(&w86)+1; ss+=1) *rr++ = *ss;
  w87 = (- w87 );
  rr=(&w77);
  *rr++ = w87;
  for (rr=(&w87), ss=(&w86)+0; ss!=(&w86)+1; ss+=1) *rr++ = *ss;
  w87 = (- w87 );
  rr=(&w109);
  *rr++ = w87;
  rr=w8;
  *rr++ = w79;
  *rr++ = w77;
  *rr++ = w109;
  trans(w8, s21, w73, s22, iw);
  fill(w96, 9, 0.);
  mtimes(w73, s22, w17, s6, w96, s2, w, 0);
  for (i=0, rr=w20, cs=w96; i<9; ++i) (*rr++) += (*cs++);
  fill(w27, 24, 0.);
  for (i=0, rr=w27; i<8; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w20+j, tt=w23+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  for (rr=w103, ss=w27+1; ss!=w27+25; ss+=3) *rr++ = *ss;
  for (i=0, rr=w69, cr=w25, cs=w103; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w22, cs=w27; i<24; ++i) *rr++ = (- *cs++ );
  for (rr=w73, ss=w22+0; ss!=w22+3; ss+=1) *rr++ = *ss;
  for (i=0, rr=w73, cs=w73; i<3; ++i) (*rr++)  = (w10*(*cs++));
  for (i=0, rr=w73, cs=w73; i<3; ++i) (*rr++)  = (w80*(*cs++));
  for (rr=w8, ss=w22+0; ss!=w22+3; ss+=1) *rr++ = *ss;
  w79 = dot(3, w29, w8);
  w79 /= w11;
  for (i=0, rr=w8, cr=w28; i<3; ++i) (*rr++)  = ((*cr++)*w79);
  for (i=0, rr=w73, cs=w8; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=w8, ss=w22+3; ss!=w22+6; ss+=1) *rr++ = *ss;
  for (i=0, rr=w8, cs=w8; i<3; ++i) (*rr++)  = (w12*(*cs++));
  for (i=0, rr=w8, cs=w8; i<3; ++i) (*rr++)  = (w72*(*cs++));
  for (rr=w71, ss=w22+3; ss!=w22+6; ss+=1) *rr++ = *ss;
  w79 = dot(3, w32, w71);
  w79 /= w13;
  for (i=0, rr=w71, cr=w31; i<3; ++i) (*rr++)  = ((*cr++)*w79);
  for (i=0, rr=w8, cs=w71; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=w71, ss=w22+6; ss!=w22+9; ss+=1) *rr++ = *ss;
  for (i=0, rr=w71, cs=w71; i<3; ++i) (*rr++)  = (w33*(*cs++));
  for (i=0, rr=w71, cs=w71; i<3; ++i) (*rr++)  = (w74*(*cs++));
  for (rr=w83, ss=w22+6; ss!=w22+9; ss+=1) *rr++ = *ss;
  w79 = dot(3, w36, w83);
  w79 /= w37;
  for (i=0, rr=w83, cr=w35; i<3; ++i) (*rr++)  = ((*cr++)*w79);
  for (i=0, rr=w71, cs=w83; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=w83, ss=w22+9; ss!=w22+12; ss+=1) *rr++ = *ss;
  for (i=0, rr=w83, cs=w83; i<3; ++i) (*rr++)  = (w38*(*cs++));
  for (i=0, rr=w83, cs=w83; i<3; ++i) (*rr++)  = (w78*(*cs++));
  for (rr=w97, ss=w22+9; ss!=w22+12; ss+=1) *rr++ = *ss;
  w79 = dot(3, w41, w97);
  w79 /= w42;
  for (i=0, rr=w97, cr=w40; i<3; ++i) (*rr++)  = ((*cr++)*w79);
  for (i=0, rr=w83, cs=w97; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=w97, ss=w22+12; ss!=w22+15; ss+=1) *rr++ = *ss;
  for (i=0, rr=w97, cs=w97; i<3; ++i) (*rr++)  = (w43*(*cs++));
  for (i=0, rr=w97, cs=w97; i<3; ++i) (*rr++)  = (w84*(*cs++));
  for (rr=w98, ss=w22+12; ss!=w22+15; ss+=1) *rr++ = *ss;
  w79 = dot(3, w46, w98);
  w79 /= w47;
  for (i=0, rr=w98, cr=w45; i<3; ++i) (*rr++)  = ((*cr++)*w79);
  for (i=0, rr=w97, cs=w98; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=w98, ss=w22+15; ss!=w22+18; ss+=1) *rr++ = *ss;
  for (i=0, rr=w98, cs=w98; i<3; ++i) (*rr++)  = (w48*(*cs++));
  for (i=0, rr=w98, cs=w98; i<3; ++i) (*rr++)  = (w81*(*cs++));
  for (rr=w99, ss=w22+15; ss!=w22+18; ss+=1) *rr++ = *ss;
  w79 = dot(3, w51, w99);
  w79 /= w52;
  for (i=0, rr=w99, cr=w50; i<3; ++i) (*rr++)  = ((*cr++)*w79);
  for (i=0, rr=w98, cs=w99; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=w99, ss=w22+18; ss!=w22+21; ss+=1) *rr++ = *ss;
  for (i=0, rr=w99, cs=w99; i<3; ++i) (*rr++)  = (w53*(*cs++));
  for (i=0, rr=w99, cs=w99; i<3; ++i) (*rr++)  = (w85*(*cs++));
  for (rr=w100, ss=w22+18; ss!=w22+21; ss+=1) *rr++ = *ss;
  w79 = dot(3, w56, w100);
  w79 /= w57;
  for (i=0, rr=w100, cr=w55; i<3; ++i) (*rr++)  = ((*cr++)*w79);
  for (i=0, rr=w99, cs=w100; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=w100, ss=w22+21; ss!=w22+24; ss+=1) *rr++ = *ss;
  for (i=0, rr=w100, cs=w100; i<3; ++i) (*rr++)  = (w58*(*cs++));
  for (i=0, rr=w100, cs=w100; i<3; ++i) (*rr++)  = (w76*(*cs++));
  for (rr=w101, ss=w22+21; ss!=w22+24; ss+=1) *rr++ = *ss;
  w79 = dot(3, w61, w101);
  w79 /= w62;
  for (i=0, rr=w101, cr=w60; i<3; ++i) (*rr++)  = ((*cr++)*w79);
  for (i=0, rr=w100, cs=w101; i<3; ++i) (*rr++) -= (*cs++);
  rr=w22;
  for (i=0, cs=w73; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w8; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w71; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w83; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w97; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w98; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w99; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w100; i<3; ++i) *rr++ = *cs++;
  for (rr=w107, ss=w22+2; ss!=w22+26; ss+=3) *rr++ = *ss;
  for (i=0, rr=w70, cr=w24, cs=w107; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w69, cs=w70; i<8; ++i) (*rr++) += (*cs++);
  for (rr=w70, ss=w27+2; ss!=w27+26; ss+=3) *rr++ = *ss;
  for (i=0, rr=w104, cr=w65, cs=w70; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (rr=w105, ss=w22+1; ss!=w22+25; ss+=3) *rr++ = *ss;
  for (i=0, rr=w102, cr=w64, cs=w105; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w104, cs=w102; i<8; ++i) (*rr++) += (*cs++);
  for (i=0, rr=w69, cs=w104; i<8; ++i) (*rr++) -= (*cs++);
  for (i=0, rr=w70, cr=w66, cs=w70; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (rr=w104, ss=w22+0; ss!=w22+24; ss+=3) *rr++ = *ss;
  for (i=0, rr=w102, cr=w64, cs=w104; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w70, cs=w102; i<8; ++i) (*rr++) += (*cs++);
  for (rr=w102, ss=w27+0; ss!=w27+24; ss+=3) *rr++ = *ss;
  for (i=0, rr=w106, cr=w25, cs=w102; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w107, cr=w68, cs=w107; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w106, cs=w107; i<8; ++i) (*rr++) += (*cs++);
  for (i=0, rr=w70, cs=w106; i<8; ++i) (*rr++) -= (*cs++);
  for (i=0, rr=w102, cr=w65, cs=w102; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w105, cr=w68, cs=w105; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w102, cs=w105; i<8; ++i) (*rr++) += (*cs++);
  for (i=0, rr=w103, cr=w66, cs=w103; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w104, cr=w24, cs=w104; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w103, cs=w104; i<8; ++i) (*rr++) += (*cs++);
  for (i=0, rr=w102, cs=w103; i<8; ++i) (*rr++) -= (*cs++);
  rr=w27;
  for (i=0, cs=w69; i<8; ++i) *rr++ = *cs++;
  for (i=0, cs=w70; i<8; ++i) *rr++ = *cs++;
  for (i=0, cs=w102; i<8; ++i) *rr++ = *cs++;
  for (i=0, rr=w108, cs=w27; i<3; ++i) for (j=0; j<8; ++j) rr[i+j*3] = *cs++;
  fill(w27, 24, 0.);
  for (i=0, rr=w27; i<8; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w21+j, tt=w108+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  for (i=0, rr=w96, cs=w20; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  fill(w108, 24, 0.);
  for (i=0, rr=w108; i<8; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w96+j, tt=w26+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  for (i=0, rr=w27, cs=w108; i<24; ++i) (*rr++) += (*cs++);
  fill(w73, 3, 0.);
  for (i=0, rr=w73; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w27+j, tt=w63+i*8; k<8; ++k) *rr += ss[k*3]**tt++;
  fill(w8, 3, 0.);
  for (i=0, rr=w8; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w5+j, tt=w73+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  for (rr=(&w79), ss=(&w86)+0; ss!=(&w86)+1; ss+=1) *rr++ = *ss;
  w79 = (- w79 );
  rr=(&w77);
  *rr++ = w79;
  for (rr=(&w79), ss=(&w86)+0; ss!=(&w86)+1; ss+=1) *rr++ = *ss;
  w79 = (- w79 );
  rr=(&w109);
  *rr++ = w79;
  for (rr=(&w79), ss=(&w86)+0; ss!=(&w86)+1; ss+=1) *rr++ = *ss;
  rr=(&w86);
  *rr++ = w79;
  rr=w73;
  *rr++ = w77;
  *rr++ = w109;
  *rr++ = w86;
  fill(w14, 4, 0.);
  mtimes(w73, s21, w6, s3, w14, s5, w, 0);
  for (i=0, rr=w14, cs=w14; i<4; ++i) (*rr++)  = (w75*(*cs++));
  fill(w73, 3, 0.);
  for (i=0, rr=w73; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w22+j, tt=w67+i*8; k<8; ++k) *rr += ss[k*3]**tt++;
  for (i=0, rr=w73, cs=w73; i<3; ++i) (*rr++)  = (w82*(*cs++));
  rr=w90;
  for (i=0, cs=w8; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w73; i<3; ++i) *rr++ = *cs++;
  for (cii=s23, rr=w96, ss=w90; cii!=s23+9; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  for (cii=s24, rr=w91, ss=w96; cii!=s24+9; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  w77 = 1.;
  w109 = w77;
  for (rr=(&w77), ss=(&w109)+0; ss!=(&w109)+1; ss+=1) *rr++ = *ss;
  rr=(&w86);
  *rr++ = w77;
  for (rr=(&w77), ss=(&w109)+0; ss!=(&w109)+1; ss+=1) *rr++ = *ss;
  w77 = (- w77 );
  rr=(&w79);
  *rr++ = w77;
  for (rr=(&w77), ss=(&w109)+0; ss!=(&w109)+1; ss+=1) *rr++ = *ss;
  w77 = (- w77 );
  rr=(&w87);
  *rr++ = w77;
  rr=w8;
  *rr++ = w86;
  *rr++ = w79;
  *rr++ = w87;
  fill(w96, 9, 0.);
  mtimes(w19, s13, w8, s25, w96, s2, w, 0);
  for (rr=(&w86), ss=(&w109)+0; ss!=(&w109)+1; ss+=1) *rr++ = *ss;
  w86 = (- w86 );
  rr=(&w79);
  *rr++ = w86;
  for (rr=(&w86), ss=(&w109)+0; ss!=(&w109)+1; ss+=1) *rr++ = *ss;
  rr=(&w87);
  *rr++ = w86;
  for (rr=(&w86), ss=(&w109)+0; ss!=(&w109)+1; ss+=1) *rr++ = *ss;
  w86 = (- w86 );
  rr=(&w77);
  *rr++ = w86;
  rr=w8;
  *rr++ = w79;
  *rr++ = w87;
  *rr++ = w77;
  trans(w8, s25, w73, s26, iw);
  fill(w20, 9, 0.);
  mtimes(w73, s26, w17, s6, w20, s2, w, 0);
  for (i=0, rr=w96, cs=w20; i<9; ++i) (*rr++) += (*cs++);
  fill(w22, 24, 0.);
  for (i=0, rr=w22; i<8; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w96+j, tt=w23+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  for (rr=w69, ss=w22+1; ss!=w22+25; ss+=3) *rr++ = *ss;
  for (i=0, rr=w70, cr=w25, cs=w69; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w23, cs=w22; i<24; ++i) *rr++ = (- *cs++ );
  for (rr=w73, ss=w23+0; ss!=w23+3; ss+=1) *rr++ = *ss;
  for (i=0, rr=w73, cs=w73; i<3; ++i) (*rr++)  = (w10*(*cs++));
  for (i=0, rr=w73, cs=w73; i<3; ++i) (*rr++)  = (w80*(*cs++));
  for (rr=w8, ss=w23+0; ss!=w23+3; ss+=1) *rr++ = *ss;
  w79 = dot(3, w29, w8);
  w79 /= w11;
  for (i=0, rr=w8, cr=w28; i<3; ++i) (*rr++)  = ((*cr++)*w79);
  for (i=0, rr=w73, cs=w8; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=w8, ss=w23+3; ss!=w23+6; ss+=1) *rr++ = *ss;
  for (i=0, rr=w8, cs=w8; i<3; ++i) (*rr++)  = (w12*(*cs++));
  for (i=0, rr=w8, cs=w8; i<3; ++i) (*rr++)  = (w72*(*cs++));
  for (rr=w71, ss=w23+3; ss!=w23+6; ss+=1) *rr++ = *ss;
  w79 = dot(3, w32, w71);
  w79 /= w13;
  for (i=0, rr=w71, cr=w31; i<3; ++i) (*rr++)  = ((*cr++)*w79);
  for (i=0, rr=w8, cs=w71; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=w71, ss=w23+6; ss!=w23+9; ss+=1) *rr++ = *ss;
  for (i=0, rr=w71, cs=w71; i<3; ++i) (*rr++)  = (w33*(*cs++));
  for (i=0, rr=w71, cs=w71; i<3; ++i) (*rr++)  = (w74*(*cs++));
  for (rr=w83, ss=w23+6; ss!=w23+9; ss+=1) *rr++ = *ss;
  w79 = dot(3, w36, w83);
  w79 /= w37;
  for (i=0, rr=w83, cr=w35; i<3; ++i) (*rr++)  = ((*cr++)*w79);
  for (i=0, rr=w71, cs=w83; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=w83, ss=w23+9; ss!=w23+12; ss+=1) *rr++ = *ss;
  for (i=0, rr=w83, cs=w83; i<3; ++i) (*rr++)  = (w38*(*cs++));
  for (i=0, rr=w83, cs=w83; i<3; ++i) (*rr++)  = (w78*(*cs++));
  for (rr=w97, ss=w23+9; ss!=w23+12; ss+=1) *rr++ = *ss;
  w79 = dot(3, w41, w97);
  w79 /= w42;
  for (i=0, rr=w97, cr=w40; i<3; ++i) (*rr++)  = ((*cr++)*w79);
  for (i=0, rr=w83, cs=w97; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=w97, ss=w23+12; ss!=w23+15; ss+=1) *rr++ = *ss;
  for (i=0, rr=w97, cs=w97; i<3; ++i) (*rr++)  = (w43*(*cs++));
  for (i=0, rr=w97, cs=w97; i<3; ++i) (*rr++)  = (w84*(*cs++));
  for (rr=w98, ss=w23+12; ss!=w23+15; ss+=1) *rr++ = *ss;
  w79 = dot(3, w46, w98);
  w79 /= w47;
  for (i=0, rr=w98, cr=w45; i<3; ++i) (*rr++)  = ((*cr++)*w79);
  for (i=0, rr=w97, cs=w98; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=w98, ss=w23+15; ss!=w23+18; ss+=1) *rr++ = *ss;
  for (i=0, rr=w98, cs=w98; i<3; ++i) (*rr++)  = (w48*(*cs++));
  for (i=0, rr=w98, cs=w98; i<3; ++i) (*rr++)  = (w81*(*cs++));
  for (rr=w99, ss=w23+15; ss!=w23+18; ss+=1) *rr++ = *ss;
  w79 = dot(3, w51, w99);
  w79 /= w52;
  for (i=0, rr=w99, cr=w50; i<3; ++i) (*rr++)  = ((*cr++)*w79);
  for (i=0, rr=w98, cs=w99; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=w99, ss=w23+18; ss!=w23+21; ss+=1) *rr++ = *ss;
  for (i=0, rr=w99, cs=w99; i<3; ++i) (*rr++)  = (w53*(*cs++));
  for (i=0, rr=w99, cs=w99; i<3; ++i) (*rr++)  = (w85*(*cs++));
  for (rr=w100, ss=w23+18; ss!=w23+21; ss+=1) *rr++ = *ss;
  w79 = dot(3, w56, w100);
  w79 /= w57;
  for (i=0, rr=w100, cr=w55; i<3; ++i) (*rr++)  = ((*cr++)*w79);
  for (i=0, rr=w99, cs=w100; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=w100, ss=w23+21; ss!=w23+24; ss+=1) *rr++ = *ss;
  for (i=0, rr=w100, cs=w100; i<3; ++i) (*rr++)  = (w58*(*cs++));
  for (i=0, rr=w100, cs=w100; i<3; ++i) (*rr++)  = (w76*(*cs++));
  for (rr=w101, ss=w23+21; ss!=w23+24; ss+=1) *rr++ = *ss;
  w79 = dot(3, w61, w101);
  w79 /= w62;
  for (i=0, rr=w101, cr=w60; i<3; ++i) (*rr++)  = ((*cr++)*w79);
  for (i=0, rr=w100, cs=w101; i<3; ++i) (*rr++) -= (*cs++);
  rr=w23;
  for (i=0, cs=w73; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w8; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w71; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w83; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w97; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w98; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w99; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w100; i<3; ++i) *rr++ = *cs++;
  for (rr=w102, ss=w23+2; ss!=w23+26; ss+=3) *rr++ = *ss;
  for (i=0, rr=w103, cr=w24, cs=w102; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w70, cs=w103; i<8; ++i) (*rr++) += (*cs++);
  for (rr=w103, ss=w22+2; ss!=w22+26; ss+=3) *rr++ = *ss;
  for (i=0, rr=w104, cr=w65, cs=w103; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (rr=w105, ss=w23+1; ss!=w23+25; ss+=3) *rr++ = *ss;
  for (i=0, rr=w106, cr=w64, cs=w105; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w104, cs=w106; i<8; ++i) (*rr++) += (*cs++);
  for (i=0, rr=w70, cs=w104; i<8; ++i) (*rr++) -= (*cs++);
  for (i=0, rr=w103, cr=w66, cs=w103; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (rr=w104, ss=w23+0; ss!=w23+24; ss+=3) *rr++ = *ss;
  for (i=0, rr=w106, cr=w64, cs=w104; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w103, cs=w106; i<8; ++i) (*rr++) += (*cs++);
  for (rr=w106, ss=w22+0; ss!=w22+24; ss+=3) *rr++ = *ss;
  for (i=0, rr=w25, cs=w106; i<8; ++i) (*rr++) *= (*cs++);
  for (i=0, rr=w102, cr=w68, cs=w102; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w25, cs=w102; i<8; ++i) (*rr++) += (*cs++);
  for (i=0, rr=w103, cs=w25; i<8; ++i) (*rr++) -= (*cs++);
  for (i=0, rr=w65, cs=w106; i<8; ++i) (*rr++) *= (*cs++);
  for (i=0, rr=w105, cr=w68, cs=w105; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w65, cs=w105; i<8; ++i) (*rr++) += (*cs++);
  for (i=0, rr=w66, cs=w69; i<8; ++i) (*rr++) *= (*cs++);
  for (i=0, rr=w104, cr=w24, cs=w104; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w66, cs=w104; i<8; ++i) (*rr++) += (*cs++);
  for (i=0, rr=w65, cs=w66; i<8; ++i) (*rr++) -= (*cs++);
  rr=w22;
  for (i=0, cs=w70; i<8; ++i) *rr++ = *cs++;
  for (i=0, cs=w103; i<8; ++i) *rr++ = *cs++;
  for (i=0, cs=w65; i<8; ++i) *rr++ = *cs++;
  for (i=0, rr=w27, cs=w22; i<3; ++i) for (j=0; j<8; ++j) rr[i+j*3] = *cs++;
  fill(w22, 24, 0.);
  for (i=0, rr=w22; i<8; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w21+j, tt=w27+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  for (i=0, rr=w20, cs=w96; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  fill(w27, 24, 0.);
  for (i=0, rr=w27; i<8; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w20+j, tt=w26+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  for (i=0, rr=w22, cs=w27; i<24; ++i) (*rr++) += (*cs++);
  fill(w73, 3, 0.);
  for (i=0, rr=w73; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w22+j, tt=w63+i*8; k<8; ++k) *rr += ss[k*3]**tt++;
  fill(w8, 3, 0.);
  for (i=0, rr=w8; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w5+j, tt=w73+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  for (rr=(&w79), ss=(&w109)+0; ss!=(&w109)+1; ss+=1) *rr++ = *ss;
  rr=(&w87);
  *rr++ = w79;
  for (rr=(&w79), ss=(&w109)+0; ss!=(&w109)+1; ss+=1) *rr++ = *ss;
  w79 = (- w79 );
  rr=(&w77);
  *rr++ = w79;
  for (rr=(&w79), ss=(&w109)+0; ss!=(&w109)+1; ss+=1) *rr++ = *ss;
  w79 = (- w79 );
  rr=(&w109);
  *rr++ = w79;
  rr=w73;
  *rr++ = w87;
  *rr++ = w77;
  *rr++ = w109;
  fill(w14, 4, 0.);
  mtimes(w73, s25, w6, s3, w14, s5, w, 0);
  for (i=0, rr=w14, cs=w14; i<4; ++i) (*rr++)  = (w75*(*cs++));
  fill(w73, 3, 0.);
  for (i=0, rr=w73; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w23+j, tt=w67+i*8; k<8; ++k) *rr += ss[k*3]**tt++;
  for (i=0, rr=w73, cs=w73; i<3; ++i) (*rr++)  = (w82*(*cs++));
  rr=w90;
  for (i=0, cs=w8; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w73; i<3; ++i) *rr++ = *cs++;
  for (cii=s27, rr=w20, ss=w90; cii!=s27+9; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  for (cii=s28, rr=w91, ss=w20; cii!=s28+9; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  w75 = 1.;
  w87 = w75;
  for (i=0;i<8;++i) {
    copy((&w87), 1, w70+ i*1);
  }
  for (i=0, rr=w70, cs=w70; i<8; ++i) *rr++ = (- *cs++ );
  for (rr=(&w87), ss=w70+0; ss!=w70+1; ss+=1) *rr++ = *ss;
  w87  = (w10*w87);
    project((&w87), s4, w8, s3, w);
  for (i=0, rr=w8, cs=w8; i<3; ++i) (*rr++)  = (w80*(*cs++));
    project(w29, s3, (&w87), s4, w);
  for (rr=(&w75), ss=w70+0; ss!=w70+1; ss+=1) *rr++ = *ss;
  w77 = dot(1, (&w87), (&w75));
  w77 /= w11;
  for (i=0, rr=w73, cr=w28; i<3; ++i) (*rr++)  = ((*cr++)*w77);
  for (i=0, rr=w8, cs=w73; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=(&w77), ss=w70+1; ss!=w70+2; ss+=1) *rr++ = *ss;
  w77  = (w12*w77);
    project((&w77), s4, w73, s3, w);
  for (i=0, rr=w73, cs=w73; i<3; ++i) (*rr++)  = (w72*(*cs++));
    project(w32, s3, (&w77), s4, w);
  for (rr=(&w87), ss=w70+1; ss!=w70+2; ss+=1) *rr++ = *ss;
  w75 = dot(1, (&w77), (&w87));
  w75 /= w13;
  for (i=0, rr=w6, cr=w31; i<3; ++i) (*rr++)  = ((*cr++)*w75);
  for (i=0, rr=w73, cs=w6; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=(&w75), ss=w70+2; ss!=w70+3; ss+=1) *rr++ = *ss;
  w75  = (w33*w75);
    project((&w75), s4, w6, s3, w);
  for (i=0, rr=w6, cs=w6; i<3; ++i) (*rr++)  = (w74*(*cs++));
    project(w36, s3, (&w75), s4, w);
  for (rr=(&w77), ss=w70+2; ss!=w70+3; ss+=1) *rr++ = *ss;
  w87 = dot(1, (&w75), (&w77));
  w87 /= w37;
  for (i=0, rr=w71, cr=w35; i<3; ++i) (*rr++)  = ((*cr++)*w87);
  for (i=0, rr=w6, cs=w71; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=(&w87), ss=w70+3; ss!=w70+4; ss+=1) *rr++ = *ss;
  w87  = (w38*w87);
    project((&w87), s4, w71, s3, w);
  for (i=0, rr=w71, cs=w71; i<3; ++i) (*rr++)  = (w78*(*cs++));
    project(w41, s3, (&w87), s4, w);
  for (rr=(&w75), ss=w70+3; ss!=w70+4; ss+=1) *rr++ = *ss;
  w77 = dot(1, (&w87), (&w75));
  w77 /= w42;
  for (i=0, rr=w83, cr=w40; i<3; ++i) (*rr++)  = ((*cr++)*w77);
  for (i=0, rr=w71, cs=w83; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=(&w77), ss=w70+4; ss!=w70+5; ss+=1) *rr++ = *ss;
  w77  = (w43*w77);
    project((&w77), s4, w83, s3, w);
  for (i=0, rr=w83, cs=w83; i<3; ++i) (*rr++)  = (w84*(*cs++));
    project(w46, s3, (&w77), s4, w);
  for (rr=(&w87), ss=w70+4; ss!=w70+5; ss+=1) *rr++ = *ss;
  w75 = dot(1, (&w77), (&w87));
  w75 /= w47;
  for (i=0, rr=w97, cr=w45; i<3; ++i) (*rr++)  = ((*cr++)*w75);
  for (i=0, rr=w83, cs=w97; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=(&w75), ss=w70+5; ss!=w70+6; ss+=1) *rr++ = *ss;
  w75  = (w48*w75);
    project((&w75), s4, w97, s3, w);
  for (i=0, rr=w97, cs=w97; i<3; ++i) (*rr++)  = (w81*(*cs++));
    project(w51, s3, (&w75), s4, w);
  for (rr=(&w77), ss=w70+5; ss!=w70+6; ss+=1) *rr++ = *ss;
  w87 = dot(1, (&w75), (&w77));
  w87 /= w52;
  for (i=0, rr=w98, cr=w50; i<3; ++i) (*rr++)  = ((*cr++)*w87);
  for (i=0, rr=w97, cs=w98; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=(&w87), ss=w70+6; ss!=w70+7; ss+=1) *rr++ = *ss;
  w87  = (w53*w87);
    project((&w87), s4, w98, s3, w);
  for (i=0, rr=w98, cs=w98; i<3; ++i) (*rr++)  = (w85*(*cs++));
    project(w56, s3, (&w87), s4, w);
  for (rr=(&w75), ss=w70+6; ss!=w70+7; ss+=1) *rr++ = *ss;
  w77 = dot(1, (&w87), (&w75));
  w77 /= w57;
  for (i=0, rr=w99, cr=w55; i<3; ++i) (*rr++)  = ((*cr++)*w77);
  for (i=0, rr=w98, cs=w99; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=(&w77), ss=w70+7; ss!=w70+8; ss+=1) *rr++ = *ss;
  w77  = (w58*w77);
    project((&w77), s4, w99, s3, w);
  for (i=0, rr=w99, cs=w99; i<3; ++i) (*rr++)  = (w76*(*cs++));
    project(w61, s3, (&w77), s4, w);
  for (rr=(&w87), ss=w70+7; ss!=w70+8; ss+=1) *rr++ = *ss;
  w75 = dot(1, (&w77), (&w87));
  w75 /= w62;
  for (i=0, rr=w100, cr=w60; i<3; ++i) (*rr++)  = ((*cr++)*w75);
  for (i=0, rr=w99, cs=w100; i<3; ++i) (*rr++) -= (*cs++);
  rr=w23;
  for (i=0, cs=w8; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w73; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w6; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w71; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w83; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w97; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w98; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w99; i<3; ++i) *rr++ = *cs++;
  for (rr=w70, ss=w23+2; ss!=w23+26; ss+=3) *rr++ = *ss;
  for (i=0, rr=w103, cr=w24, cs=w70; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (rr=w65, ss=w23+1; ss!=w23+25; ss+=3) *rr++ = *ss;
  for (i=0, rr=w66, cr=w64, cs=w65; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w103, cs=w66; i<8; ++i) (*rr++) -= (*cs++);
  for (rr=w66, ss=w23+0; ss!=w23+24; ss+=3) *rr++ = *ss;
  for (i=0, rr=w104, cr=w64, cs=w66; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w70, cr=w68, cs=w70; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w104, cs=w70; i<8; ++i) (*rr++) -= (*cs++);
  for (i=0, rr=w65, cr=w68, cs=w65; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w66, cr=w24, cs=w66; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w65, cs=w66; i<8; ++i) (*rr++) -= (*cs++);
  rr=w22;
  for (i=0, cs=w103; i<8; ++i) *rr++ = *cs++;
  for (i=0, cs=w104; i<8; ++i) *rr++ = *cs++;
  for (i=0, cs=w65; i<8; ++i) *rr++ = *cs++;
  for (i=0, rr=w27, cs=w22; i<3; ++i) for (j=0; j<8; ++j) rr[i+j*3] = *cs++;
  fill(w22, 24, 0.);
  for (i=0, rr=w22; i<8; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w21+j, tt=w27+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  fill(w8, 3, 0.);
  for (i=0, rr=w8; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w22+j, tt=w63+i*8; k<8; ++k) *rr += ss[k*3]**tt++;
  fill(w73, 3, 0.);
  for (i=0, rr=w73; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w5+j, tt=w8+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  fill(w8, 3, 0.);
  for (i=0, rr=w8; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w23+j, tt=w67+i*8; k<8; ++k) *rr += ss[k*3]**tt++;
  for (i=0, rr=w8, cs=w8; i<3; ++i) (*rr++)  = (w82*(*cs++));
  rr=w1;
  for (i=0, cs=w73; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w8; i<3; ++i) *rr++ = *cs++;
  for (rr=w4, ss=w1+0; ss!=w1+6; ss+=1) *rr++ = *ss;
  for (cii=s29, rr=w91, ss=w4; cii!=s29+6; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  w75 = 1.;
  w77 = w75;
  for (i=0;i<8;++i) {
    copy((&w77), 1, w103+ i*1);
  }
  for (i=0, rr=w103, cs=w103; i<8; ++i) *rr++ = (- *cs++ );
  for (rr=(&w77), ss=w103+0; ss!=w103+1; ss+=1) *rr++ = *ss;
  w77  = (w10*w77);
    project((&w77), s8, w73, s3, w);
  for (i=0, rr=w73, cs=w73; i<3; ++i) (*rr++)  = (w80*(*cs++));
    project(w29, s3, (&w77), s8, w);
  for (rr=(&w75), ss=w103+0; ss!=w103+1; ss+=1) *rr++ = *ss;
  w87 = dot(1, (&w77), (&w75));
  w87 /= w11;
  for (i=0, rr=w8, cr=w28; i<3; ++i) (*rr++)  = ((*cr++)*w87);
  for (i=0, rr=w73, cs=w8; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=(&w87), ss=w103+1; ss!=w103+2; ss+=1) *rr++ = *ss;
  w87  = (w12*w87);
    project((&w87), s8, w8, s3, w);
  for (i=0, rr=w8, cs=w8; i<3; ++i) (*rr++)  = (w72*(*cs++));
    project(w32, s3, (&w87), s8, w);
  for (rr=(&w77), ss=w103+1; ss!=w103+2; ss+=1) *rr++ = *ss;
  w75 = dot(1, (&w87), (&w77));
  w75 /= w13;
  for (i=0, rr=w6, cr=w31; i<3; ++i) (*rr++)  = ((*cr++)*w75);
  for (i=0, rr=w8, cs=w6; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=(&w75), ss=w103+2; ss!=w103+3; ss+=1) *rr++ = *ss;
  w75  = (w33*w75);
    project((&w75), s8, w6, s3, w);
  for (i=0, rr=w6, cs=w6; i<3; ++i) (*rr++)  = (w74*(*cs++));
    project(w36, s3, (&w75), s8, w);
  for (rr=(&w87), ss=w103+2; ss!=w103+3; ss+=1) *rr++ = *ss;
  w77 = dot(1, (&w75), (&w87));
  w77 /= w37;
  for (i=0, rr=w71, cr=w35; i<3; ++i) (*rr++)  = ((*cr++)*w77);
  for (i=0, rr=w6, cs=w71; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=(&w77), ss=w103+3; ss!=w103+4; ss+=1) *rr++ = *ss;
  w77  = (w38*w77);
    project((&w77), s8, w71, s3, w);
  for (i=0, rr=w71, cs=w71; i<3; ++i) (*rr++)  = (w78*(*cs++));
    project(w41, s3, (&w77), s8, w);
  for (rr=(&w75), ss=w103+3; ss!=w103+4; ss+=1) *rr++ = *ss;
  w87 = dot(1, (&w77), (&w75));
  w87 /= w42;
  for (i=0, rr=w83, cr=w40; i<3; ++i) (*rr++)  = ((*cr++)*w87);
  for (i=0, rr=w71, cs=w83; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=(&w87), ss=w103+4; ss!=w103+5; ss+=1) *rr++ = *ss;
  w87  = (w43*w87);
    project((&w87), s8, w83, s3, w);
  for (i=0, rr=w83, cs=w83; i<3; ++i) (*rr++)  = (w84*(*cs++));
    project(w46, s3, (&w87), s8, w);
  for (rr=(&w77), ss=w103+4; ss!=w103+5; ss+=1) *rr++ = *ss;
  w75 = dot(1, (&w87), (&w77));
  w75 /= w47;
  for (i=0, rr=w97, cr=w45; i<3; ++i) (*rr++)  = ((*cr++)*w75);
  for (i=0, rr=w83, cs=w97; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=(&w75), ss=w103+5; ss!=w103+6; ss+=1) *rr++ = *ss;
  w75  = (w48*w75);
    project((&w75), s8, w97, s3, w);
  for (i=0, rr=w97, cs=w97; i<3; ++i) (*rr++)  = (w81*(*cs++));
    project(w51, s3, (&w75), s8, w);
  for (rr=(&w87), ss=w103+5; ss!=w103+6; ss+=1) *rr++ = *ss;
  w77 = dot(1, (&w75), (&w87));
  w77 /= w52;
  for (i=0, rr=w98, cr=w50; i<3; ++i) (*rr++)  = ((*cr++)*w77);
  for (i=0, rr=w97, cs=w98; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=(&w77), ss=w103+6; ss!=w103+7; ss+=1) *rr++ = *ss;
  w77  = (w53*w77);
    project((&w77), s8, w98, s3, w);
  for (i=0, rr=w98, cs=w98; i<3; ++i) (*rr++)  = (w85*(*cs++));
    project(w56, s3, (&w77), s8, w);
  for (rr=(&w75), ss=w103+6; ss!=w103+7; ss+=1) *rr++ = *ss;
  w87 = dot(1, (&w77), (&w75));
  w87 /= w57;
  for (i=0, rr=w99, cr=w55; i<3; ++i) (*rr++)  = ((*cr++)*w87);
  for (i=0, rr=w98, cs=w99; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=(&w87), ss=w103+7; ss!=w103+8; ss+=1) *rr++ = *ss;
  w87  = (w58*w87);
    project((&w87), s8, w99, s3, w);
  for (i=0, rr=w99, cs=w99; i<3; ++i) (*rr++)  = (w76*(*cs++));
    project(w61, s3, (&w87), s8, w);
  for (rr=(&w77), ss=w103+7; ss!=w103+8; ss+=1) *rr++ = *ss;
  w75 = dot(1, (&w87), (&w77));
  w75 /= w62;
  for (i=0, rr=w100, cr=w60; i<3; ++i) (*rr++)  = ((*cr++)*w75);
  for (i=0, rr=w99, cs=w100; i<3; ++i) (*rr++) -= (*cs++);
  rr=w23;
  for (i=0, cs=w73; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w8; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w6; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w71; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w83; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w97; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w98; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w99; i<3; ++i) *rr++ = *cs++;
  for (rr=w103, ss=w23+2; ss!=w23+26; ss+=3) *rr++ = *ss;
  for (i=0, rr=w104, cr=w24, cs=w103; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (rr=w65, ss=w23+1; ss!=w23+25; ss+=3) *rr++ = *ss;
  for (i=0, rr=w66, cr=w64, cs=w65; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w104, cs=w66; i<8; ++i) (*rr++) -= (*cs++);
  for (rr=w66, ss=w23+0; ss!=w23+24; ss+=3) *rr++ = *ss;
  for (i=0, rr=w70, cr=w64, cs=w66; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w103, cr=w68, cs=w103; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w70, cs=w103; i<8; ++i) (*rr++) -= (*cs++);
  for (i=0, rr=w65, cr=w68, cs=w65; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w66, cr=w24, cs=w66; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w65, cs=w66; i<8; ++i) (*rr++) -= (*cs++);
  rr=w22;
  for (i=0, cs=w104; i<8; ++i) *rr++ = *cs++;
  for (i=0, cs=w70; i<8; ++i) *rr++ = *cs++;
  for (i=0, cs=w65; i<8; ++i) *rr++ = *cs++;
  for (i=0, rr=w27, cs=w22; i<3; ++i) for (j=0; j<8; ++j) rr[i+j*3] = *cs++;
  fill(w22, 24, 0.);
  for (i=0, rr=w22; i<8; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w21+j, tt=w27+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  fill(w73, 3, 0.);
  for (i=0, rr=w73; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w22+j, tt=w63+i*8; k<8; ++k) *rr += ss[k*3]**tt++;
  fill(w8, 3, 0.);
  for (i=0, rr=w8; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w5+j, tt=w73+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  fill(w73, 3, 0.);
  for (i=0, rr=w73; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w23+j, tt=w67+i*8; k<8; ++k) *rr += ss[k*3]**tt++;
  for (i=0, rr=w73, cs=w73; i<3; ++i) (*rr++)  = (w82*(*cs++));
  rr=w4;
  for (i=0, cs=w8; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w73; i<3; ++i) *rr++ = *cs++;
  for (rr=w1, ss=w4+0; ss!=w4+6; ss+=1) *rr++ = *ss;
  for (cii=s30, rr=w91, ss=w1; cii!=s30+6; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  w75 = 1.;
  w87 = w75;
  for (i=0;i<8;++i) {
    copy((&w87), 1, w104+ i*1);
  }
  for (i=0, rr=w104, cs=w104; i<8; ++i) *rr++ = (- *cs++ );
  for (rr=(&w87), ss=w104+0; ss!=w104+1; ss+=1) *rr++ = *ss;
  w10 *= w87;
    project((&w10), s10, w8, s3, w);
  for (i=0, rr=w8, cs=w8; i<3; ++i) (*rr++)  = (w80*(*cs++));
    project(w29, s3, (&w80), s10, w);
  for (rr=(&w10), ss=w104+0; ss!=w104+1; ss+=1) *rr++ = *ss;
  w87 = dot(1, (&w80), (&w10));
  w87 /= w11;
  for (i=0, rr=w28; i<3; ++i) (*rr++) *= w87;
  for (i=0, rr=w8, cs=w28; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=(&w87), ss=w104+1; ss!=w104+2; ss+=1) *rr++ = *ss;
  w12 *= w87;
    project((&w12), s10, w28, s3, w);
  for (i=0, rr=w28, cs=w28; i<3; ++i) (*rr++)  = (w72*(*cs++));
    project(w32, s3, (&w72), s10, w);
  for (rr=(&w12), ss=w104+1; ss!=w104+2; ss+=1) *rr++ = *ss;
  w87 = dot(1, (&w72), (&w12));
  w87 /= w13;
  for (i=0, rr=w31; i<3; ++i) (*rr++) *= w87;
  for (i=0, rr=w28, cs=w31; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=(&w87), ss=w104+2; ss!=w104+3; ss+=1) *rr++ = *ss;
  w33 *= w87;
    project((&w33), s10, w31, s3, w);
  for (i=0, rr=w31, cs=w31; i<3; ++i) (*rr++)  = (w74*(*cs++));
    project(w36, s3, (&w74), s10, w);
  for (rr=(&w33), ss=w104+2; ss!=w104+3; ss+=1) *rr++ = *ss;
  w87 = dot(1, (&w74), (&w33));
  w87 /= w37;
  for (i=0, rr=w35; i<3; ++i) (*rr++) *= w87;
  for (i=0, rr=w31, cs=w35; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=(&w87), ss=w104+3; ss!=w104+4; ss+=1) *rr++ = *ss;
  w38 *= w87;
    project((&w38), s10, w35, s3, w);
  for (i=0, rr=w35, cs=w35; i<3; ++i) (*rr++)  = (w78*(*cs++));
    project(w41, s3, (&w78), s10, w);
  for (rr=(&w38), ss=w104+3; ss!=w104+4; ss+=1) *rr++ = *ss;
  w87 = dot(1, (&w78), (&w38));
  w87 /= w42;
  for (i=0, rr=w40; i<3; ++i) (*rr++) *= w87;
  for (i=0, rr=w35, cs=w40; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=(&w87), ss=w104+4; ss!=w104+5; ss+=1) *rr++ = *ss;
  w43 *= w87;
    project((&w43), s10, w40, s3, w);
  for (i=0, rr=w40, cs=w40; i<3; ++i) (*rr++)  = (w84*(*cs++));
    project(w46, s3, (&w84), s10, w);
  for (rr=(&w43), ss=w104+4; ss!=w104+5; ss+=1) *rr++ = *ss;
  w87 = dot(1, (&w84), (&w43));
  w87 /= w47;
  for (i=0, rr=w45; i<3; ++i) (*rr++) *= w87;
  for (i=0, rr=w40, cs=w45; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=(&w87), ss=w104+5; ss!=w104+6; ss+=1) *rr++ = *ss;
  w48 *= w87;
    project((&w48), s10, w45, s3, w);
  for (i=0, rr=w45, cs=w45; i<3; ++i) (*rr++)  = (w81*(*cs++));
    project(w51, s3, (&w81), s10, w);
  for (rr=(&w48), ss=w104+5; ss!=w104+6; ss+=1) *rr++ = *ss;
  w87 = dot(1, (&w81), (&w48));
  w87 /= w52;
  for (i=0, rr=w50; i<3; ++i) (*rr++) *= w87;
  for (i=0, rr=w45, cs=w50; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=(&w87), ss=w104+6; ss!=w104+7; ss+=1) *rr++ = *ss;
  w53 *= w87;
    project((&w53), s10, w50, s3, w);
  for (i=0, rr=w50, cs=w50; i<3; ++i) (*rr++)  = (w85*(*cs++));
    project(w56, s3, (&w85), s10, w);
  for (rr=(&w53), ss=w104+6; ss!=w104+7; ss+=1) *rr++ = *ss;
  w87 = dot(1, (&w85), (&w53));
  w87 /= w57;
  for (i=0, rr=w55; i<3; ++i) (*rr++) *= w87;
  for (i=0, rr=w50, cs=w55; i<3; ++i) (*rr++) -= (*cs++);
  for (rr=(&w87), ss=w104+7; ss!=w104+8; ss+=1) *rr++ = *ss;
  w58 *= w87;
    project((&w58), s10, w55, s3, w);
  for (i=0, rr=w55, cs=w55; i<3; ++i) (*rr++)  = (w76*(*cs++));
    project(w61, s3, (&w76), s10, w);
  for (rr=(&w58), ss=w104+7; ss!=w104+8; ss+=1) *rr++ = *ss;
  w87 = dot(1, (&w76), (&w58));
  w87 /= w62;
  for (i=0, rr=w60; i<3; ++i) (*rr++) *= w87;
  for (i=0, rr=w55, cs=w60; i<3; ++i) (*rr++) -= (*cs++);
  rr=w23;
  for (i=0, cs=w8; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w31; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w35; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w40; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w45; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w50; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w55; i<3; ++i) *rr++ = *cs++;
  for (rr=w104, ss=w23+2; ss!=w23+26; ss+=3) *rr++ = *ss;
  for (i=0, rr=w70, cr=w24, cs=w104; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (rr=w65, ss=w23+1; ss!=w23+25; ss+=3) *rr++ = *ss;
  for (i=0, rr=w66, cr=w64, cs=w65; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w70, cs=w66; i<8; ++i) (*rr++) -= (*cs++);
  for (rr=w66, ss=w23+0; ss!=w23+24; ss+=3) *rr++ = *ss;
  for (i=0, rr=w103, cr=w64, cs=w66; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w104, cr=w68, cs=w104; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w103, cs=w104; i<8; ++i) (*rr++) -= (*cs++);
  for (i=0, rr=w65, cr=w68, cs=w65; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w66, cr=w24, cs=w66; i<8; ++i) (*rr++)  = ((*cr++)*(*cs++));
  for (i=0, rr=w65, cs=w66; i<8; ++i) (*rr++) -= (*cs++);
  rr=w22;
  for (i=0, cs=w70; i<8; ++i) *rr++ = *cs++;
  for (i=0, cs=w103; i<8; ++i) *rr++ = *cs++;
  for (i=0, cs=w65; i<8; ++i) *rr++ = *cs++;
  for (i=0, rr=w27, cs=w22; i<3; ++i) for (j=0; j<8; ++j) rr[i+j*3] = *cs++;
  fill(w22, 24, 0.);
  for (i=0, rr=w22; i<8; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w21+j, tt=w27+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  fill(w8, 3, 0.);
  for (i=0, rr=w8; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w22+j, tt=w63+i*8; k<8; ++k) *rr += ss[k*3]**tt++;
  fill(w28, 3, 0.);
  for (i=0, rr=w28; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w5+j, tt=w8+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  fill(w8, 3, 0.);
  for (i=0, rr=w8; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w23+j, tt=w67+i*8; k<8; ++k) *rr += ss[k*3]**tt++;
  for (i=0, rr=w8, cs=w8; i<3; ++i) (*rr++)  = (w82*(*cs++));
  rr=w1;
  for (i=0, cs=w28; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w8; i<3; ++i) *rr++ = *cs++;
  for (rr=w4, ss=w1+0; ss!=w1+6; ss+=1) *rr++ = *ss;
  for (cii=s31, rr=w91, ss=w4; cii!=s31+6; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  trans(w91, s33, w110, s32, iw);
    project(w110, s32, w111, s34, w);
  if (res[1]) copy(w111, 169, res[1]);
    project(w24, s36, (&w82), s35, w);
  w11 = (1./ w11 );
  for (i=0, rr=w9, cs=w9; i<3; ++i) (*rr++)  = (w11*(*cs++));
  for (rr=(&w11), ss=w9+2; ss!=w9+3; ss+=1) *rr++ = *ss;
  w82 *= w11;
    project(w64, s36, (&w87), s35, w);
  for (rr=(&w76), ss=w9+1; ss!=w9+2; ss+=1) *rr++ = *ss;
  w87 *= w76;
  w82 -= w87;
    project(w64, s36, (&w87), s35, w);
  for (rr=(&w58), ss=w9+0; ss!=w9+1; ss+=1) *rr++ = *ss;
  w87 *= w58;
    project(w68, s36, (&w85), s35, w);
  w85 *= w11;
  w87 -= w85;
    project(w68, s36, (&w85), s35, w);
  w85 *= w76;
    project(w24, s36, (&w76), s35, w);
  w76 *= w58;
  w85 -= w76;
  rr=w28;
  *rr++ = w82;
  *rr++ = w87;
  *rr++ = w85;
  trans(w28, s38, w8, s37, iw);
  fill(w23, 24, 0.);
  mtimes(w21, s2, w8, s37, w23, s39, w, 0);
  fill(w8, 3, 0.);
  for (i=0, rr=w8; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w23+j, tt=w63+i*8; k<8; ++k) *rr += ss[k*3]**tt++;
  fill(w28, 3, 0.);
  for (i=0, rr=w28; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w5+j, tt=w8+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  rr=w8;
  for (i=0, cs=w9; i<3; ++i) *rr++ = *cs++;
  fill(w9, 3, 0.);
  mtimes(w8, s37, w67, s40, w9, s3, w, 0);
  w3 = (1./ w3 );
  for (i=0, rr=w9, cs=w9; i<3; ++i) (*rr++)  = (w3*(*cs++));
  rr=w4;
  for (i=0, cs=w28; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w9; i<3; ++i) *rr++ = *cs++;
  for (rr=w1, ss=w4+0; ss!=w4+6; ss+=1) *rr++ = *ss;
  fill(w116, 48, 0.);
  for (rr=w116+0, ss=w1; rr!=w116+48; rr+=8) *rr = *ss++;
    project(w24, s36, (&w82), s41, w);
  w13 = (1./ w13 );
  for (i=0, rr=w30, cs=w30; i<3; ++i) (*rr++)  = (w13*(*cs++));
  for (rr=(&w13), ss=w30+2; ss!=w30+3; ss+=1) *rr++ = *ss;
  w82 *= w13;
    project(w64, s36, (&w87), s41, w);
  for (rr=(&w85), ss=w30+1; ss!=w30+2; ss+=1) *rr++ = *ss;
  w87 *= w85;
  w82 -= w87;
    project(w64, s36, (&w87), s41, w);
  for (rr=(&w76), ss=w30+0; ss!=w30+1; ss+=1) *rr++ = *ss;
  w87 *= w76;
    project(w68, s36, (&w58), s41, w);
  w58 *= w13;
  w87 -= w58;
    project(w68, s36, (&w58), s41, w);
  w58 *= w85;
    project(w24, s36, (&w85), s41, w);
  w85 *= w76;
  w58 -= w85;
  rr=w28;
  *rr++ = w82;
  *rr++ = w87;
  *rr++ = w58;
  trans(w28, s43, w9, s42, iw);
  fill(w23, 24, 0.);
  mtimes(w21, s2, w9, s42, w23, s39, w, 0);
  fill(w9, 3, 0.);
  for (i=0, rr=w9; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w23+j, tt=w63+i*8; k<8; ++k) *rr += ss[k*3]**tt++;
  fill(w28, 3, 0.);
  for (i=0, rr=w28; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w5+j, tt=w9+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  rr=w9;
  for (i=0, cs=w30; i<3; ++i) *rr++ = *cs++;
  fill(w30, 3, 0.);
  mtimes(w9, s42, w67, s40, w30, s3, w, 0);
  for (i=0, rr=w30, cs=w30; i<3; ++i) (*rr++)  = (w3*(*cs++));
  rr=w1;
  for (i=0, cs=w28; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w30; i<3; ++i) *rr++ = *cs++;
  for (rr=w4, ss=w1+0; ss!=w1+6; ss+=1) *rr++ = *ss;
  for (rr=w116+1, ss=w4; rr!=w116+49; rr+=8) *rr = *ss++;
    project(w24, s36, (&w82), s44, w);
  w37 = (1./ w37 );
  for (i=0, rr=w34, cs=w34; i<3; ++i) (*rr++)  = (w37*(*cs++));
  for (rr=(&w37), ss=w34+2; ss!=w34+3; ss+=1) *rr++ = *ss;
  w82 *= w37;
    project(w64, s36, (&w87), s44, w);
  for (rr=(&w58), ss=w34+1; ss!=w34+2; ss+=1) *rr++ = *ss;
  w87 *= w58;
  w82 -= w87;
    project(w64, s36, (&w87), s44, w);
  for (rr=(&w85), ss=w34+0; ss!=w34+1; ss+=1) *rr++ = *ss;
  w87 *= w85;
    project(w68, s36, (&w76), s44, w);
  w76 *= w37;
  w87 -= w76;
    project(w68, s36, (&w76), s44, w);
  w76 *= w58;
    project(w24, s36, (&w58), s44, w);
  w58 *= w85;
  w76 -= w58;
  rr=w28;
  *rr++ = w82;
  *rr++ = w87;
  *rr++ = w76;
  trans(w28, s46, w30, s45, iw);
  fill(w23, 24, 0.);
  mtimes(w21, s2, w30, s45, w23, s39, w, 0);
  fill(w30, 3, 0.);
  for (i=0, rr=w30; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w23+j, tt=w63+i*8; k<8; ++k) *rr += ss[k*3]**tt++;
  fill(w28, 3, 0.);
  for (i=0, rr=w28; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w5+j, tt=w30+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  rr=w30;
  for (i=0, cs=w34; i<3; ++i) *rr++ = *cs++;
  fill(w34, 3, 0.);
  mtimes(w30, s45, w67, s40, w34, s3, w, 0);
  for (i=0, rr=w34, cs=w34; i<3; ++i) (*rr++)  = (w3*(*cs++));
  rr=w4;
  for (i=0, cs=w28; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w34; i<3; ++i) *rr++ = *cs++;
  for (rr=w1, ss=w4+0; ss!=w4+6; ss+=1) *rr++ = *ss;
  for (rr=w116+2, ss=w1; rr!=w116+50; rr+=8) *rr = *ss++;
    project(w24, s36, (&w82), s47, w);
  w42 = (1./ w42 );
  for (i=0, rr=w39, cs=w39; i<3; ++i) (*rr++)  = (w42*(*cs++));
  for (rr=(&w42), ss=w39+2; ss!=w39+3; ss+=1) *rr++ = *ss;
  w82 *= w42;
    project(w64, s36, (&w87), s47, w);
  for (rr=(&w76), ss=w39+1; ss!=w39+2; ss+=1) *rr++ = *ss;
  w87 *= w76;
  w82 -= w87;
    project(w64, s36, (&w87), s47, w);
  for (rr=(&w58), ss=w39+0; ss!=w39+1; ss+=1) *rr++ = *ss;
  w87 *= w58;
    project(w68, s36, (&w85), s47, w);
  w85 *= w42;
  w87 -= w85;
    project(w68, s36, (&w85), s47, w);
  w85 *= w76;
    project(w24, s36, (&w76), s47, w);
  w76 *= w58;
  w85 -= w76;
  rr=w28;
  *rr++ = w82;
  *rr++ = w87;
  *rr++ = w85;
  trans(w28, s49, w34, s48, iw);
  fill(w23, 24, 0.);
  mtimes(w21, s2, w34, s48, w23, s39, w, 0);
  fill(w34, 3, 0.);
  for (i=0, rr=w34; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w23+j, tt=w63+i*8; k<8; ++k) *rr += ss[k*3]**tt++;
  fill(w28, 3, 0.);
  for (i=0, rr=w28; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w5+j, tt=w34+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  rr=w34;
  for (i=0, cs=w39; i<3; ++i) *rr++ = *cs++;
  fill(w39, 3, 0.);
  mtimes(w34, s48, w67, s40, w39, s3, w, 0);
  for (i=0, rr=w39, cs=w39; i<3; ++i) (*rr++)  = (w3*(*cs++));
  rr=w1;
  for (i=0, cs=w28; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w39; i<3; ++i) *rr++ = *cs++;
  for (rr=w4, ss=w1+0; ss!=w1+6; ss+=1) *rr++ = *ss;
  for (rr=w116+3, ss=w4; rr!=w116+51; rr+=8) *rr = *ss++;
    project(w24, s36, (&w82), s50, w);
  w47 = (1./ w47 );
  for (i=0, rr=w44, cs=w44; i<3; ++i) (*rr++)  = (w47*(*cs++));
  for (rr=(&w47), ss=w44+2; ss!=w44+3; ss+=1) *rr++ = *ss;
  w82 *= w47;
    project(w64, s36, (&w87), s50, w);
  for (rr=(&w85), ss=w44+1; ss!=w44+2; ss+=1) *rr++ = *ss;
  w87 *= w85;
  w82 -= w87;
    project(w64, s36, (&w87), s50, w);
  for (rr=(&w76), ss=w44+0; ss!=w44+1; ss+=1) *rr++ = *ss;
  w87 *= w76;
    project(w68, s36, (&w58), s50, w);
  w58 *= w47;
  w87 -= w58;
    project(w68, s36, (&w58), s50, w);
  w58 *= w85;
    project(w24, s36, (&w85), s50, w);
  w85 *= w76;
  w58 -= w85;
  rr=w28;
  *rr++ = w82;
  *rr++ = w87;
  *rr++ = w58;
  trans(w28, s52, w39, s51, iw);
  fill(w23, 24, 0.);
  mtimes(w21, s2, w39, s51, w23, s39, w, 0);
  fill(w39, 3, 0.);
  for (i=0, rr=w39; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w23+j, tt=w63+i*8; k<8; ++k) *rr += ss[k*3]**tt++;
  fill(w28, 3, 0.);
  for (i=0, rr=w28; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w5+j, tt=w39+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  rr=w39;
  for (i=0, cs=w44; i<3; ++i) *rr++ = *cs++;
  fill(w44, 3, 0.);
  mtimes(w39, s51, w67, s40, w44, s3, w, 0);
  for (i=0, rr=w44, cs=w44; i<3; ++i) (*rr++)  = (w3*(*cs++));
  rr=w4;
  for (i=0, cs=w28; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w44; i<3; ++i) *rr++ = *cs++;
  for (rr=w1, ss=w4+0; ss!=w4+6; ss+=1) *rr++ = *ss;
  for (rr=w116+4, ss=w1; rr!=w116+52; rr+=8) *rr = *ss++;
    project(w24, s36, (&w82), s53, w);
  w52 = (1./ w52 );
  for (i=0, rr=w49, cs=w49; i<3; ++i) (*rr++)  = (w52*(*cs++));
  for (rr=(&w52), ss=w49+2; ss!=w49+3; ss+=1) *rr++ = *ss;
  w82 *= w52;
    project(w64, s36, (&w87), s53, w);
  for (rr=(&w58), ss=w49+1; ss!=w49+2; ss+=1) *rr++ = *ss;
  w87 *= w58;
  w82 -= w87;
    project(w64, s36, (&w87), s53, w);
  for (rr=(&w85), ss=w49+0; ss!=w49+1; ss+=1) *rr++ = *ss;
  w87 *= w85;
    project(w68, s36, (&w76), s53, w);
  w76 *= w52;
  w87 -= w76;
    project(w68, s36, (&w76), s53, w);
  w76 *= w58;
    project(w24, s36, (&w58), s53, w);
  w58 *= w85;
  w76 -= w58;
  rr=w28;
  *rr++ = w82;
  *rr++ = w87;
  *rr++ = w76;
  trans(w28, s55, w44, s54, iw);
  fill(w23, 24, 0.);
  mtimes(w21, s2, w44, s54, w23, s39, w, 0);
  fill(w44, 3, 0.);
  for (i=0, rr=w44; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w23+j, tt=w63+i*8; k<8; ++k) *rr += ss[k*3]**tt++;
  fill(w28, 3, 0.);
  for (i=0, rr=w28; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w5+j, tt=w44+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  rr=w44;
  for (i=0, cs=w49; i<3; ++i) *rr++ = *cs++;
  fill(w49, 3, 0.);
  mtimes(w44, s54, w67, s40, w49, s3, w, 0);
  for (i=0, rr=w49, cs=w49; i<3; ++i) (*rr++)  = (w3*(*cs++));
  rr=w1;
  for (i=0, cs=w28; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w49; i<3; ++i) *rr++ = *cs++;
  for (rr=w4, ss=w1+0; ss!=w1+6; ss+=1) *rr++ = *ss;
  for (rr=w116+5, ss=w4; rr!=w116+53; rr+=8) *rr = *ss++;
    project(w24, s36, (&w82), s56, w);
  w57 = (1./ w57 );
  for (i=0, rr=w54, cs=w54; i<3; ++i) (*rr++)  = (w57*(*cs++));
  for (rr=(&w57), ss=w54+2; ss!=w54+3; ss+=1) *rr++ = *ss;
  w82 *= w57;
    project(w64, s36, (&w87), s56, w);
  for (rr=(&w76), ss=w54+1; ss!=w54+2; ss+=1) *rr++ = *ss;
  w87 *= w76;
  w82 -= w87;
    project(w64, s36, (&w87), s56, w);
  for (rr=(&w58), ss=w54+0; ss!=w54+1; ss+=1) *rr++ = *ss;
  w87 *= w58;
    project(w68, s36, (&w85), s56, w);
  w85 *= w57;
  w87 -= w85;
    project(w68, s36, (&w85), s56, w);
  w85 *= w76;
    project(w24, s36, (&w76), s56, w);
  w76 *= w58;
  w85 -= w76;
  rr=w28;
  *rr++ = w82;
  *rr++ = w87;
  *rr++ = w85;
  trans(w28, s58, w49, s57, iw);
  fill(w23, 24, 0.);
  mtimes(w21, s2, w49, s57, w23, s39, w, 0);
  fill(w49, 3, 0.);
  for (i=0, rr=w49; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w23+j, tt=w63+i*8; k<8; ++k) *rr += ss[k*3]**tt++;
  fill(w28, 3, 0.);
  for (i=0, rr=w28; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w5+j, tt=w49+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  rr=w49;
  for (i=0, cs=w54; i<3; ++i) *rr++ = *cs++;
  fill(w54, 3, 0.);
  mtimes(w49, s57, w67, s40, w54, s3, w, 0);
  for (i=0, rr=w54, cs=w54; i<3; ++i) (*rr++)  = (w3*(*cs++));
  rr=w4;
  for (i=0, cs=w28; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w54; i<3; ++i) *rr++ = *cs++;
  for (rr=w1, ss=w4+0; ss!=w4+6; ss+=1) *rr++ = *ss;
  for (rr=w116+6, ss=w1; rr!=w116+54; rr+=8) *rr = *ss++;
    project(w24, s36, (&w82), s59, w);
  w62 = (1./ w62 );
  for (i=0, rr=w59, cs=w59; i<3; ++i) (*rr++)  = (w62*(*cs++));
  for (rr=(&w62), ss=w59+2; ss!=w59+3; ss+=1) *rr++ = *ss;
  w82 *= w62;
    project(w64, s36, (&w87), s59, w);
  for (rr=(&w85), ss=w59+1; ss!=w59+2; ss+=1) *rr++ = *ss;
  w87 *= w85;
  w82 -= w87;
    project(w64, s36, (&w87), s59, w);
  for (rr=(&w76), ss=w59+0; ss!=w59+1; ss+=1) *rr++ = *ss;
  w87 *= w76;
    project(w68, s36, (&w58), s59, w);
  w58 *= w62;
  w87 -= w58;
    project(w68, s36, (&w58), s59, w);
  w58 *= w85;
    project(w24, s36, (&w85), s59, w);
  w85 *= w76;
  w58 -= w85;
  rr=w28;
  *rr++ = w82;
  *rr++ = w87;
  *rr++ = w58;
  trans(w28, s61, w54, s60, iw);
  fill(w23, 24, 0.);
  mtimes(w21, s2, w54, s60, w23, s39, w, 0);
  fill(w54, 3, 0.);
  for (i=0, rr=w54; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w23+j, tt=w63+i*8; k<8; ++k) *rr += ss[k*3]**tt++;
  fill(w28, 3, 0.);
  for (i=0, rr=w28; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w5+j, tt=w54+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  rr=w54;
  for (i=0, cs=w59; i<3; ++i) *rr++ = *cs++;
  fill(w59, 3, 0.);
  mtimes(w54, s60, w67, s40, w59, s3, w, 0);
  for (i=0, rr=w59, cs=w59; i<3; ++i) (*rr++)  = (w3*(*cs++));
  rr=w1;
  for (i=0, cs=w28; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w59; i<3; ++i) *rr++ = *cs++;
  for (rr=w4, ss=w1+0; ss!=w1+6; ss+=1) *rr++ = *ss;
  for (rr=w116+7, ss=w4; rr!=w116+55; rr+=8) *rr = *ss++;
  trans(w116, s63, w117, s62, iw);
    project(w117, s62, w118, s64, w);
  if (res[2]) copy(w118, 104, res[2]);
  return 0;
}

void cablerobot_ode_incref(void) {
}

void cablerobot_ode_decref(void) {
}

int cablerobot_ode_n_in(void) { return 3;}

int cablerobot_ode_n_out(void) { return 3;}

const char* cablerobot_ode_name_in(int i){
  switch (i) {
  case 0: return "i0";
  case 1: return "i1";
  case 2: return "i2";
  default: return 0;
  }
}

const char* cablerobot_ode_name_out(int i){
  switch (i) {
  case 0: return "o0";
  case 1: return "o1";
  case 2: return "o2";
  default: return 0;
  }
}

const int* cablerobot_ode_sparsity_in(int i) {
  switch (i) {
  case 0: return s65;
  case 1: return s40;
  case 2: return s65;
  default: return 0;
  }
}

const int* cablerobot_ode_sparsity_out(int i) {
  switch (i) {
  case 0: return s65;
  case 1: return s34;
  case 2: return s64;
  default: return 0;
  }
}

int cablerobot_ode_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 11;
  if (sz_res) *sz_res = 7;
  if (sz_iw) *sz_iw = 14;
  if (sz_w) *sz_w = 1073;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
