/* This function was automatically generated by CasADi */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef real_t
#define real_t double
#define to_double(x) (double) x
#define to_int(x) (int) x
#endif /* real_t */

int cybermotion_output(const real_t** arg, real_t** res, int* iw, real_t* w, int mem);
void cybermotion_output_incref(void);
void cybermotion_output_decref(void);
int cybermotion_output_n_in(void);
int cybermotion_output_n_out(void);
const char* cybermotion_output_name_in(int i);
const char* cybermotion_output_name_out(int i);
const int* cybermotion_output_sparsity_in(int i);
const int* cybermotion_output_sparsity_out(int i);
int cybermotion_output_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w);
int cybermotion_ode(const real_t** arg, real_t** res, int* iw, real_t* w, int mem);
void cybermotion_ode_incref(void);
void cybermotion_ode_decref(void);
int cybermotion_ode_n_in(void);
int cybermotion_ode_n_out(void);
const char* cybermotion_ode_name_in(int i);
const char* cybermotion_ode_name_out(int i);
const int* cybermotion_ode_sparsity_in(int i);
const int* cybermotion_ode_sparsity_out(int i);
int cybermotion_ode_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w);
#ifdef __cplusplus
} /* extern "C" */
#endif
