/* This function was automatically generated by CasADi */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef real_t
#define real_t double
#define to_double(x) (double) x
#define to_int(x) (int) x
#endif /* real_t */

int cablerobot_output(const real_t** arg, real_t** res, int* iw, real_t* w, int mem);
void cablerobot_output_incref(void);
void cablerobot_output_decref(void);
int cablerobot_output_n_in(void);
int cablerobot_output_n_out(void);
const char* cablerobot_output_name_in(int i);
const char* cablerobot_output_name_out(int i);
const int* cablerobot_output_sparsity_in(int i);
const int* cablerobot_output_sparsity_out(int i);
int cablerobot_output_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w);
int cablerobot_ode(const real_t** arg, real_t** res, int* iw, real_t* w, int mem);
void cablerobot_ode_incref(void);
void cablerobot_ode_decref(void);
int cablerobot_ode_n_in(void);
int cablerobot_ode_n_out(void);
const char* cablerobot_ode_name_in(int i);
const char* cablerobot_ode_name_out(int i);
const int* cablerobot_ode_sparsity_in(int i);
const int* cablerobot_ode_sparsity_out(int i);
int cablerobot_ode_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w);
#ifdef __cplusplus
} /* extern "C" */
#endif
